### ISSUE TITLE
Verifier log full of errors - 'NoneType' object has no attribute 'operational_state'

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1046]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora Rawhide
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm + tpm2-abrmd
 * Keylime version: current upstream d456d4866dc1e883caf2f81e27f8e18992c28c5e

# Description 
In keylime-tests CI this error

## Expected behavior vs. actual behavior 
After deleting agent in the test the following errors appear in the verifier log
```
Jul 06 22:16:29 keylime_verifier[37276]: 2022-07-06 22:16:29.009 - keylime.cloudverifier - INFO - PUT returning 200 response for agent id: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:29 keylime_verifier[37276]: 2022-07-06 22:16:29.651 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
Jul 06 22:16:29 keylime_verifier[37276]: 2022-07-06 22:16:29.755 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:29 keylime_verifier[37277]: 2022-07-06 22:16:29.845 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:32 keylime_verifier[37276]: 2022-07-06 22:16:32.294 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:32 keylime_verifier[37277]: 2022-07-06 22:16:32.591 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:33 keylime_verifier[37276]: 2022-07-06 22:16:33.943 - tornado.access - INFO - 200 GET /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1) 2.10ms
Jul 06 22:16:33 keylime_verifier[37277]: 2022-07-06 22:16:33.973 - tornado.access - INFO - 202 DELETE /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1) 13.81ms
Jul 06 22:16:33 keylime_verifier[37277]: 2022-07-06 22:16:33.974 - keylime.cloudverifier - INFO - DELETE returning 202 response for agent id: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:33 keylime_verifier[37276]: 2022-07-06 22:16:33.989 - tornado.access - INFO - 200 GET /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1) 2.09ms
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.411 - tornado.access - INFO - 200 GET /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1) 3.04ms
Jul 06 22:16:34 keylime_verifier[37276]: 2022-07-06 22:16:34.572 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:34 keylime_verifier[37276]: 2022-07-06 22:16:34.576 - keylime.cloudverifier - WARNING - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 terminated by user.
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.840 - tornado.access - WARNING - 404 GET /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 (127.0.0.1) 7.93ms
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.890 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.893 - keylime.cloudverifier - ERROR - 'NoneType' object has no attribute 'boottime'
Jul 06 22:16:34 keylime_verifier[37277]: Traceback (most recent call last):
Jul 06 22:16:34 keylime_verifier[37277]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.4.1-py3.11.egg/keylime/cloud_verifier_tornado.py", line 827, in invoke_get_quote
Jul 06 22:16:34 keylime_verifier[37277]:     store_attestation_state(agentAttestState)
Jul 06 22:16:34 keylime_verifier[37277]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 06 22:16:34 keylime_verifier[37277]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.4.1-py3.11.egg/keylime/cloud_verifier_tornado.py", line 126, in store_attestation_state
Jul 06 22:16:34 keylime_verifier[37277]:     update_agent.boottime = agentAttestState.get_boottime()
Jul 06 22:16:34 keylime_verifier[37277]:     ^^^^^^^^^^^^^^^^^^^^^
Jul 06 22:16:34 keylime_verifier[37277]: AttributeError: 'NoneType' object has no attribute 'boottime'
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.897 - keylime.cloudverifier - ERROR - Polling thread error: 'NoneType' object has no attribute 'operational_state'
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.897 - keylime.cloudverifier - ERROR - 'NoneType' object has no attribute 'operational_state'
Jul 06 22:16:34 keylime_verifier[37277]: Traceback (most recent call last):
Jul 06 22:16:34 keylime_verifier[37277]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.4.1-py3.11.egg/keylime/cloud_verifier_tornado.py", line 957, in process_agent
Jul 06 22:16:34 keylime_verifier[37277]:     if stored_agent.operational_state == states.TERMINATED:
Jul 06 22:16:34 keylime_verifier[37277]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 06 22:16:34 keylime_verifier[37277]: AttributeError: 'NoneType' object has no attribute 'operational_state'
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.900 - keylime.cloudverifier - ERROR - Polling thread error: 'NoneType' object has no attribute 'operational_state'
Jul 06 22:16:34 keylime_verifier[37277]: 2022-07-06 22:16:34.900 - keylime.cloudverifier - ERROR - 'NoneType' object has no attribute 'operational_state'
Jul 06 22:16:34 keylime_verifier[37277]: Traceback (most recent call last):
Jul 06 22:16:34 keylime_verifier[37277]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.4.1-py3.11.egg/keylime/cloud_verifier_tornado.py", line 957, in process_agent
Jul 06 22:16:34 keylime_verifier[37277]:     if stored_agent.operational_state == states.TERMINATED:
Jul 06 22:16:34 keylime_verifier[37277]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 06 22:16:34 keylime_verifier[37277]: AttributeError: 'NoneType' object has no attribute 'operational_state'
```
The last Traceback appears in the log >100 times, before the verifier is forcibly killed by the test.

When running the test manually I could also see
```
Jul 07 02:15:09 keylime_verifier[7482]:     if stored_agent.operational_state == states.TERMINATED:
Jul 07 02:15:09 keylime_verifier[7482]: UnboundLocalError: local variable 'stored_agent' referenced before assignment
Jul 07 02:16:56 systemd-journald[367]: Suppressed 1127159 messages from keylime_verifier.service
```

The issue is either triggered by stopping the verifier at the end of the test but it is probably related to some other action performed by the test previously as other tests do not manifest this issue.

## Steps to reproduce problem
The problem is visible in CI in test
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/keylime_tenant-commands-on-localhost/test.sh#L105

# Relevant logs
Attached above

**Comment by THS-on** [comment]
Seems like a race condition in the verifier between different processes.
The agent is deleted in the DB, but on another process the event loop is still running.

`stored_agent` might be `None` if the agent was deleted, so we just should return then.
