### ISSUE TITLE
UnboundLocalError: local variable 'agent' referenced before assignment

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1072]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: CentOS Stream 9
 * Processor architecture: x86_64
 * TPM Manufacturer: HW one but don't know details ATM
 * Keylime version: current upstream 1a41a8a

# Description 
There was an issue with Rust agent accessing TPM (will be reported as a separate issue). The to that the agent hasn't been registered.
The following Traceback appeared later in registrar log.

```
Aug 11 07:35:54  keylime_registrar[9010]: 2022-08-11 07:35:54.001 - keylime.registrar - ERROR - SQLAlchemy Error: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
Aug 11 07:35:54  keylime_registrar[9010]: ----------------------------------------
Aug 11 07:35:54  keylime_registrar[9010]: Exception occurred during processing of request from ('127.0.0.1', 48902)
Aug 11 07:35:54  keylime_registrar[9010]: Traceback (most recent call last):
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/lib64/python3.9/socketserver.py", line 683, in process_request_thread
Aug 11 07:35:54  keylime_registrar[9010]:     self.finish_request(request, client_address)
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/lib64/python3.9/socketserver.py", line 360, in finish_request
Aug 11 07:35:54  keylime_registrar[9010]:     self.RequestHandlerClass(request, client_address, self)
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/lib64/python3.9/socketserver.py", line 747, in __init__
Aug 11 07:35:54  keylime_registrar[9010]:     self.handle()
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/lib64/python3.9/http/server.py", line 425, in handle
Aug 11 07:35:54  keylime_registrar[9010]:     self.handle_one_request()
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/lib64/python3.9/http/server.py", line 413, in handle_one_request
Aug 11 07:35:54  keylime_registrar[9010]:     method()
Aug 11 07:35:54  keylime_registrar[9010]:   File "/usr/local/lib/python3.9/site-packages/keylime-6.4.2-py3.9.egg/keylime/registrar_common.py", line 79, in do_GET
Aug 11 07:35:54  keylime_registrar[9010]:     if agent is None:
Aug 11 07:35:54  keylime_registrar[9010]: UnboundLocalError: local variable 'agent' referenced before assignment
Aug 11 07:35:54  keylime_registrar[9010]: ----------------------------------------
```

## Expected behavior vs. actual behavior 
There should not be a Traceback, agent variable should be properly initialized.

## Steps to reproduce problem
Not reliably. Were seen in test scenarios from keylime-tests when agent could not start properly.

# Relevant logs
above.

**Comment by maugustosilva** [comment]
Which kind of database are you using? I am asking because the `ERROR - SQLAlchemy Error: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)` caught my attention.

**Comment by kkaarreell** [comment]
Yes, this comes from one of the tests using either mysql or mariadb.
