### ISSUE TITLE
Since allowlist API implementation Keylime "local tests" show now SQL-related suspicious error.

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#1073]
# Environment
 * OS / version: Fedora Core 35
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: commit `1a41a8ae91242d4179a81c86072ce89e0d225eb1`

# Description 
I see what seems to be a - silent, incorrectly ignored - error while running tests on `keylime`. I don't remember seeing the error before the changes in the database introduced by the `allowlist` API (@mbestavros please confirm)

## Expected behavior vs. actual behavior 
Local tests should complete without displaying errors.

## Steps to reproduce problem
1. `git clone https://github.com/keylime/keylime.git`
2. `cd ~/keylime/.ci; ./run_local.sh ${PWD}/..`

# Relevant logs
```
Captured stdout for test.test_restful.TestRestful.test_040_agent_quotes_integrity_get

2022-08-11 16:54:21.491 - keylime.cloudverifier - ERROR - (sqlite3.IntegrityError) UNIQUE constraint failed: allowlists.name
[SQL: INSERT INTO allowlists (name, tpm_policy, ima_policy) VALUES (?, ?, ?)]
[parameters: ('d432fbb3-d2f1-4a97-9ef7-75bd81c00000', None, '{"allowlist": {"meta": {"version": 5}, "release": 0, "hashes": {"boot_aggregate": ["0000000000000000000000000000000000000000", "000000000000000000000 ... (29 characters truncated) ... 00000000000000"]}, "keyrings": {}, "ima": {"ignored_keyrings": [], "log_hash_alg": "sha1", "dm_policy": null}, "ima-buf": {}}, "exclude": "WyIqIl0="}')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: allowlists.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime/cloud_verifier_tornado.py", line 498, in post
    session.commit()
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: allowlists.name
[SQL: INSERT INTO allowlists (name, tpm_policy, ima_policy) VALUES (?, ?, ?)]
[parameters: ('d432fbb3-d2f1-4a97-9ef7-75bd81c00000', None, '{"allowlist": {"meta": {"version": 5}, "release": 0, "hashes": {"boot_aggregate": ["0000000000000000000000000000000000000000", "000000000000000000000 ... (29 characters truncated) ... 00000000000000"]}, "keyrings": {}, "ima": {"ignored_keyrings": [], "log_hash_alg": "sha1", "dm_policy": null}, "ima-buf": {}}, "exclude": "WyIqIl0="}')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2022-08-11 16:54:21.509 - keylime.cloudagent - INFO - GET invoked from ('127.0.0.1', 42004) with uri: /v2.0/quotes/integrity?nonce=l3MFWppao8YOvPF1eD0H&mask=0x408000&partial=1
2022-08-11 16:54:21.569 - keylime.cloudagent - INFO - GET integrity quote returning 200 response.
Captured stderr for test.test_restful.TestRestful.test_040_agent_quotes_integrity_get
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
```

**Comment by mbestavros** [comment]
Thanks for the report @maugustosilva! I've got a fix open here: https://github.com/keylime/keylime/pull/1074
