### ISSUE TITLE
keylime_tenant traceback not providing specific enough output when not able to load PEM

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1081]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 35
 * Processor architecture: x86_64
 * TPM Manufacturer:  swtpm
 * Keylime version: upstream d8968cb

# Description 
I am running a virtual system with TPM provided by QEMU through swtpm.
swtpm stores its TPM CA certificates in /var/lib/swtpm-localca so I have pointed
`tpm_cert_store = /var/lib/swtpm-localca/`
so I can enable `require_ek_cert`.

However, swtpm does not only store certificates in this dir bug also private keys that also have `.pem` suffix.
`keylime_tenant` seems to fail to load these files and errors out.
While this is sort of expected, it would be nice if at least the name of a file that could not be loaded was presented.
Even better, there won't be any traceback and only error mentioning the respective file would be printed.

## Expected behavior vs. actual behavior 
Traceback not mentioning specific file
PEM file that could not be loaded should be listed.

## Steps to reproduce problem
1. described above

# Relevant logs

```
# ls /var/lib/swtpm-localca/
certserial      signkey.pem                    swtpm-localca-rootca-cert.srl
issuercert.pem  swtpm-localca-rootca-cert.pem  swtpm-localca-rootca-privkey.pem

# keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c update'
Reading configuration from ['/etc/keylime.conf']
2022-08-22 11:36:42.220 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-08-22 11:36:42.224 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-08-22 11:36:42.224 - keylime.registrar_client - WARNING - TLS is enabled.
2022-08-22 11:36:42.224 - keylime.registrar_client - INFO - Setting up client TLS...
2022-08-22 11:36:42.253 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2022-08-22 11:36:42.298 - keylime.tenant - INFO - Verifier at 127.0.0.1 with Port 8881 does not have agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000.
2022-08-22 11:36:42.299 - keylime.tenant - ERROR - Could not get status of agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 from verifier 127.0.0.1.
<Response [200]>
2022-08-22 11:36:42.413 - keylime.tpm - WARNING - PCR #0 in quote not found in tpm_policy, skipping.
2022-08-22 11:36:42.414 - keylime.tpm - ERROR - Unable to load certificate. See https://cryptography.io/en/latest/faq.html#why-can-t-i-import-my-pem-file for more details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tpm/tpm_main.py", line 830, in verify_ek
    signcert = x509.load_pem_x509_certificate(
  File "/usr/lib64/python3.10/site-packages/cryptography/x509/base.py", line 399, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/usr/lib64/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1350, in load_pem_x509_certificate
    raise ValueError(
ValueError: Unable to load certificate. See https://cryptography.io/en/latest/faq.html#why-can-t-i-import-my-pem-file for more details.
2022-08-22 11:36:42.419 - keylime.tenant - ERROR - Error processing ek/ekcert. Does this TPM have a valid EK?
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tpm/tpm_main.py", line 830, in verify_ek
    signcert = x509.load_pem_x509_certificate(
  File "/usr/lib64/python3.10/site-packages/cryptography/x509/base.py", line 399, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/usr/lib64/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1350, in load_pem_x509_certificate
    raise ValueError(
ValueError: Unable to load certificate. See https://cryptography.io/en/latest/faq.html#why-can-t-i-import-my-pem-file for more details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/cmd/tenant.py", line 10, in main
    tenant.main()
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tenant.py", line 1631, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tenant.py", line 1113, in do_quote
    if not self.validate_tpm_quote(public_key, quote, algorithms.Hash(hash_alg)):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tenant.py", line 575, in validate_tpm_quote
    if not self.check_ek(self.registrar_data["ekcert"]):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tenant.py", line 522, in check_ek
    elif not self.tpm_instance.verify_ek(base64.b64decode(ekcert)):
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tpm/tpm_main.py", line 853, in verify_ek
    raise Exception("Error processing ek/ekcert. Does this TPM have a valid EK?").with_traceback(
  File "/usr/local/lib/python3.10/site-packages/keylime-6.4.2-py3.10.egg/keylime/tpm/tpm_main.py", line 830, in verify_ek
    signcert = x509.load_pem_x509_certificate(
  File "/usr/lib64/python3.10/site-packages/cryptography/x509/base.py", line 399, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/usr/lib64/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1350, in load_pem_x509_certificate
    raise ValueError(
Exception: Error processing ek/ekcert. Does this TPM have a valid EK?
```

**Comment by stefanberger** [comment]
When I have private keys in the certs directory nothing like this happens when the EK cert is verified as part of the `-C add/update` tenant command. What operation were you doing? I am using python cryptography v40.0.

**Comment by kkaarreell** [comment]
Hi @stefanberger , I am sorry for a delayed response. I believe that the actual problem was that my issuercert.pem file was corrupted. At least I seem to be able to reproduce the traceback when
```rlRun "> $CACERTDIR/issuercert.pem"```
in https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/ek-cert-use-ek_handle-custom-ca_certs/test.sh#L72
So the only problem here are just difficulties to identify which PEM file cannot be processed.

**Comment by stefanberger** [comment]
@kkaarreell right, a malformed certificate or key throws this error. See PR #1488 for a resolution.

**Comment by THS-on** [comment]
@stefanberger just to confirm we can close this issue right?

**Comment by stefanberger** [comment]
> @stefanberger just to confirm we can close this issue right?

I think so.
