### ISSUE TITLE
Adding agent with keylime_tenant results in 404 and `keylime.tpm2 - ERROR - wrong public key type`

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#109]
# Environment
 * OS / version: Fedora 29
 * Processor architecture: x86_64
 * TPM Manufacturer: Intel
 * Keylime version: master

# Description 

Run the following command:

`keylime_tenant -v 1<verifier_ip> -t <agent_ip> -f /root/excludes.txt --uuid D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --whitelist /root/whitelist.txt --exclude /root/excludes.txt`

The verifier logs

    keylime.cloudverifier - INFO - PUT returning 404 response. agent id: D432FBB3-D2F1-4A97-9EF7-75BD81C00000 not found.

The keylime_tenant shows the following stack trace:

```
2019-04-16 09:30:59.533 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2019-04-16 09:30:59.533 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2019-04-16 09:30:59.538 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2019-04-16 09:30:59.538 - keylime.tenant - INFO - vTPM PCR Mask from policy is 0x808000
2019-04-16 09:31:01.424 - keylime.registrar_client - INFO - Setting up client TLS...
2019-04-16 09:31:01.432 - keylime.registrar_client - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2019-04-16 09:31:01.465 - keylime.tpm2 - ERROR - wrong public key type
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tpm2.py", line 625, in verify_ek
    signcert = M2Crypto.X509.load_cert_string(trusted_certs[signer])
  File "/usr/lib64/python2.7/site-packages/M2Crypto/X509.py", line 851, in load_cert_string
    return load_cert_bio(bio, format)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/X509.py", line 827, in load_cert_bio
    cptr = m2.x509_read_pem(bio._ptr())
X509Error: wrong public key type
Traceback (most recent call last):
  File "/usr/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_tenant')()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tenant.py", line 732, in main
    mytenant.do_quote()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tenant.py", line 624, in do_quote
    self.do_cvstop() 
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tenant.py", line 527, in do_cvstop
    raise UserError("Update command response: %d Unexpected response from Cloud Verifier."%response.status_code)
keylime.tenant.UserError: Update command response: 404 Unexpected response from Cloud Verifier.
```

## Steps to reproduce problem

Steps outlined above.

**Comment by lukehinds** [comment]
I have suspicion it has something to do with https://github.com/keylime/python-keylime/commit/82b9c670c0a118966cbfdf4004fddb7ab3a196d4#diff-242fc79fc17586955d7b4bcd2c12f4d5

I don't believe it should be responding with a 404 (UUID not found), when we are trying to add the agent.

**Comment by jetwhiz** [comment]
Is this with a physical TPM or emulated?  That part of the code should not be running for an emulated TPM (verify_ek, which should be disabled in keylime.conf for emulated). 

I'm also not sure why the verifier is performing a PUT (reactivate) when you're trying to perform a first-time 'add' command, unless the agent had already been provisioned?

**Comment by lukehinds** [comment]
Its a physical TPM

**Comment by jetwhiz** [comment]
If you run `tpm2_nvlist` on that machine, does it list a key under slot `0x1c00002`?  

If it does exist, then can you export it and see what it looks like: 
`tpm2_nvread -x 0x1c00002 -s <KEY_SIZE_FROM_ABOVE_COMMAND> -f /my/output/file`
