### ISSUE TITLE
Graceful handling of Agent connection failures

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#111]
# Environment
 * OS / version: Fedora 29
 * Processor architecture: x86_64
 * TPM Manufacturer: N/A
 * Keylime version: master

# Description 

Should the agent not be able to connect to its assigned register, a stack trace is displayed and nothing is logged to `cloudagent.log` - this would make it challenging to debug at a later stage for adminstrators of keylime agents

Stack trace

```
2019-04-17 12:02:25.375 - keylime.cloudagent - INFO - Agent UUID: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/cloud_agent.py", line 519, in main
    keyblob = registrar_client.doRegisterAgent(registrar_ip,registrar_port,agent_uuid,tpm_version,ek,ekcert,aik,ek_tpm,aik_name)
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/registrar_client.py", line 139, in doRegisterAgent
    context=None)
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tornado_requests.py", line 38, in request
    response = http_client.fetch(request)
  File "/usr/lib64/python2.7/site-packages/tornado/httpclient.py", line 118, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 581, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
socket.error: [Errno 111] Connection refused
```

Instead we could perform a connection test, implement a retry and log the result to `cloudagent.log` for later debug information.

**Comment by lukehinds** [comment]
keep alive

**Comment by lukehinds** [comment]
Keep
