### ISSUE TITLE
`keylime_tenant --help` backtraces if logging config exists but is not readable

### ISSUE THREAD

**Issue by crobinso** [keylime/keylime#1116]
# Environment
 * OS / version: Fedora 36
 * Keylime version: git

# Reproducer

```
$ KEYLIME_LOGGING_CONFIG=/etc/keylime.conf ./bin/keylime_tenant --help
Reading configuration from []
Traceback (most recent call last):
  File "/home/crobinso/.local/share/virtualenvs/keylime-x34CgAWE/./bin/keylime_tenant", line 5, in <module>
    from keylime.cmd.tenant import main
  File "/home/crobinso/.local/share/virtualenvs/keylime-x34CgAWE/lib/python3.10/site-packages/keylime/cmd/tenant.py", line 3, in <module>
    from keylime import keylime_logging, tenant
  File "/home/crobinso/.local/share/virtualenvs/keylime-x34CgAWE/lib/python3.10/site-packages/keylime/keylime_logging.py", line 15, in <module>
    logging_config.fileConfig(config.get_config("logging"))
  File "/usr/lib64/python3.10/logging/config.py", line 72, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib64/python3.10/logging/config.py", line 105, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib64/python3.10/configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

This is kind of an artificial reporducer, so let me explain: keylime in fedora 36 is the non-latest 6.4.3 version. Run `keylime_tenant --help` as non-root with stock packages, and you get a similar backtrace. The issue is the config lookup just checks for essentially `os.path.exists("/etc/keylime.conf")` and not whether the user can read the config, and the error flows from there.

Upstream code config layout has changed, but the root problem still appears to be there, but whether it's busted out of the box or not on Fedora will depend on `/etc/keylime` directory permissions I think.

**Comment by THS-on** [comment]
@ansasaki can you look into adding an error message when no Keylime configuration was found be the config module?

**Comment by ansasaki** [comment]
> @ansasaki can you look into adding an error message when no Keylime configuration was found be the config module?

Sure, I'll add an error message for this case. I think I will also include a check for the configuration version.

**Comment by crobinso** [comment]
Note, it may not just be about path existing. For unpriv user on Fedora 36 `os.path.exists("/etc/keylime.conf")` will succeed but `open("/etc/keylime.conf", "r")` will fail. So may need an `os.access` check too or something like that
