### ISSUE TITLE
Verifier allowlist implementation bug causes double insert sqlalchemy errors in extreme circumstances

### ISSUE THREAD

**Issue by galmasi** [keylime/keylime#1146]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 22.04
 * Processor architecture: x86_64
 * TPM Manufacturer: virtual (irrelevant)
 * Keylime version: 6.5.1+

# Description 

In unusual circumstances the current implementation of the keylime allowlist database causes sql failures by attempting to insert entries into the sql database with duplicated indices.

This problem was found "in the wild" on a large scaling cluster where transient mysql access failures are known to happen. However, we have managed to reproduce the problem by causing a mysql connection failure explicitly, then attempting to recover from it.

Generally speaking, to produce the error reliably, one have a running a keylime verifier attached to a mysql database and an ongoing attestation process. No need for IMA to be enabled.

Next, trigger the sequence of events by killing mysql connections while attestation is ongoing. This produces an (expected) attestation failure due to loss of connectivity to mysql.

The actual problem occurs during an attempt to restore attestation. This involves restarting the keylime verifier and attempting to re-add the agent for attestation. The last step produces an sql failure ("duplicate entry") that could be prevented by coding allowlist operations with care.

## Expected behavior vs. actual behavior 

Expected behavior would be that even if an agent stopped attesting amidst a transient mysql failure, re-adding the agent should not cause duplicate database entries. Actual behavior is that it *does*.

## Root cause analysis

The problem seems to be centered around line 568 of `cloud_verifier_tornado.py`, where no check is made whether a `VerifierAllowList` entry exists for an agent before one is inserted. I expect that the fix is trivial -- force-remove the old entry or avoid overwriting it without causing the verifier to throw an exception aborting the `add` process.

## Steps to reproduce problem

1. Set up a keylime verifier running against a  mysql database (important not to use sqlite)
2. Turn on attestation one an agent -- in our case we did not turn on IMA at all, merely IDENT attestation.
3. Get into the database with mysql or mysqladmin, and KILL ALL CONNECTIONS (to simulate a network failure)
4. Check the verifier -- attestation should haved failed with an SQLAlchemy error
5. Restart the verifier to force it to re-establish connectivity to the database.
6. Turn off attestation; turn attestation back on (with keylime_tenant -c delete ; keylime_tenant -c add
7. Expect to see new failures caused by duplicate insertion of agent's allow list.

# Relevant logs

### 1. verifier log extract from ongoing (correct) attestation, before sequence of errors was triggered
```
2022-10-28 15:46:52.734 - keylime.cloudverifier_common - DEBUG - received data for agent 00000000-0000-0000-0000-5254180d0221, quote: r/1RDR4AYACIAC8Ezixdk0WqY3wqt8BL7KcN8fDikjeyCKSRlztRegFBnABRCVHkxOExCTUxXY2wwTzJKUEVZUAAAAAAEi9PVAAAAAwAAAAABIBkQIwAWNjYAAAABAAsDAAABACBT6m61pePE9cQ4kaX0I6Q8WHlI92BwokvuBHQ/kj4UdA==:ABQACwEAQ+wniU1QEHMadeTw7qM+OBGN2xcG7ucU7MD0mQuJo9U/RaMzs1OBynetLLELEcENVVJmp59M/XVfYEK5SD1GEvlnIb2yriBNu3yN6v/RGH3c1w6tssv9frhT+S7DA8ANK7bRzO8QiWewp65nG3LahXp68GV1Ul3FAhcH56W2Zrl1aRQ8mJGqHrgfIVCH67reVrtwLKr/5yA+EFgv9maVwJomxZhjUMFdg7lg5Ua27+GafxLilHF3rjp8vuzLqP7F/X95lb9X57oSrVBHGJgKmoceDT74j3H8CZ0nsWrZlgG/7N5CCkvNUqygdCMibbtWIDja3BP8reR3RXd3QhRKYg==:AQAAAAsAAwAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAgALKNzVhYLCoQdV+1kBjMeB/D2IvBlNynVEW6RChP7P+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=, nonce: BTy18LBMLWcl0O2JPEYP, public key(b64): Tm9uZQ==, ima_measurement_list: False, ima_measurement_list_entry: 0, measured_boot_log: False, boottime: 1666895768
```

### 2. extract of procedure to contact mysql and kill connections
`100.64.24.2` in this case is the IP address on which a verifier is running

```
mysql> select * from information_schema.processlist where host like '%100.64.24.2%';
+----+------+-------------------+---------+---------+------+-------+------+
| ID | USER | HOST              | DB      | COMMAND | TIME | STATE | INFO |
+----+------+-------------------+---------+---------+------+-------+------+
| 18 | root | 100.64.24.2:58260 | small24 | Sleep   |  191 |       | NULL |
| 59 | root | 100.64.24.2:44486 | small24 | Sleep   |   63 |       | NULL |
| 68 | root | 100.64.24.2:40092 | small24 | Sleep   |   31 |       | NULL |
+----+------+-------------------+---------+---------+------+-------+------+
3 rows in set (0.00 sec)

mysql> kill 18;
<kill all other processes>
```

### 3. (expected) Verifier failure caused by killing mysql processees

```
[SQL: SELECT verifiermain.agent_id AS verifiermain_agent_id, verifiermain.v AS verifiermain_v, verifiermain.ip AS verifiermain_ip, verifiermain.verifier_id AS verifiermain_verifier_id, verifiermain.verifier_ip AS verifiermain_verifier_ip, verifiermain.verifier_port AS verifiermain_verifier_port, verifiermain.port AS verifiermain_port, verifiermain.operational_state AS verifiermain_operational_state, verifiermain.public_key AS verifiermain_public_key, verifiermain.tpm_policy AS verifiermain_tpm_policy, verifiermain.meta_data AS verifiermain_meta_data, verifiermain.ima_policy_id AS verifiermain_ima_policy_id, verifiermain.ima_sign_verification_keys AS verifiermain_ima_sign_verification_keys, verifiermain.mb_refstate AS verifiermain_mb_refstate, verifiermain.revocation_key AS verifiermain_revocation_key, verifiermain.accept_tpm_hash_algs AS verifiermain_accept_tpm_hash_algs, verifiermain.accept_tpm_encryption_algs AS verifiermain_accept_tpm_encryption_algs, verifiermain.accept_tpm_signing_algs AS verifiermain_accept_tpm_signing_algs, verifiermain.hash_alg AS verifiermain_hash_alg, verifiermain.enc_alg AS verifiermain_enc_alg, verifiermain.sign_alg AS verifiermain_sign_alg, verifiermain.boottime AS verifiermain_boottime, verifiermain.ima_pcrs AS verifiermain_ima_pcrs, verifiermain.pcr10 AS verifiermain_pcr10, verifiermain.next_ima_ml_entry AS verifiermain_next_ima_ml_entry, verifiermain.severity_level AS verifiermain_severity_level, verifiermain.last_event_id AS verifiermain_last_event_id, verifiermain.learned_ima_keyrings AS verifiermain_learned_ima_keyrings, verifiermain.supported_version AS verifiermain_supported_version, verifiermain.ak_tpm AS verifiermain_ak_tpm, verifiermain.mtls_cert AS verifiermain_mtls_cert, verifiermain.attestation_count AS verifiermain_attestation_count, verifiermain.last_received_quote AS verifiermain_last_received_quote, verifiermain.tpm_clockinfo AS verifiermain_tpm_clockinfo
FROM verifiermain
WHERE verifiermain.agent_id = %(param_1)s]
[parameters: {'param_1': '00000000-0000-0000-0000-5254180d0221'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2022-10-27 19:00:44.980 - keylime.verifier - ERROR - (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT verifiermain.agent_id AS verifiermain_agent_id, verifiermain.v AS verifiermain_v, verifiermain.ip AS verifiermain_ip, verifiermain.verifier_id AS verifiermain_verifier_id, verifiermain.verifier_ip AS verifiermain_verifier_ip, verifiermain.verifier_port AS verifiermain_verifier_port, verifiermain.port AS verifiermain_port, verifiermain.operational_state AS verifiermain_operational_state, verifiermain.public_key AS verifiermain_public_key, verifiermain.tpm_policy AS verifiermain_tpm_policy, verifiermain.meta_data AS verifiermain_meta_data, verifiermain.ima_policy_id AS verifiermain_ima_policy_id, verifiermain.ima_sign_verification_keys AS verifiermain_ima_sign_verification_keys, verifiermain.mb_refstate AS verifiermain_mb_refstate, verifiermain.revocation_key AS verifiermain_revocation_key, verifiermain.accept_tpm_hash_algs AS verifiermain_accept_tpm_hash_algs, verifiermain.accept_tpm_encryption_algs AS verifiermain_accept_tpm_encryption_algs, verifiermain.accept_tpm_signing_algs AS verifiermain_accept_tpm_signing_algs, verifiermain.hash_alg AS verifiermain_hash_alg, verifiermain.enc_alg AS verifiermain_enc_alg, verifiermain.sign_alg AS verifiermain_sign_alg, verifiermain.boottime AS verifiermain_boottime, verifiermain.ima_pcrs AS verifiermain_ima_pcrs, verifiermain.pcr10 AS verifiermain_pcr10, verifiermain.next_ima_ml_entry AS verifiermain_next_ima_ml_entry, verifiermain.severity_level AS verifiermain_severity_level, verifiermain.last_event_id AS verifiermain_last_event_id, verifiermain.learned_ima_keyrings AS verifiermain_learned_ima_keyrings, verifiermain.supported_version AS verifiermain_supported_version, verifiermain.ak_tpm AS verifiermain_ak_tpm, verifiermain.mtls_cert AS verifiermain_mtls_cert, verifiermain.attestation_count AS verifiermain_attestation_count, verifiermain.last_received_quote AS verifiermain_last_received_quote, verifiermain.tpm_clockinfo AS verifiermain_tpm_clockinfo
FROM verifiermain
WHERE verifiermain.agent_id = %(param_1)s]
[parameters: {'param_1': '00000000-0000-0000-0000-5254180d0221'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 646, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 698, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

```

### 4. Verifier log when attempting to re-add agent after the verifier restart
```
[SQL: INSERT INTO allowlists (name, tpm_policy, ima_policy) VALUES (%(name)s, %(tpm_policy)s, %(ima_policy)s)]
[parameters: {'name': '00000000-0000-0000-0000-5254180d0221', 'tpm_policy': None, 'ima_policy': '{"allowlist": {"meta": {"version": 5}, "release": 0, "hashes": {"boot_aggregate": ["0000000000000000000000000000000000000000", "000000000000000000000 ... (21 characters truncated) ... 0000000000000000000000"]}, "keyrings": {}, "ima": {"ignored_keyrings": [], "log_hash_alg": "sha1", "dm_policy": null}, "ima-buf": {}}, "exclude": []}'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.9/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.9/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '00000000-0000-0000-0000-5254180d0221' for key 'allowlists.uniq_allowlists0name'")
```

**Comment by maugustosilva** [comment]
A PR with a fix was merged.
