### ISSUE TITLE
test_ima_verification.py: Switch from sha1 to sha256

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1202]
I have found out that in keylime-tests we were running upstream tests incorrectly, as a result some test scripts were not executed.
This is now fixed with https://github.com/RedHat-SP-Security/keylime-tests/pull/246/ but on C9S two tests in test_ima_verification.py are failing because sha1 is not considered secure for RSA signatures.

Please, switch to sha256 so we can run this test in CI for C9S.

```
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   Run test_ima_verification.py
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [ 00:10:40 ] :: [  BEGIN   ] :: Running 'sed -i 's#context =.*#context = test_ima_verification.py#' /var/tmp/limeLib/coverage/coveragerc'
:: [ 00:10:40 ] :: [   PASS   ] :: Command 'sed -i 's#context =.*#context = test_ima_verification.py#' /var/tmp/limeLib/coverage/coveragerc' (Expected 0, got 0)
:: [ 00:10:40 ] :: [  BEGIN   ] :: Running '/usr/local/bin/coverage run -m unittest /tmp/tmp.rEWmleoUWx/test/test_ima_verification.py -v'
/usr/local/lib64/python3.9/site-packages/coverage/inorout.py:497: CoverageWarning: Already imported a file that will be measured: /usr/local/bin/coverage (already-imported)
  self.warn(msg, slug="already-imported")
test_ima_buf_verification (test_ima_verification.TestIMAVerification)
The verification of ima-buf entries supporting keys loaded onto keyrings ... Reading configuration from ['/etc/keylime/logging.conf']
2022-11-22 00:10:41.581 - keylime.file_signatures - DEBUG - Extracted keyidv2 from cert: 0x2cb6058c
2022-11-22 00:10:41.582 - keylime.file_signatures - DEBUG - Added key with keyid: 0x2cb6058c
ok
test_iterative_attestation (test_ima_verification.TestIMAVerification)
Test that the resulting pcr value is as expected by subsequently feeding a measurement list. ... 2022-11-22 00:10:41.582 - keylime.ima - DEBUG - Found match at linenum 1
2022-11-22 00:10:41.583 - keylime.ima - DEBUG - Found match at linenum 1
2022-11-22 00:10:41.583 - keylime.ima - DEBUG - Found match at linenum 1
ok
test_measurment_verification (test_ima_verification.TestIMAVerification)
Test IMA measurement list verification ... 2022-11-22 00:10:41.583 - keylime.ima - WARNING - No boot_aggregate value found in allowlist, adding an empty one
2022-11-22 00:10:41.584 - keylime.ima - WARNING - Hashes for file boot_aggregate don't match e4cb9f5709c88376b5fc3743cd88e76b9aae8f3d992d845678de5215edb31216 not in ['0000000000000000000000000000000000000000', '0000000000000000000000000000000000000000000000000000000000000000']
2022-11-22 00:10:41.585 - keylime.ima - WARNING - File not found in allowlist: /lib/modules/5.4.48-openpower1/kernel/drivers/usb/common/usb-common.ko
2022-11-22 00:10:41.585 - keylime.ima - WARNING - File not found in allowlist: /lib/modules/5.4.48-openpower1/kernel/drivers/gpu/drm/drm_panel_orientation_quirks.ko
2022-11-22 00:10:41.585 - keylime.ima - ERROR - IMA ERRORS: Some entries couldn't be validated. Number of failures in modes: ImaSig 3.
ok
test_mixed_verfication (test_ima_verification.TestIMAVerification)
Test verification using allowlist and keys ... 2022-11-22 00:10:41.585 - keylime.ima - WARNING - No boot_aggregate value found in allowlist, adding an empty one
2022-11-22 00:10:41.588 - keylime.file_signatures - DEBUG - Added key with keyid: 0xf3452d23
2022-11-22 00:10:41.593 - keylime.file_signatures - DEBUG - Added key with keyid: 0x531f4025
ERROR
test_read_allowlist (test_ima_verification.TestIMAVerification)
Test reading and processing of the IMA allow-list ... 2022-11-22 00:10:41.596 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.597 - keylime.ima - DEBUG - Loaded allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt with checksum 6b010e359bbcebafb9b3e5010c302c94d29e249f86ae6293339506041aeebd41
2022-11-22 00:10:41.597 - keylime.ima - DEBUG - Allowlist did not have a checksum provided, will add calculated checksum to bundle
2022-11-22 00:10:41.597 - keylime.ima - DEBUG - Converting legacy allowlist format to JSON
2022-11-22 00:10:41.597 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Loaded allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt with checksum 6b010e359bbcebafb9b3e5010c302c94d29e249f86ae6293339506041aeebd41
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Allowlist passed checksum validation
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Converting legacy allowlist format to JSON
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Loaded allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt with checksum 6b010e359bbcebafb9b3e5010c302c94d29e249f86ae6293339506041aeebd41
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.598 - keylime.ima - DEBUG - Loading signature (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.sig) and key (/tmp/tmp.rEWmleoUWx/test/data/gpg-sig.pub) and checking against allowlist (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt)
2022-11-22 00:10:41.621 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.643 - keylime.ima - DEBUG - Allowlist passed signature verification
2022-11-22 00:10:41.643 - keylime.ima - DEBUG - Loaded allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt with checksum 6b010e359bbcebafb9b3e5010c302c94d29e249f86ae6293339506041aeebd41
2022-11-22 00:10:41.643 - keylime.ima - DEBUG - Allowlist did not have a checksum provided, will add calculated checksum to bundle
2022-11-22 00:10:41.649 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.669 - keylime.ima - INFO - Allowlist signature validation passed.
2022-11-22 00:10:41.669 - keylime.ima - DEBUG - Converting legacy allowlist format to JSON
2022-11-22 00:10:41.670 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.670 - keylime.ima - DEBUG - Loading signature (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-bad.sig) and key (/tmp/tmp.rEWmleoUWx/test/data/gpg-sig.pub) and checking against allowlist (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt)
2022-11-22 00:10:41.676 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.696 - keylime.signing - WARNING - Unable to verify signature: 86FD996E85DD86A5F599B4532D41CC62EE157581: No public key
2022-11-22 00:10:41.702 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.721 - keylime.signing - WARNING - Unable to verify signature: 86FD996E85DD86A5F599B4532D41CC62EE157581: No public key
2022-11-22 00:10:41.722 - keylime.ima - DEBUG - Loading allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt
2022-11-22 00:10:41.722 - keylime.ima - DEBUG - Loading signature (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.sig) and key (/tmp/tmp.rEWmleoUWx/test/data/gpg-sig.pub) and checking against allowlist (/tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt)
2022-11-22 00:10:41.727 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.747 - keylime.ima - DEBUG - Allowlist passed signature verification
2022-11-22 00:10:41.747 - keylime.ima - DEBUG - Loaded allowlist from /tmp/tmp.rEWmleoUWx/test/data/ima-allowlist-short.txt with checksum 6b010e359bbcebafb9b3e5010c302c94d29e249f86ae6293339506041aeebd41
2022-11-22 00:10:41.747 - keylime.ima - DEBUG - Allowlist passed checksum validation
2022-11-22 00:10:41.753 - keylime.signing - DEBUG - Importing GPG key
2022-11-22 00:10:41.774 - keylime.ima - INFO - Allowlist signature validation passed.
2022-11-22 00:10:41.774 - keylime.ima - DEBUG - Converting legacy allowlist format to JSON
ok
test_signature_verification (test_ima_verification.TestIMAVerification)
Test the signature verification ... 2022-11-22 00:10:41.776 - keylime.file_signatures - WARNING - No key with id 0xf3452d23 available
2022-11-22 00:10:41.776 - keylime.ima - WARNING - signature for file /usr/bin/dd is not valid
2022-11-22 00:10:41.776 - keylime.file_signatures - WARNING - No key with id 0x531f4025 available
2022-11-22 00:10:41.777 - keylime.ima - WARNING - signature for file /usr/bin/zmore is not valid
2022-11-22 00:10:41.777 - keylime.ima - ERROR - IMA ERRORS: Some entries couldn't be validated. Number of failures in modes: ImaSig 2.
2022-11-22 00:10:41.778 - keylime.file_signatures - DEBUG - Added key with keyid: 0xf3452d23
ERROR

======================================================================
ERROR: test_mixed_verfication (test_ima_verification.TestIMAVerification)
Test verification using allowlist and keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.rEWmleoUWx/test/test_ima_verification.py", line 203, in test_mixed_verfication
    _, failure = ima.process_measurement_list(
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 391, in process_measurement_list
    running_hash, failure = _process_measurement_list(
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 339, in _process_measurement_list
    validation_failure = entry.invalid()
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ast.py", line 413, in invalid
    failure.merge(self.mode.is_data_valid(self._validator))
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ast.py", line 292, in is_data_valid
    return validator.get_validator(type(self))(self.digest, self.path, self.signature)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 191, in _validate_ima_sig
    if not ima_keyrings.integrity_digsig_verify(signature.data, digest.hash, digest.algorithm):
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 356, in integrity_digsig_verify
    return self._asymmetric_verify(signature, filehash, filehash_type)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 335, in _asymmetric_verify
    ImaKeyrings._verify(pubkey, signature[hdrlen:], filehash, hashfunc())
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 284, in _verify
    pubkey.verify(sig, filehash, padding.PKCS1v15(), Prehashed(hashfunc))
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 571, in verify
    return _rsa_sig_verify(
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 270, in _rsa_sig_verify
    pkey_ctx = _rsa_sig_setup(
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 213, in _rsa_sig_setup
    raise UnsupportedAlgorithm(
cryptography.exceptions.UnsupportedAlgorithm: sha1 is not supported by this backend for RSA signing.

======================================================================
ERROR: test_signature_verification (test_ima_verification.TestIMAVerification)
Test the signature verification
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.rEWmleoUWx/test/test_ima_verification.py", line 128, in test_signature_verification
    _, failure = ima.process_measurement_list(AgentAttestState("1"), lines[0:1], ima_keyrings=keyrings)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 391, in process_measurement_list
    running_hash, failure = _process_measurement_list(
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 339, in _process_measurement_list
    validation_failure = entry.invalid()
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ast.py", line 413, in invalid
    failure.merge(self.mode.is_data_valid(self._validator))
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ast.py", line 292, in is_data_valid
    return validator.get_validator(type(self))(self.digest, self.path, self.signature)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/ima.py", line 191, in _validate_ima_sig
    if not ima_keyrings.integrity_digsig_verify(signature.data, digest.hash, digest.algorithm):
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 356, in integrity_digsig_verify
    return self._asymmetric_verify(signature, filehash, filehash_type)
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 335, in _asymmetric_verify
    ImaKeyrings._verify(pubkey, signature[hdrlen:], filehash, hashfunc())
  File "/usr/local/lib/python3.9/site-packages/keylime-6.5.2-py3.9.egg/keylime/ima/file_signatures.py", line 284, in _verify
    pubkey.verify(sig, filehash, padding.PKCS1v15(), Prehashed(hashfunc))
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 571, in verify
    return _rsa_sig_verify(
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 270, in _rsa_sig_verify
    pkey_ctx = _rsa_sig_setup(
  File "/usr/lib64/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 213, in _rsa_sig_setup
    raise UnsupportedAlgorithm(
cryptography.exceptions.UnsupportedAlgorithm: sha1 is not supported by this backend for RSA signing.

----------------------------------------------------------------------
Ran 6 tests in 0.215s

FAILED (errors=2)
```

**Comment by kkaarreell** [comment]
@stefanberger Hi, is this something you would be easily fix? I am wondering how one can easily generate updated hashes and signatures for the IMA test.
