### ISSUE TITLE
keylime_tenant tracebacks when verifier config is not available

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1262]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: C9S
 * Processor architecture: x86_64
 * TPM Manufacturer: virtual swtpm
 * Keylime version: current upstream [4720332](https://github.com/keylime/keylime/commit/4720332ca9a9ad33e2b1ebea4e6baf89e1b8fcaa)

# Description 
keylime_tenant tracebacks when verifier configuration is not available. This is a regression introduced recently most likely by this MR
https://github.com/keylime/keylime/pull/1255/files

## Expected behavior vs. actual behavior 
keylime_tenant should not require config files of the verifier, registrar or agent

## Steps to reproduce problem
Run keylime_tenant cmf on a system with other config files deleted. E.g. when running all services on localhost
```
# rm -rf /etc/keylime/{agent,registrar,verifier}*
# keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --verify --allowlist allowlist.txt --exclude excludelist.txt --include payload-module --cert default -c add
```

# Relevant logs
```
Reading configuration from ['/etc/keylime/logging.conf']
Config file not found in ['/etc/keylime/verifier.conf', '/usr/etc/keylime/verifier.conf']. Please see /usr/lib/python3.9/site-packages/keylime/config.py for more details.
Traceback (most recent call last):
  File "/usr/bin/keylime_tenant", line 33, in <module>
    sys.exit(load_entry_point('keylime==6.5.2', 'console_scripts', 'keylime_tenant')())
  File "/usr/bin/keylime_tenant", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/keylime/cmd/tenant.py", line 3, in <module>
    from keylime import keylime_logging, tenant
  File "/usr/lib/python3.9/site-packages/keylime/tenant.py", line 20, in <module>
    from keylime.cli import options, policies
  File "/usr/lib/python3.9/site-packages/keylime/cli/policies.py", line 4, in <module>
    from keylime import config, keylime_logging, measured_boot
  File "/usr/lib/python3.9/site-packages/keylime/measured_boot.py", line 8, in <module>
    from keylime.elchecking import tests
  File "/usr/lib/python3.9/site-packages/keylime/elchecking/__init__.py", line 9, in <module>
    from . import example
  File "/usr/lib/python3.9/site-packages/keylime/elchecking/example.py", line 4, in <module>
    from . import policies, tests
  File "/usr/lib/python3.9/site-packages/keylime/elchecking/policies.py", line 106, in <module>
    imports = config.getlist("verifier", "measured_boot_imports")
  File "/usr/lib/python3.9/site-packages/keylime/config.py", line 236, in getlist
    read = get_config(component).get(section, option)
  File "/usr/lib64/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'verifier'
```

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
@kkaarreell thank you for finding this. It has to do with that loading of the `measured_boot` module causes the `elchecking` code to import the configured modules because it is part of `__init__.py`. This is due to type hints, maybe we find a better way to load it.
