### ISSUE TITLE
failing tests because of the missing configuration files in testing

### ISSUE THREAD

**Issue by mcepl** [keylime/keylime#1264]
When trying enabling tests while building packages for openSUSE, I have hit this configuration problem:

```
[   26s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/keylime-6.5.2-0.x86_64/usr/lib/python3.9/site-packages
[   26s] + PYTHONDONTWRITEBYTECODE=1
[   26s] + python3.9 -m unittest discover -s keylime -p '*_test.py' -v
[   27s] elchecking (unittest.loader._FailedTest) ... ERROR
[   27s] ima.ima_test (unittest.loader._FailedTest) ... ERROR
[   27s] test_get_tpm2b_public_name (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_get_tpm2b_public_object_attributes (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_object_attributes_description (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_pubkey_from_tpm2b_public_ec (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_pubkey_from_tpm2b_public_ec_without_encryption (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_pubkey_from_tpm2b_public_rsa (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_pubkey_from_tpm2b_public_rsa_without_encryption (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_tpm2b_public_from_pubkey_ec (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] test_tpm2b_public_from_pubkey_rsa (tpm.tpm2_objects_test.TestTpm2Objects) ... ok
[   27s] user_utils_test (unittest.loader._FailedTest) ... ERROR
[   27s] 
[   27s] ======================================================================
[   27s] ERROR: elchecking (unittest.loader._FailedTest)
[   27s] ----------------------------------------------------------------------
[   27s] ImportError: Failed to import test module: elchecking
[   27s] Traceback (most recent call last):
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 470, in _find_test_path
[   27s]     package = self._get_module_from_name(name)
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 377, in _get_module_from_name
[   27s]     __import__(name)
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/elchecking/__init__.py", line 9, in <module>
[   27s]     from . import example
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/elchecking/example.py", line 4, in <module>
[   27s]     from . import policies, tests
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/elchecking/policies.py", line 106, in <module>
[   27s]     imports = config.getlist("verifier", "measured_boot_imports")
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config.py", line 248, in getlist
[   27s]     read = get_config(component).get(section, option)
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config.py", line 214, in get_config
[   27s]     _config[component].read_string(file.read_text("utf-8"))
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1266, in read_text
[   27s]     with self.open(mode='r', encoding=encoding, errors=errors) as f:
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1252, in open
[   27s]     return io.open(self, mode, buffering, encoding, errors, newline,
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1120, in _opener
[   27s]     return self._accessor.open(self, flags, mode)
[   27s] FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config/verifier.conf'
[   27s] 
[   27s] 
[   27s] ======================================================================
[   27s] ERROR: ima.ima_test (unittest.loader._FailedTest)
[   27s] ----------------------------------------------------------------------
[   27s] ImportError: Failed to import test module: ima.ima_test
[   27s] Traceback (most recent call last):
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 436, in _find_test_path
[   27s]     module = self._get_module_from_name(name)
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 377, in _get_module_from_name
[   27s]     __import__(name)
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/ima/ima_test.py", line 4, in <module>
[   27s]     from keylime.ima import ima
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/ima/ima.py", line 12, in <module>
[   27s]     from keylime import config, keylime_logging, signing
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/keylime_logging.py", line 15, in <module>
[   27s]     logging_config.fileConfig(config.get_config("logging"))
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config.py", line 214, in get_config
[   27s]     _config[component].read_string(file.read_text("utf-8"))
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1266, in read_text
[   27s]     with self.open(mode='r', encoding=encoding, errors=errors) as f:
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1252, in open
[   27s]     return io.open(self, mode, buffering, encoding, errors, newline,
[   27s]   File "/usr/lib64/python3.9/pathlib.py", line 1120, in _opener
[   27s]     return self._accessor.open(self, flags, mode)
[   27s] FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config/logging.conf'
[   27s] 
[   27s] 
[   27s] ======================================================================
[   27s] ERROR: user_utils_test (unittest.loader._FailedTest)
[   27s] ----------------------------------------------------------------------
[   27s] ImportError: Failed to import test module: user_utils_test
[   27s] Traceback (most recent call last):
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 436, in _find_test_path
[   27s]     module = self._get_module_from_name(name)
[   27s]   File "/usr/lib64/python3.9/unittest/loader.py", line 377, in _get_module_from_name
[   27s]     __import__(name)
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/user_utils_test.py", line 3, in <module>
[   27s]     from keylime import user_utils
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/user_utils.py", line 5, in <module>
[   27s]     from keylime import keylime_logging
[   27s]   File "/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/keylime_logging.py", line 15, in <module>
[   27s]     logging_config.fileConfig(config.get_config("logging"))
[   27s]   File "/usr/lib64/python3.9/logging/config.py", line 71, in fileConfig
[   27s]     formatters = _create_formatters(cp)
[   27s]   File "/usr/lib64/python3.9/logging/config.py", line 104, in _create_formatters
[   27s]     flist = cp["formatters"]["keys"]
[   27s]   File "/usr/lib64/python3.9/configparser.py", line 963, in __getitem__
[   27s]     raise KeyError(key)
[   27s] KeyError: 'formatters'
[   27s] 
[   27s] 
[   27s] ----------------------------------------------------------------------
[   27s] Ran 12 tests in 0.012s
[   27s] 
[   27s] FAILED (errors=3)
[   27s] Config file not found in ['/etc/keylime/verifier.conf', '/usr/etc/keylime/verifier.conf']. Please see /home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config.py for more details.
[   27s] Falling back on package provided configuration
[   27s] Config file not found in ['/etc/keylime/logging.conf', '/usr/etc/keylime/logging.conf']. Please see /home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config.py for more details.
[   27s] Falling back on package provided configuration
```

# Environment
 * OS / version: openSUSE/Tumbleweed (latest development version of openSUSE)
 * Processor architecture: any (this is x86_64, but I don’t think it matters)
 * TPM Manufacturer: ???
 * Keylime version: 6.5.2 from the tarball

# Description 
Run the test suite with:

```sh
python3 -m unittest discover -s keylime -p '*_test.py' -v
```

## Expected behavior vs. actual behavior 

Expected: the test suite passes

Actual: it fails with the above shown problems (complete build log with all details has been attached below).

Concernig `*.conf` files in `/etc/` directory, would it be possible to set the location of the configuration file somewhere else (e.g., `if 'KEYLIME_CONF’ in os.environ:` which would point to the location of the configuration file)? Our build system (as many others for obvious reasons) doesn’t allow running builds under the root user, so it is not possible to write to the real `/etc`.

Also, there is no `/home/abuild/rpmbuild/BUILD/keylime-v6.5.2/keylime/config/` directory at all (there is only `config.py` in the `keylime/` directory).

# Relevant logs
[Complete build log](https://github.com/keylime/keylime/files/10315932/_log.txt)

**Comment by THS-on** [comment]
You can set the config for each service: `KEYLIME_AGENT_CONFIG`, `KEYLIME_VERIFIER_CONFIG`, `KEYLIME_TENANT_CONFIG`, `KEYLIME_REGISTRAR_CONFIG`,  `KEYLIME_CA_CONFIG` and `KEYLIME_LOGGING_CONFIG`

Reference: https://github.com/keylime/keylime/blob/4720332ca9a9ad33e2b1ebea4e6baf89e1b8fcaa/keylime/config.py#L100-L111

For generating the config files the easiest way is to run the conversion script like so:
```
./scripts/convert_config.py  --templates ./scripts/templates --input keylime.conf --out PATH/TO/SAVE/CONFIG
```

Note that we are currently trying to simplify this in #1260 and that some of the tests require a software TPM (see: https://github.com/keylime/keylime/blob/master/.ci/test_wrapper.sh).

**Comment by aplanas** [comment]
Yes. I think that this can be closed. @mcepl I will take care of it. Thanks!
