### ISSUE TITLE
Registrar start  fails when is set up with IPv6 address

### ISSUE THREAD

**Issue by Koncpa** [keylime/keylime#1316]
# Environment
 * OS / version: Fedora-37
 * Processor architecture: x86_64
 * TPM Manufacturer: SWTP also QEMU TPM
 * Keylime version: Upstream latest

# Description 
When I run registrar with IPv6 setup, the start of registrar fail.

## Expected behavior vs. actual behavior 
Registrar succesfully starts with IPv6 setup vs Registrar start fails with IPv6 setup.

## Steps to reproduce problem
1. Setup in registrar.conf ip in IPv6 format ( like 2001:db8:6000:: or ::1 as localhost IPv6 )
2. Start registrar

# Relevant logs

For QEMU TPM with distributed version of package ( keylime-registrar-6.5.0-1.el9.x86_64 )
2023-02-15 13:20:46.165 - keylime.keylime_db - INFO - database_url is set as 'sqlite' keyword, using default values to establish database connection
2023-02-15 13:20:46.167 - alembic.env - INFO - Migrating database registrar
Traceback (most recent call last):
  File "/usr/bin/keylime_registrar", line 33, in <module>
    sys.exit(load_entry_point('keylime==6.5.2', 'console_scripts', 'keylime_registrar')())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/registrar.py", line 12, in main
    registrar_common.start(
  File "/usr/lib/python3.9/site-packages/keylime/registrar_common.py", line 490, in start
    protected_server = RegistrarServer((host, tlsport), ProtectedHandler)
  File "/usr/lib/python3.9/site-packages/keylime/registrar_common.py", line 467, in __init__
    http.server.HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/usr/lib64/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.9/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -9] Address family for hostname not supported

Keylime upstream version of package

Feb 20 06:42:31 keylime_registrar[5039]: Traceback (most recent call last):
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/local/bin/keylime_registrar", line 33, in <module>
Feb 20 06:42:31 keylime_registrar[5039]:     sys.exit(load_entry_point('keylime==6.6.0', 'console_scripts', 'keylime_registrar')())
Feb 20 06:42:31 keylime_registrar[5039]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/cmd/registrar.py", line 14, in main
Feb 20 06:42:31 keylime_registrar[5039]:     registrar_common.start(
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/registrar_common.py", line 516, in start
Feb 20 06:42:31 keylime_registrar[5039]:     protected_server = RegistrarServer((host, tlsport), ProtectedHandler)
Feb 20 06:42:31 keylime_registrar[5039]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/registrar_common.py", line 493, in __init__
Feb 20 06:42:31 keylime_registrar[5039]:     http.server.HTTPServer.__init__(self, server_address, RequestHandlerClass)
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/lib64/python3.11/socketserver.py", line 456, in __init__
Feb 20 06:42:31 keylime_registrar[5039]:     self.server_bind()
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/lib64/python3.11/http/server.py", line 136, in server_bind
Feb 20 06:42:31 keylime_registrar[5039]:     socketserver.TCPServer.server_bind(self)
Feb 20 06:42:31 keylime_registrar[5039]:   File "/usr/lib64/python3.11/socketserver.py", line 472, in server_bind
Feb 20 06:42:31 keylime_registrar[5039]:     self.socket.bind(self.server_address)
Feb 20 06:42:31 keylime_registrar[5039]: socket.gaierror: [Errno -9] Address family for hostname not supported

**Comment by Koncpa** [comment]
Duplicate, sorry.
