### ISSUE TITLE
Keylime tenant cannot parse IPv6 url, when try to add agent 

### ISSUE THREAD

**Issue by Koncpa** [keylime/keylime#1328]
# Environment
 * OS / version: f37
 * Processor architecture:  x86_64
 * TPM Manufacturer: SWTPM
 * Keylime version: Upstream for rust agent and other keylime components

# Description 
When I tried to run keylime in dual stack (IPv4 for v registrar and IPv6 for other components) the adding of keylime_agent via tenant CLI has failed. IPv4 was setup due to actual fail in keylime registrar. [IPv6 ISSUE](https://github.com/keylime/keylime/issues/1315)

## Expected behavior vs. actual behavior 
Adding keylime_agent will be succesfull. vs. Adding keylime_agent has failed. 

## Steps to reproduce problem
1.Setup IPv6 localhost for keylime_agent, keylime_verifier ( for example IPv6 localhost)
2.Run all keylime components
3.Add keylime_agent via keylime_tenant

# Relevant logs

:: [ 05:45:02 ] :: [  BEGIN   ] :: Running 'keylime_tenant -v ::1 -t ::1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --runtime-policy policy.json -f /etc/hostname -c add'
INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2023-03-02 05:45:02.738 - keylime.keylime.cmd_exec - DEBUG - Executing command "tpm2_startup --version"
2023-03-02 05:45:02.745 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.4
2023-03-02 05:45:02.747 - keylime.tenant - WARNING - The configuration upgrade templates path /usr/share/keylime/templates does not exist
2023-03-02 05:45:02.748 - keylime.config - INFO - Reading configuration from ['/etc/keylime/tenant.conf']
2023-03-02 05:45:02.748 - keylime.tenant - INFO - Setting up client TLS...
2023-03-02 05:45:02.748 - keylime.tenant - INFO - Using default client_cert option for tenant
2023-03-02 05:45:02.748 - keylime.tenant - INFO - Using default client_key option for tenant
2023-03-02 05:45:02.749 - keylime.tenant - INFO - No value provided in client_key_password option for tenant, assuming the key is unencrypted
2023-03-02 05:45:02.771 - keylime.tenant - INFO - TLS is enabled.
2023-03-02 05:45:02.773 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 127.0.0.1:8891
2023-03-02 05:45:02.804 - urllib3.connectionpool - DEBUG - https://127.0.0.1:8891 "GET /v2.1/agents/d432fbb3-d2f1-4a97-9ef7-75bd81c00000 HTTP/1.1" 200 None
2023-03-02 05:45:02.827 - keylime.tenant - ERROR - Failed to parse: https://::1:9002/version
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
                                                      ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://::1:9002/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/cmd/tenant.py", line 10, in main
    tenant.main()
  File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/tenant.py", line 1637, in main
    mytenant.init_add(vars(args))
  File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/tenant.py", line 237, in init_add
    res = get_version.get("/version")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/keylime-6.6.0-py3.11.egg/keylime/requests_client.py", line 47, in get
    return self.session.get(self.base_url + url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://::1:9002/version

**Comment by stefanberger** [comment]
You may have to use `[::1]` instead of `::1` :  

```
$ python
Python 3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib3.util import parse_url
>>> parse_url("https://::1:8080/foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/urllib3/util/url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://::1:8080/foo
>>> parse_url("https://[::1]:8080/foo")
Url(scheme='https', auth=None, host='[::1]', port=8080, path='/foo', query=None, fragment=None)
```

**Comment by Koncpa** [comment]
After manual testing, I can confirm that this approach works. I'm just not sure if it would be better for the user environment to implement IPv6 without square brackets. And it would also be good to standardize the IPv6 address format. In the verifier configuration file, IPv6 is set without square brackets but for other components we use the format with square brackets.

**Comment by stefanberger** [comment]
Relative to my testing that may not cover all the cases:

The verifier's server IP and port can be specified with simple '::1'. I could specify the registrar_ip in the verifier.conf with with '::1' and it worked but I am not sure whether it actually initiated a connection to the registrar (likely not).

The registrar's server IP address could also be specified using '::1' in its config file.

The tenant tool (python) does require square brackets "[::1]" on the command line (for `-t` and `-r` options for example).

The agent (Rust) seems to require the "[::1]" notation for its server IP address.

Python: For python programs it seems that server IP addresses (= local listening IP addresses) can be specified by '::1' and anything that goes into a URL requires "[::1]".

Rust: For Rust the server IP addresses the only choice seems to be square brackets. I think there it is related to how the HttpServer (library) handles the IP addresses. @lkatalin @ansasaki 

Command lines: For a user to specify the non-bracket version on the command line would be better and we can add the brackets.
Config files: Same thing -- no brackets ?

**Comment by Koncpa** [comment]
I agree. Thanks for the summary, I definitely know that brackets are sometimes necessary for IPv6 processing, but we should definitely try to implement brackets in keylime code to increase usability and clarity for keylime users.

**Comment by stefanberger** [comment]
@Koncpa I updated the PR with another patch to add brackets onto IPv6 IP addresses when they are going into a URL.

**Comment by stefanberger** [comment]
Has this issue been resolved now?

**Comment by maugustosilva** [comment]
@Koncpa Will close this issue for now, fell free to open if needed.

**Comment by Koncpa** [comment]
Hi guys, I can confirm that IPv6 should work for now, here is [PR](https://github.com/RedHat-SP-Security/keylime-tests/pull/380) for our test suite. I will just disscuss to possibility to paste IPv6 into rust agent.conf without brackets, but from python side is OK.
