### ISSUE TITLE
Missing python module psycopg2 for Docker and postgresql

### ISSUE THREAD

**Issue by bencorrado** [keylime/keylime#1672]
# Environment
 * OS / version: Docker [sha tag](https://quay.io/repository/keylime/keylime_registrar/manifest/sha256:c5affc299e94bc2e7da0c4e1d7ae4a52220db6a6e787c8fe3b864e6514f789cb)
 * Processor architecture: x86_64 
 * TPM Manufacturer: 
 * Keylime version: 7.11.0

# Description 

## Expected behavior vs. actual behavior 
When specifying a Postgresql database the docker containers should boot and host keylime registrar and verifier

## Steps to reproduce problem
1. Follow the instructions to launch the [Docker containers](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/security_hardening/assembly_ensuring-system-integrity-with-keylime_security-hardening#configuring-keylime-verifier-as-a-container_assembly_ensuring-system-integrity-with-keylime)
2. Setup a new postgresql database
3. Use environmental variables: `KEYLIME_REGISTRAR_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"` and `KEYLIME_VERIFIER_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"`
4. Watch the logs, particularly for registrar.  You will see a crash from Python3 missing `psycopg2.py` and module `psycopg2`

# Relevant logs

```
keylime-docker-compose-postgres-1           | 2024-10-24 23:04:20.797 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
keylime-docker-compose-postgres-1           | 2024-10-24 23:04:20.797 UTC [1] LOG:  listening on IPv6 address "::", port 5432
keylime-docker-compose-postgres-1           | 2024-10-24 23:04:20.799 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
keylime-docker-compose-postgres-1           | 2024-10-24 23:04:20.803 UTC [66] LOG:  database system was shut down at 2024-10-24 23:04:20 UTC
keylime-docker-compose-postgres-1           | 2024-10-24 23:04:20.806 UTC [1] LOG:  database system is ready to accept connections
keylime-docker-compose-keylime-verifier-1   | INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
keylime-docker-compose-keylime-verifier-1   | 2024-10-24 23:04:31.590 - keylime.config - INFO - Reading configuration from ['/etc/keylime/verifier.conf']
keylime-docker-compose-keylime-verifier-1   | 2024-10-24 23:04:31.591 - keylime.failure - INFO - Severity configuration set
keylime-docker-compose-keylime-verifier-1   | 2024-10-24 23:04:31.591 - keylime.config - INFO - option "database_url" for component verifier.conf was overriden by environment variable KEYLIME_VERIFIER_DATABASE_URL
keylime-docker-compose-keylime-verifier-1   | 2024-10-24 23:04:31.591 - keylime.keylime_db - INFO - database_url is set, using it to establish database connection
keylime-docker-compose-keylime-verifier-1   | Traceback (most recent call last):
keylime-docker-compose-keylime-verifier-1   |   File "/usr/local/bin/keylime_verifier", line 5, in <module>
keylime-docker-compose-keylime-verifier-1   |     from keylime.cmd.verifier import main
keylime-docker-compose-keylime-verifier-1   |   File "/usr/local/lib/python3.11/site-packages/keylime/cmd/verifier.py", line 1, in <module>
keylime-docker-compose-keylime-verifier-1   |     from keylime import cloud_verifier_tornado, config, keylime_logging
keylime-docker-compose-keylime-verifier-1   |   File "/usr/local/lib/python3.11/site-packages/keylime/cloud_verifier_tornado.py", line 49, in <module>
keylime-docker-compose-keylime-verifier-1   |     engine = DBEngineManager().make_engine("cloud_verifier")
keylime-docker-compose-keylime-verifier-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
keylime-docker-compose-keylime-verifier-1   |   File "/usr/local/lib/python3.11/site-packages/keylime/db/keylime_db.py", line 91, in make_engine
keylime-docker-compose-keylime-verifier-1   |     engine = create_engine(url, **engine_args)
keylime-docker-compose-keylime-verifier-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
keylime-docker-compose-keylime-verifier-1   |   File "<string>", line 2, in create_engine
keylime-docker-compose-keylime-verifier-1   |   File "/usr/lib64/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
keylime-docker-compose-keylime-verifier-1   |     return fn(*args, **kwargs)
keylime-docker-compose-keylime-verifier-1   |            ^^^^^^^^^^^^^^^^^^^
keylime-docker-compose-keylime-verifier-1   |   File "/usr/lib64/python3.11/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
keylime-docker-compose-keylime-verifier-1   |     dbapi = dialect_cls.dbapi(**dbapi_args)
keylime-docker-compose-keylime-verifier-1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
keylime-docker-compose-keylime-verifier-1   |   File "/usr/lib64/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 811, in dbapi
keylime-docker-compose-keylime-verifier-1   |     import psycopg2
keylime-docker-compose-keylime-verifier-1   | ModuleNotFoundError: No module named 'psycopg2'
container for service "keylime-verifier" is unhealthy
```

**Comment by bencorrado** [comment]
> Thank you for reporting your first issue. If the issue relates to a change you intend to work on, please ask that someone assign it to you.

Feel free to assign this to me, it is fixed by #1673
