### ISSUE TITLE
Issues with legacy tools

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#172]
Tools version

`tpm2-tools-3.2.0-3.fc30.x86_64`

Running the agent shows:

```
neptune :: ~ » keylime_agent                                    
Using config file /etc/keylime.conf
2019-09-27 14:03:41.093 - keylime.tpm2 - INFO - Using legacy version of tpm2-tools
2019-09-27 14:03:41.168 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2019-09-27 14:03:41.311 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2019-09-27 14:03:41.312 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81010007
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/cloud_agent.py", line 492, in main
    (ek,ekcert,aik,ek_tpm,aik_name) = tpm.tpm_init(self_activate=False,config_pw=config.get('cloud_agent','tpm_ownerpassword')) # this tells initialize not to self activate the AIK
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm2.py", line 819, in tpm_init
    self.__get_pub_ek()
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/tpm2.py", line 468, in __get_pub_ek
    raise Exception("tpm2_readpublic failed with code "+str(code)+": "+str(output))
Exception: tpm2_readpublic failed with code 1: [b"tpm2_readpublic: invalid option -- 'H'\n"]
```

```
tpm2_readpublic -H 0x81010007 -o akpub.pem -f pem

tpm2_readpublic: invalid option -- 'H'
```

Using the 4.x tool code:

```
tpm2_readpublic -c 0x81010007 -o akpub.pem -f pem

name: 000b600c6e954f7a31eb92a8608e052c14b085105b6d8be0643a2832d009c216a46c
qualified name: 000bc135ce5aa2eb608a6d297bba2d9329771c23986a866fbf881baebe7852f19e89
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: c1df9098cbc8fe453bed2832e0e7cfe36996d40731ac4e715be10de75e3aaae9cc6c148222af1bab574af18549d3c49cacdcb9125253b2e38c40c5c605a1f8f3c0b0a5a0ecd8a67502839917dd72fe78f0a6cb26cd8f9e835062f561bfaa47e507a0dcf3a82851f0b344b5085f5ea69308c42bbdf4d17e1b31c3905412e611bbe8bb51c1fbce1adc802ddfdd7339641ddde62e14d24660e1f2f336a14403d313931e75ae9865050c2775af4f79e4184830e831306cbcd1da9bf30aca23450ec923d8a3f274d34f37120239f0759d2096446cac4c37842ed2a5267af1ae8da452aa26d5831103dc82e8acfce236f2f0028212f5ea808d56f38c71a72a205130a9
authorization policy: 837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
neptune :: ~ » cat akpub.pem      
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwd+QmMvI/kU77Sgy4OfP
42mW1AcxrE5xW+EN5146qunMbBSCIq8bq1dK8YVJ08ScrNy5ElJTsuOMQMXGBaH4
88CwpaDs2KZ1AoOZF91y/njwpssmzY+eg1Bi9WG/qkflB6Dc86goUfCzRLUIX16m
kwjEK7300X4bMcOQVBLmEbvou1HB+84a3IAt391zOWQd3eYuFNJGYOHy8zahRAPT
E5Meda6YZQUMJ3WvT3nkGEgw6DEwbLzR2pvzCsojRQ7JI9ij8nTTTzcSAjnwdZ0g
lkRsrEw3hC7SpSZ68a6NpFKqJtWDEQPcguis/OI28vACghL16oCNVvOMcacqIFEw
qQIDAQAB
-----END PUBLIC KEY-----
```

Summary:

legacy_tools is True 

```
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import distutils.spawn
>>> from keylime import common
Using config file /etc/keylime.conf
>>> env = os.environ.copy()
>>> env['PATH']=env['PATH']+":%s"%common.TPM_TOOLS_PATH
>>> legacy_tools = distutils.spawn.find_executable("tpm2_takeownership", env['PATH']) is not None
>>> print("Using %s version of tpm2-tools"%("legacy" if legacy_tools else "modern"))
Using legacy version of tpm2-tools
>>> 
```

https://github.com/keylime/keylime/blob/b32955ae1c0e5022e67144f6cc210d04c956af4b/keylime/tpm2.py#L459-L462

The above code results in the `-H` flag being used. 

The `-H` flag is not supported in `tpm2-tools-3.2.0-3.fc30.x86_64`

Tagging @jetwhiz

**Comment by lukehinds** [comment]
Hold up, there is something really messed up on my machine:

```
dnf install tpm2-tools                           
Package tpm2-tools-3.2.0-3.fc30.x86_64 is already installed.
```

```
tpm2_readpublic --version
tool="tpm2_readpublic" version="3.0.2-736-ga22ca8f" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
```

On a second machine

```
dnf install tpm2-tools
Package tpm2-tools-3.2.0-3.fc30.x86_64 is already installed.
```

```
tpm2_readpublic --version
tool="tpm2_readpublic" version="3.2.0" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
````

**Comment by lukehinds** [comment]
I will close this as invalid (once I get to the bottom of it), but I think this leads into wether we might consider using the `--version` flag instead of an execution path being present.

**Comment by lukehinds** [comment]
invalid
