### ISSUE TITLE
Unexpected Auth tag

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#199]
I have seen this on a couple of different machines now (Raspberry Pi and Intel Nuk).

I will add more debug information as a followup.

root@raspberrypi:~/keylime# keylime_agent 
Using config file /etc/keylime.conf
2019-10-22 13:46:03.250 - keylime.tpm2 - INFO - Using legacy version of tpm2-tools
WARN: More data to be queried: capability: 0x6, property: 0x100

```
2019-10-22 13:46:03.458 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2019-10-22 13:46:03.710 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2019-10-22 13:46:03.711 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81010007
2019-10-22 13:46:04.312 - keylime.tpm2 - INFO - Flushing old ak handle: 0x81010008
2019-10-22 13:46:05.598 - keylime.cloudagent - INFO - Agent UUID: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-10-22 13:46:05.718 - keylime.registrar_client - INFO - Agent registration requested for D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-10-22 13:46:06.151 - keylime.tpm2 - INFO - AIK activated.
2019-10-22 13:46:06.159 - keylime.registrar_client - ERROR - Error: unexpected http response code from Registrar Server: 400
2019-10-22 13:46:06.160 - keylime.registrar_client - ERROR - Response code 400: Error: Auth tag c8fb3e8626608838413616bbe52fe2fcf9fc1212f54042bc54ad7baf996aaf236135d37861ddd8b662a565604b09344e does not match expected value 6f8d0b8a7521dd3187e8d7a3d4bdea76050071c5cd872722b00cc1f297e86947e6cf717c55c62c8794f70317661d73bd
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/local/lib/python3.7/dist-packages/keylime-1.2-py3.7.egg/keylime/cloud_agent.py", line 549, in main
    raise Exception("Registration failed on activate")
Exception: Registration failed on activate
```

**Comment by lukehinds** [comment]
I have not seen this for a while so closing.
