### ISSUE TITLE
tpm2-tools 3.2.0 nvread fails with Infineon SLB9665VQ2.0 TPM v2.0

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#206]
Keylime agent registration works with 3.2.0 using  an emulator, but fails with the Infineon SLB9665VQ2.0 TPM v2.0

Debug output:

```
Using config file /etc/keylime.conf
2019-11-11 14:36:23.860 - keylime.tpm2 - INFO - Using legacy version of tpm2-tools
('cmd: ', 'tpm2_startup -c')
('cmd: ', 'tpm2_getcap -c algorithms')
('cmd: ', 'mount')
('cmd: ', 'tpm2_getcap -c properties-fixed')
WARN: More data to be queried: capability: 0x6, property: 0x100

2019-11-11 14:36:23.950 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
('cmd: ', 'tpm2_takeownership -c')
('cmd: ', 'tpm2_takeownership -o keylime -e keylime')
2019-11-11 14:36:24.090 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2019-11-11 14:36:24.091 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81010007
('cmd: ', 'tpm2_getcap -c handles-persistent')
('cmd: ', 'tpm2_getpubek -H 0x81010007 -g rsa -f /tmp/tmpGCMRtx -P U1RKfzVUVpVGfQsxldtb -o keylime -e keylime')
('cmd: ', 'tpm2_readpublic -H 0x81010007 -o /tmp/tmpdU12rp -f pem')
('cmd: ', 'tpm2_nvlist')
('cmd: ', 'tpm2_nvread -x 0x1c00002 -s 1177 -f /tmp/tmppRPCNb')
ERROR: Failed to read NVRAM area at index 0x1c00002 (29360130). Error:0x9a2
ERROR: Unable to run tpm2_nvread
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/cloud_agent.py", line 482, in main
    (ek,ekcert,aik,ek_tpm,aik_name) = tpm.tpm_init(self_activate=False,config_pw=config.get('cloud_agent','tpm_ownerpassword')) # this tells initialize not to self activate the AIK
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tpm2.py", line 797, in tpm_init
    ekcert = self.read_ekcert_nvram()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tpm2.py", line 1066, in read_ekcert_nvram
    raise Exception("tpm2_nvread for ekcert failed with code "+str(code)+": "+str(output))
Exception: tpm2_nvread for ekcert failed with code 1: []

```

**Comment by lukehinds** [comment]
Note, the site-packages is python 2.7, its the same for 3.7 & 3.8 (I was debugging to see if it was also present on the old 2.7 branch)

**Comment by lukehinds** [comment]
ok, this is interesting - the same command also fails when using the emulator and 3.2, but somehow its not trapped as an error, so the agent starts normally. You can only see the error when you print out `retout`

```
Using config file /etc/keylime.conf
command:  tpm2_startup --version
2019-11-11 15:04:50.083 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 3.2.0
command:  tpm2_startup -c
command:  tpm2_getcap -c algorithms
command:  mount
command:  tpm2_getcap -c properties-fixed
2019-11-11 15:04:50.640 - keylime.tpm - WARNING - INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
2019-11-11 15:04:50.640 - keylime.tpm - WARNING - INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
2019-11-11 15:04:50.640 - keylime.tpm - WARNING - INSECURE: Only use Keylime in this mode for testing or debugging purposes.
2019-11-11 15:04:50.640 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
command:  tpm2_takeownership -c
command:  tpm2_takeownership -o keylime -e keylime
2019-11-11 15:04:50.697 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2019-11-11 15:04:50.697 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81010007
command:  tpm2_getcap -c handles-persistent
command:  tpm2_getpubek -H 0x81010007 -g rsa -f /tmp/tmphqt12g9a -P sJgyOUPn18DMnAAnTsLB -o keylime -e keylime
command:  tpm2_readpublic -H 0x81010007 -o /tmp/tmp4sh183_z -f pem
command:  tpm2_nvlist
2019-11-11 15:04:50.846 - keylime.tpm2 - WARNING - No EK certificate found in TPM NVRAM
2019-11-11 15:04:50.846 - keylime.tpm2 - INFO - Flushing old ak handle: 0x81010008
command:  tpm2_getcap -c handles-persistent
command:  tpm2_getpubak -E 0x81010007 -k 0x81010008 -g rsa -D sha256 -s rsassa -f /tmp/tmp3rmp83wy -e keylime -P 1DkHAiMbF2F67rTVmN2a -o keylime
command:  tpm2_readpublic -H 0x81010008 -o /tmp/tmpmrr9vq72 -f pem
command:  tpm2_getrandom -o /tmp/tmpjrae2r1k 32
command:  tpm2_getcap -c properties-fixed
2019-11-11 15:04:51.119 - keylime.cloudagent - INFO - Agent UUID: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-11-11 15:04:51.179 - keylime.registrar_client - INFO - Agent registration requested for D432FBB3-D2F1-4A97-9EF7-75BD81C00000
command:  mount
command:  tpm2_activatecredential -H 0x81010008 -k 0x81010007 -f /tmp/tmp_m0q01db -o /var/lib/keylime/secure/tmpupaw31tg -P 1DkHAiMbF2F67rTVmN2a -e keylime
2019-11-11 15:04:51.188 - keylime.tpm2 - INFO - AIK activated.
2019-11-11 15:04:51.198 - keylime.registrar_client - INFO - Registration activated for agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000.
command:  mount
command:  tpm2_nvread -x 0x1500018 -a 0x40000001 -s 32 -P keylime
command output (retout):  ['ERROR: Failed to read NVRAM public area at index 0x1500018 (22020120). Error:0x18b\n', 'ERROR: Unable to run tpm2_nvread\n']
2019-11-11 15:04:51.243 - keylime.cloudagent - INFO - Starting Cloud Agent on port 9002 use <Ctrl-C> to stop
2019-11-11 15:04:51.243 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 127.0.0.1:8992
```

**Comment by lukehinds** [comment]
@jetwhiz what do you make of this, is `tpm2_nvread -x 0x1500018 -a 0x40000001 -s 32 -P keylime` important ?

**Comment by lukehinds** [comment]
found the issue, its failing to match this line I believe:

https://github.com/keylime/keylime/blob/e2bfff7b1ebcaef9b3dec7d840f18133684e84bf/keylime/tpm2.py#L1203

**Comment by lukehinds** [comment]
gah! I know what it is, its because I removed `stderr=subprocess.STDOUT` as per the email thread we had with @atothRedHat

**Comment by lukehinds** [comment]
ok, fixed...pr coming

**Comment by jetwhiz** [comment]
@lukehinds Is this issue fixed now?  I think https://github.com/keylime/keylime/pull/207 was designed to take care of this issue

**Comment by lukehinds** [comment]
Yep, we can close thanks @jetwhiz
