### ISSUE TITLE
Revocation notices failing to parse json-dumps

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#220]
Revocation events are failing parsing into json.dumps:

https://github.com/keylime/keylime/blob/200099fe107c62f2d6b9697d625415a506366fed/keylime/revocation_notifier.py#L79-L86

This error is hidden within the confines of the zmq sock.send call.

If you extract the dump of `tosend` and set it a few lines before, aka:

`dump_test = json.dumps(tosend)`

You will then see the failure:

```
2019-12-10 10:55:39.334 - keylime.ima - WARNING - File not found in whitelist: /root/zmtpdump/configure
2019-12-10 10:55:39.334 - keylime.ima - WARNING - File not found in whitelist: /usr/sbin/tcpdump
2019-12-10 10:55:39.334 - keylime.ima - ERROR - IMA ERRORS: template-hash 0 fnf 8 hash 0 good 461
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/revocation_notifier.py", line 82, in worker
    dump_test = json.dumps(tosend)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 382, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 4: invalid start byte

2019-12-10 10:55:39.808 - keylime.cloudverifier - WARNING - agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000 failed, stopping polling
```

The issue is resolved by setting the return signature as base64 (which is was during the python 2 days), I believe it was changed to non base64 to allow unit tests to pass.

**Comment by lukehinds** [comment]
This is still not ready to merge yet.

The code is handling the revocation (which is an x509 pem cerftifate) as an RSA key

Need to include two new functions `x509_import_pubkey` and `x509_verify`
