### ISSUE TITLE
Flag using keylime_ca with openssl

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#261]
If you use keylime_ca with openssl set in keylime.conf the following error appears:

```
2020-04-02 14:22:54.537 - keylime.ca-util - WARNING - using default name for revocation cert /root/test/RevocationNotifier-cert.crt
Please enter the password to decrypt your keystore: 
2020-04-02 14:22:56.401 - keylime.ca-util - INFO - Loading existing crl: /root/test/cacrl.der
2020-04-02 14:22:56.442 - keylime.ca-util - INFO - Hosting CRL on saturn:38080
2020-04-02 14:22:56.444 - keylime.ca-util - INFO - checking CRL for expiration every hour
2020-04-02 14:22:56.446 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 127.0.0.1:8992
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/ca_util.py", line 373, in check_expiration
    retout = cmd_exec.run("openssl crl -inform der -in cacrl.der -text -noout",lock=False)['retout']
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/cmd_exec.py", line 64, in run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s"%(cmd,code,expectedcode,retout,reterr))
Exception: Command: openssl crl -inform der -in cacrl.der -text -noout returned 1, expected 0, output [], stderr [b'unable to load CRL\n', b'140502363866944:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:\n']
```

We should instead pre-validate the set up and warn the user to use cfssl instead (I just burnt up a few hours worried I might have broken the crypto in a previous pull request).

**Comment by nabilschear** [comment]
is this related to lazy loading the revocation certificate?  or is it just poor error handling when loading it.

**Comment by maugustosilva** [comment]
@lukehinds here is the result of the execution with this PR:

```
[root@css-flex14vm1 /]# keylime_ca -c listen -d /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F/
Using config file /etc/keylime.conf
2020-10-29 19:22:38.106 - keylime.ca-util - WARNING - using default name for revocation cert /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F/RevocationNotifier-cert.crt
Please enter the password to decrypt your keystore:
2020-10-29 19:22:41.129 - keylime.ca-util - INFO - Loading existing crl: /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F/cacrl.der
2020-10-29 19:22:41.129 - keylime.ca-util - INFO - Hosting CRL on css-flex14vm1:38080
2020-10-29 19:22:41.130 - keylime.ca-util - INFO - checking CRL for expiration every hour
2020-10-29 19:22:41.132 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 100.64.14.13:8992
2020-10-29 19:23:11.051 - keylime.revocation_notifier - INFO - Lazy loading the revocation certificate from /var/lib/keylime/ca/EB7CD2DF-9A40-5019-830E-D5805FC9276F/RevocationNotifier-cert.crt
2020-10-29 19:23:11.057 - keylime.revocation_notifier - DEBUG - Revocation signature validated for revocation: {'type': 'revocation', 'ip': '100.64.14.15', 'agent_id': 'EB7CD2DF-9A40-5019-830E-D5805FC9276F', 'port': 9002, 'tpm_policy': '{"22": ["0000000000000000000000000000000000000001", "0000000000000000000000000000000000000000000000000000000000000001", "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001", "ffffffffffffffffffffffffffffffffffffffff", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], "15": ["0000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"], "mask": "0x408400"}', 'vtpm_policy': '{"23": ["ffffffffffffffffffffffffffffffffffffffff", "0000000000000000000000000000000000000000"], "15": ["0000000000000000000000000000000000000000"], "mask": "0x808000"}', 'meta_data': '{"cert_serial": 2, "subject": "/C=US/CN=EB7CD2DF-9A40-5019-830E-D5805FC9276F/ST=NY/L=YKT/O=IBM/OU=k5l"}', 'event_time': 'Thu Oct 29 19:23:10 2020'}
2020-10-29 19:23:11.057 - keylime.ca-util - INFO - Revoking certificate: 2
2020-10-29 19:23:11.156 - keylime.ca_impl_openssl - WARNING - CRL creation with openssl is not supported
^C2020-10-29 19:23:52.312 - keylime.ca-util - INFO - TERM Signal received, shutting down...

**Comment by THS-on** [comment]
Should be fixed with #1012.
