### ISSUE TITLE
Unable to run `keylime_tenant -a add` when the verifier and registrar are running on two different machines

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#297]
# Environment
OS / version: Ubuntu / 18.04.4
Processor architecture: Intel Xeon E312xx (Sandy Bridge)
TPM Manufacturer: SWTPM (https://github.com/stefanberger/swtpm)
Keylime version: 1.2
TPM2-Tools version: 4.2

# Description 
Have a setup with three nodes. Node "V" runs the `verifier`, node "R" runs the `registrar` and node "A" runs the `agent`. When attempted to "deploy" the already running agent on node "R" `keylime_tenant` reports and error.

### Expected: 
command `keylime_tenant -c add -t <ip address of A> -v <ip address of V> -u 64124A95-1E10-543E-9560-DC8BF962E60D --cert /var/lib/keylime/ca` should return exit code 0

### Actual: 
command fails with a (quite ugly) python error about ` 'int' object has no attribute 'read'`

## Steps to reproduce problem
1. Deploy verifier, registrar and agent on three different nodes (my personal opinion: the configurations required for this are, at this point, quite messy and undocumented)
2. Attempt to "add" an agent via `keylime_tenant`

# Relevant logs
```
root@css-flex14vm1:~# /usr/local/bin/keylime_tenant -c update -t <ip address of A> -v <ip address of V> -u 6D98723F-153F-5BD6-9097-152011DD3EE8 --cert /var/lib/keylime/ca
Using config file /etc/keylime.conf
2020-05-01 19:06:03.781 - keylime.tenant - INFO - Setting up client TLS in /root/keylime/verifier_ca/
2020-05-01 19:06:03.784 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2020-05-01 19:06:03.784 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
Please enter the password to decrypt your keystore:
2020-05-01 19:06:07.023 - keylime.ca-util - INFO - Creating cert package for 6D98723F-153F-5BD6-9097-152011DD3EE8 in 6D98723F-153F-5BD6-9097-152011DD3EE8-pkg.zip
2020-05-01 19:06:07.117 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2020-05-01 19:06:07.147 - keylime.tenant - INFO - Agent 6D98723F-153F-5BD6-9097-152011DD3EE8 deleted from the CV
2020-05-01 19:06:07.147 - keylime.tenant - DEBUG - b64_v:kYJIHYEG4ayHA1HRPEtKGq6u/1txC3nfoKEtU0oUJ34=
2020-05-01 19:06:07.503 - keylime.tenant - DEBUG - agent_quote received quote: reJz7H+Ls3iDBoMTA/Tti0vXPMtzMJU+EGO53JPElGDqWT3tno+wheXynnoFJIYOIf2SGm0mEa2KFSYhJQXCBq6+ziSEDCAitZASSTCAmo4I4mySDmJkZiM3AzcwIJBUeK2cqHzzxjv+1wa6kYEm/ozsr9mU6TN3Ya9Z75dSzI7OOAQBUIyl2:eJwBBgH5/gAUAAsBALq6RJm+ehqebTZoxGL3yTf2zWGkwDvHqwa0L0MNAIg/YKtZPLuHazfaqGZVqqXwjBVqKw03zlFEdi9LC066bZJo06jilXH3pBKvvCkrl6aKCx3hFMrZB4p+PU7zdsZm0aj0YsEw9Rr/wKvJOlhU7Jbm7v3Li/NvuvRW31HL2pdhkArWIFZ8x8YHf0TrU5LgLxFM7DqUzriRuwRetuHagbYe7m3gUs/lEuKt1fj+kaxSoYGIfv2PLcM7myPT7UIG7D80+3N/HMaRkj0utyt1hyCC5/nQJFiCCCn6uicGQ3pP+g4+fqeTSR5HKE/BANArG0AYLAz3j0kYiVI5uI7SFnNQdYEH:eJxjZGBg4GZgZmRgZBgwALKaCYgVGN6sLH0Tennly0ULUs7+Sfi2Uc5gueyUjeuDhWOafd76c4gSMkmBoaf/y6Q2fn39+QkPtdz60oI5Xe4dSTUU2Jb/Yl7Ez0nro2jvm1FALQAAioAgwg==
2020-05-01 19:06:07.503 - keylime.tenant - DEBUG - agent_quote received public key: -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwDT525NQXKNFTpzku7X9
CXS1mLG4Rx7rt5dMbJHPpvAzQz6WwJFh6tgxUvnUFJQ+E/ESo58bMYprBvspnDNH
LNCIyd5Ozsd5+k0P8iQA9Qa3HAdiuYw+IlinceHnfxVw/AvyoVc1TdhmMPbc+4QC
zAVtaEDM4s+x7UJLjXlkVLNXp3LM5o0Ao2gLFxuSnmdeY3OkQ6eVmJZJVKmDl5mg
hk86n8I0zXz3Mli88a7PibAa5yRmrdfBpweOzpwoDUSdgpc7eEQcUyGsdKLlTPlc
f1IlDOu0WGxyMOUao5OLwB5HdUnxYgkNxMzWqmb7Xid3UMZrqH0ixq17+qeY8FUN
+wIDAQAB
-----END PUBLIC KEY-----

2020-05-01 19:06:07.503 - keylime.tenant - DEBUG - agent_quote received tpm version: 2
2020-05-01 19:06:07.503 - keylime.tenant - DEBUG - agent_quote received hash algorithm: sha256
2020-05-01 19:06:07.504 - keylime.tenant - DEBUG - agent_quote received encryption algorithm: rsa
2020-05-01 19:06:07.504 - keylime.tenant - DEBUG - agent_quote received signing algorithm: rsassa
2020-05-01 19:06:07.509 - keylime.registrar_client - ERROR - 'int' object has no attribute 'read'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/registrar_client.py", line 114, in getKeys
    response_body = json.loads(response.read().decode())
AttributeError: 'int' object has no attribute 'read'
2020-05-01 19:06:07.510 - keylime.tenant - WARNING - AIK not found in registrar, quote not validated
2020-05-01 19:06:07.525 - keylime.tenant - INFO - Agent 6D98723F-153F-5BD6-9097-152011DD3EE8 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/tenant.py", line 833, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/tenant.py", line 706, in do_quote
    raise e
  File "/usr/local/lib/python3.6/dist-packages/keylime-1.2-py3.6.egg/keylime/tenant.py", line 669, in do_quote
    raise UserError("TPM Quote from cloud agent is invalid for nonce: %s"%self.nonce)
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: OYhF4XEax4T4pSpEMC41
```

**Comment by maugustosilva** [comment]
@lukehinds turns out the fix is quite trivial: the method `validate_tpm_quote` in `keylime/tenant.py` is calling `registrar_client.getKeys`specifying the *verifier* IP instead of the *registrar* IP. I will wait for others to comment on this (it looks like a bug to me), but I believe it is literally a one-line fix (which I am happy to send)

**Comment by jetwhiz** [comment]
@maugustosilva good catch!  I agree that might just be a bug.  I don't think I've ever run the verifier and registrar separately before, so this likely never surfaced in the past.  what do you think @lukehinds ?

**Comment by maugustosilva** [comment]
ah, of course, the error message `WARNING - AIK not found in registrar, quote not validated` is totally misleading, and we should probably include a solution for this too. The problem is, the `response` in `getKeys` is an `int` (`503`) in case the registrar does not respond on the configured port.

**Comment by maugustosilva** [comment]
@jetwhiz @lukehinds this commit solves the problem (it is a single-line fix), and now produces a more clear and unequivocal indication when the registrar cannot be contacted.
