### ISSUE TITLE
Is it possible to enable the tenant to verify a VM's integrity without a vTPM?

### ISSUE THREAD

**Issue by Han0nly** [keylime/keylime#321]
Hi, I'm a little confused about the vTPM design in the wiki. I want to build an Openstack cloud(with a couple of servers with TPM2) in my lab using KVM and I want to make everyone in my lab can verify their VM's integrity.

So I want to know is it possible to enable the tenant to verify a VM's integrity without a vTPM? Or I have to install TPM emulator on everyone's virtual machines.

Thank you!

**Comment by lukehinds** [comment]
Hi @Han0nly 

I would ignore the stuff in the wiki as that is around a pending design. There is nothing to stop you using a vTPM right away.  The only consideration to make is that a vTPM is not as secure as a hardware TPM which has the crypto keys are locked into the chip. 

With a vTPM, it being software based means the keys reside in the host memory. However if you own the host, this is less of a concern (as you won't be hacking your own VMs), so Keylime does afford protections still and will protect you against attackers (as long as they don't hack into the host OS itself).

Google Cloud offer this approach, you can add a vTPM to a virtual machine and use that to attest the trust within the VM. 

If you need help setting up the vTPM let me know, we plan on changing our CI to use a vTPM.

Eventually we will have full hardware level protections for a vTPM which is what the design in the wiki is about. This is still a work in progress though and requires changes in the kernel.

**Comment by lukehinds** [comment]
Edit, I missed your original question. Yes you can, using passthrough:

https://libvirt.org/formatdomain.html#elementsTpm

I would not do this though, as its a one to one mapping. So only one VM will be able to use the hardware TPM. I recommend you go for a vTPM implementation, and then when deep quote features land (extend trust from the vTPM to hardware TPM), you will already have your environment set up.

**Comment by Han0nly** [comment]
Thank you for your answer @lukehinds , I don't know if I get it right, if a tenant want to verify their VM's integrity, they need to create a VM with a TPM device using emualtor/passthrough, and then they need to install the Keylime agent and register it to the Keylime registrar . After that they can request the Keylime verifier Restful API to verify VM's integrity, do I get it right? Do Keylime verifier and Keylime registrar have other prerequisites or I can just install them on any of machines? Thanks!

**Comment by lukehinds** [comment]
Yes, that's it. 

On each VM you would run the vtpm and keylime agent and then on another machine (like a management machine) you would run the keylime verifier and register (or you could even run the verifier and register on different machines).

You would then use the keylime tenant application to start the measurement of the VM and if it passes you could run an autorun.sh script to set things up on the machine (for example install and application)., You could also deliver some secrets to the machine. 

I recommend watching the following demo to get an idea of the architecture and flow of interaction between the different systems in Keylime:

https://www.youtube.com/watch?v=Qhr_aVBCZPw

Also jump on the gitter channel if you need some support getting things running. 

https://gitter.im/keylime-project/community

**Comment by Han0nly** [comment]
Thank you @lukehinds , your answer is really helpful, l'm much obliged.

**Comment by lukehinds** [comment]
> Thank you @lukehinds , it is really helpful, l'm much obliged.

My pleasure, I have wanted to integrate keylime more with openstack, but not had the spare time available as yet. If you want plan to go ahead we will support you as much as we can and help make needed changes into Keylime.

**Comment by Han0nly** [comment]
I found some links may be helpful for integration with openstack. It seems openstack community are working on vtpm and it basically works.

https://that.guru/blog/emulated-tpm-in-openstack/

**Comment by lukehinds** [comment]
Awesome news. glad to see that is happening!

**Comment by Han0nly** [comment]
Hi @lukehinds , one thing I need help, I watched the demo on youtube and I want to try this demo locally. So can I get to these script somewhere? Thank you!

**Comment by lukehinds** [comment]
Hi @Han0nly , sure..we have a ansible role with a vagrant file:

https://github.com/keylime/ansible-keylime-tpm-emulator/

If you install vagrant, you can then clone the above and then just run `vagrant up --provision` and it will bring up a running keylime instance with a tpm emulator to use.

Try that, if you hit any issues, just raise a github issue in the ansible repo above and tag me in there!

**Comment by Han0nly** [comment]
Sorry @lukehinds , my English is not very good, so you may have misunderstood. What I want to ask is whether there is a script used in that example in Youtube, such as copy ssh keys/remove ssh keys after failure verification. Thank you!

**Comment by Han0nly** [comment]
Hi, I deployed Keylime on 2 centos7 virtual machines with TPM2.0 device. The first one run `keylime_agent`, and the other one run `verifier&registrar&ca`, then I run `keylime_tenant -v 127.0.0.1 -t agent -tp 9002 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --cert /var/lib/keylime/cv_ca --include /root/payload/ --whitelist /root/whitelist.txt -c add` on the second one to add a policy, but an error occurred.

```
[root@verifier payload]# keylime_tenant -v 127.0.0.1 -t agent -tp 9002 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --cert /var/lib/keylime/cv_ca --include /root/payload/ --whitelist /root/whitelist.txt -c add
Using config file /etc/keylime.conf
2020-06-14 09:07:56.915 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 09:07:56.915 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2020-06-14 09:07:56.922 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2020-06-14 09:07:56.922 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2020-06-14 09:07:57.040 - keylime.ima - WARNING - No boot_aggregate value found in whitelist, adding an empty one
Please enter the password to decrypt your keystore:
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 794, in main
    mytenant.init_add(vars(args))
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 294, in init_add
    ca_util.cmd_mkcert(args["ca_dir"],self.agent_uuid)
  File "/usr/local/lib/python3.6/site-packages/keylime/ca_util.py", line 84, in cmd_mkcert
    priv = read_private()
  File "/usr/local/lib/python3.6/site-packages/keylime/ca_util.py", line 455, in read_private
    plain = crypto.decrypt(toread['priv'],key)
  File "/usr/local/lib/python3.6/site-packages/keylime/crypto.py", line 199, in decrypt
    return decryptor.update(ciphertext) + decryptor.finalize()
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 198, in finalize
    data = self._ctx.finalize()
  File "/usr/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 164, in finalize
    raise InvalidTag
cryptography.exceptions.InvalidTag
```

Did I do something wrong？

**Comment by lukehinds** [comment]
Can you check that ca_implementation is set to `cfssl`

https://github.com/keylime/keylime/blob/e0a1a98017828a3af6ab5a8bcaf2bcb91372e5d1/keylime.conf#L14

Also that you have cfssl installed.

**Comment by Han0nly** [comment]
> Can you check that ca_implementation is set to `cfssl`
> 
> https://github.com/keylime/keylime/blob/e0a1a98017828a3af6ab5a8bcaf2bcb91372e5d1/keylime.conf#L14
> 
> Also that you have cfssl installed.

Yes, cfssl is installed and ca_implementation is set to cfssl

**Comment by lukehinds** [comment]
I think I see it now, point cert to a new location:

`--cert /home/han0nly/keylimeca`

You will then be prompted to create a password, put whatever you like. After this start `keylime_ca` and use the same password as before.

**Comment by Han0nly** [comment]
Sorry to bother you again...but after that I met a new problem.

When I run `keylime_tenant -v 127.0.0.1 -t 192.168.1.29 -tp 9002 -u agent --cert /root/keylimeca --include /root/payload/ --whitelist /root/whitelist.txt -c add` and then I was prompted to input a password. Then I got this error:

```
[root@verifier ~]# keylime_tenant -v 127.0.0.1 -t 192.168.1.29 -tp 9002 -u agent3 --cert /root/keylimeca --include /root/payload/ --whitelist /root/whitelist.txt -c add
Using config file /etc/keylime.conf
2020-06-14 10:27:37.177 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 10:27:37.178 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2020-06-14 10:27:37.184 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2020-06-14 10:27:37.184 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2020-06-14 10:27:37.319 - keylime.ima - WARNING - No boot_aggregate value found in whitelist, adding an empty one
Please enter the password to decrypt your keystore: 
2020-06-14 10:27:40.112 - keylime.ca-util - INFO - Created certificate for name agent3 successfully in /root/keylimeca
2020-06-14 10:27:40.176 - keylime.ca-util - INFO - Creating cert package for agent3 in agent3-pkg.zip
2020-06-14 10:27:40.239 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2020-06-14 10:27:40.616 - keylime.registrar_client - INFO - Setting up client TLS...
2020-06-14 10:27:40.620 - keylime.registrar_client - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 10:27:40.629 - keylime.registrar_client - CRITICAL - Error: unexpected http response code from Registrar Server: 404
2020-06-14 10:27:40.629 - keylime.registrar_client - CRITICAL - Response code 404: agent_id not found
2020-06-14 10:27:40.629 - keylime.tenant - WARNING - AIK not found in registrar, quote not validated
2020-06-14 10:27:41.863 - keylime.tenant - INFO - Agent agent3 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 797, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 690, in do_quote
    raise e
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 653, in do_quote
    raise UserError("TPM Quote from cloud agent is invalid for nonce: %s"%self.nonce)
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: L1z2QCoAuE3bAmFqRwmN
```

The `keylime_agent` logged these:

```
2020-06-14 10:27:40.574 - keylime.cloudagent - INFO - GET invoked from ('192.168.1.142', 43698) with uri:/quotes/identity?nonce=L1z2QCoAuE3bAmFqRwmN
2020-06-14 10:27:40.605 - keylime.cloudagent - INFO - GET identity quote returning 200 response.
2020-06-14 10:27:42.094 - keylime.cloudagent - INFO - GET invoked from ('192.168.1.142', 43704) with uri:/quotes/integrity?nonce=iF4y0DvAgHMK0CO7d3Se&mask=0x408400&vmask=0x808000&partial=0
2020-06-14 10:27:42.124 - keylime.cloudagent - INFO - GET integrity quote returning 200 response.
2020-06-14 10:27:42.408 - keylime.revocation_notifier - WARNING - Unable to check signature of revocation message: /var/lib/keylime/secure/unzipped/RevocationNotifier-cert.crt not available
```

**Comment by lukehinds** [comment]
I think this is the issue:

`2020-06-14 10:27:40.629 - keylime.registrar_client - CRITICAL - Response code 404: agent_id not found`

What do you have for the UUID value:

https://github.com/keylime/keylime/blob/e0a1a98017828a3af6ab5a8bcaf2bcb91372e5d1/keylime.conf#L57

You're using `-u agent` so it would need to look like this:

`agent_uuid = agent`

We typically use the following fixed value of `D432FBB3-D2F1-4A97-9EF7-75BD81C00000` for development. If you like you can use `agent_uuid = generate` and it will create a random UUID each time.

So give this a try:

`keylime_tenant -v 127.0.0.1 -t 192.168.1.29 -tp 9002 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --cert /root/keylimeca --include /root/payload/ --whitelist /root/whitelist.txt -c add`

**Comment by lukehinds** [comment]
p.s it might be worth cleaning things up a bit:

Stop / kill the verifier / agent / registrar 

`umount /var/log/keylime/secure`
`rm -r /var/log/keylime`

Start the verifier / registrar / agent

**Comment by kaifeng** [comment]
The vtpm support in openstack is fairly simple as nova just provides a path to create a vtpm device for a VM [1]. There were times that trusted compute + opencit available there but not maintained anymore and removed from the upstream.
I am towarding the integration with openstack too, with ironic and probably nova, it's nice to see @Han0nly working on the same road :)

[1] http://specs.openstack.org/openstack/nova-specs/specs/train/approved/add-emulated-virtual-tpm.html

**Comment by lukehinds** [comment]
I will support you both whenever I can. 

We do have some integration with openstack already. You can set the agent_uuid value to openstack and it gets a uuid from the nova meta data service.

**Comment by Han0nly** [comment]
hi @kaifeng @lukehinds , I have ran OPENCIT for a couple of times , but it only support TPM1.2 and it's new version SecL can't be built in my environment, so I turn to Keylime for help. I'll try to make some contribution to Keylime and nice to meet you guys!

**Comment by Han0nly** [comment]
Sorry to bother again @lukehinds , I have tried cleaning and using a unique uuid, but I still get an error, did I miss some configurations or something?

keylime_tenant
```
[root@verifier ~]# keylime_tenant -v 127.0.0.1 -t agent -tp 9002 -u 4bf03a01-8920-4f9a-9a29-9edc0592d5a4 --cert /root/keylimeca/ --include /root/payload/ --whitelist /root/whitelist.txt -c add
Using config file /etc/keylime.conf
2020-06-14 20:27:42.379 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 20:27:42.379 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2020-06-14 20:27:42.386 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2020-06-14 20:27:42.386 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2020-06-14 20:27:42.581 - keylime.ima - WARNING - No boot_aggregate value found in whitelist, adding an empty one
Please enter the password to decrypt your keystore:
2020-06-14 20:27:47.537 - keylime.ca-util - INFO - Created certificate for name 4bf03a01-8920-4f9a-9a29-9edc0592d5a4 successfully in /root/keylimeca/
2020-06-14 20:27:47.598 - keylime.ca-util - INFO - Creating cert package for 4bf03a01-8920-4f9a-9a29-9edc0592d5a4 in 4bf03a01-8920-4f9a-9a29-9edc0592d5a4-pkg.zip
2020-06-14 20:27:47.658 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2020-06-14 20:27:48.116 - keylime.registrar_client - INFO - Setting up client TLS...
2020-06-14 20:27:48.121 - keylime.registrar_client - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 20:27:48.134 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 3.2.2
2020-06-14 20:27:48.146 - keylime.tpm2 - ERROR - No Root CA matched EK Certificate
2020-06-14 20:27:48.146 - keylime.tenant - WARNING - Invalid EK certificate
2020-06-14 20:27:49.603 - keylime.tenant - INFO - Agent 4bf03a01-8920-4f9a-9a29-9edc0592d5a4 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 797, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 690, in do_quote
    raise e
  File "/usr/local/lib/python3.6/site-packages/keylime/tenant.py", line 653, in do_quote
    raise UserError("TPM Quote from cloud agent is invalid for nonce: %s"%self.nonce)
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: 1LMNNM580SLcZptsXPEH
```

keylime_verifier
```
[root@verifier ~]# keylime_verifier             Using config file /etc/keylime.conf
2020-06-14 20:25:46.360 - keylime.cloudverifier - INFO - agent ids in db loaded from file: [('D432FBB3-D2F1-4A97-9EF7-75BD81C00000',), ('agent',), ('agent1',), ('agent2',), ('agent3',)]
2020-06-14 20:25:46.360 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2020-06-14 20:25:46.360 - keylime.cloudverifier_common - INFO - Setting up TLS...
2020-06-14 20:25:46.360 - keylime.cloudverifier_common - INFO - Existing CA certificate found in /var/lib/keylime/cv_ca, not generating a new one
2020-06-14 20:25:46.363 - keylime.cloudverifier - INFO - Starting service for revocation notifications on port 8992
2020-06-14 20:27:48.084 - keylime.cloudverifier - INFO - POST returning 200 response for adding agent id: 4bf03a01-8920-4f9a-9a29-9edc0592d5a4
2020-06-14 20:27:49.603 - keylime.cloudverifier - INFO - PUT returning 200 response for agent id: 4bf03a01-8920-4f9a-9a29-9edc0592d5a4
2020-06-14 20:27:49.839 - keylime.registrar_client - INFO - Setting up client TLS...
2020-06-14 20:27:49.844 - keylime.registrar_client - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2020-06-14 20:27:49.858 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 3.2.2
2020-06-14 20:27:49.864 - keylime.tpm - INFO - Checking IMA measurement list on agent: 4bf03a01-8920-4f9a-9a29-9edc0592d5a4
2020-06-14 20:27:50.726 - keylime.ima - WARNING - Hashes for file boot_aggregate don't match 5445029c1db5e91093eaf6d921bd1abed9cef954 not in ['0000000000000000000000000000000000000000']
2020-06-14 20:27:50.726 - keylime.ima - ERROR - IMA ERRORS: template-hash 0 fnf 0 hash 1 good 0
2020-06-14 20:27:51.008 - keylime.cloudverifier - WARNING - agent 4bf03a01-8920-4f9a-9a29-9edc0592d5a4 failed, stopping polling
2020-06-14 20:27:51.028 - keylime.revocation_notifier - INFO - Sending revocation event to listening nodes..
```

Keylime_agent
```
2020-06-14 20:26:02.151 - keylime.cloudagent - INFO - Agent UUID: 4bf03a01-8920-4f9a-9a29-9edc0592d5a4
2020-06-14 20:26:02.352 - keylime.registrar_client - INFO - Agent registration requested for 4bf03a01-8920-4f9a-9a29-9edc0592d5a4
2020-06-14 20:26:02.370 - keylime.tpm2 - INFO - AIK activated.
2020-06-14 20:26:02.377 - keylime.registrar_client - INFO - Registration activated for agent 4bf03a01-8920-4f9a-9a29-9edc0592d5a4.
2020-06-14 20:26:02.417 - keylime.cloudagent - INFO - Starting Cloud Agent on 192.168.1.29:9002 use <Ctrl-C> to stop
2020-06-14 20:26:02.419 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 192.168.1.142:8992
2020-06-14 20:27:48.085 - keylime.cloudagent - INFO - GET invoked from ('192.168.1.142', 43928) with uri:/quotes/identity?nonce=1LMNNM580SLcZptsXPEH
2020-06-14 20:27:48.113 - keylime.cloudagent - INFO - GET identity quote returning 200 response.
2020-06-14 20:27:49.808 - keylime.cloudagent - INFO - GET invoked from ('192.168.1.142', 43934) with uri:/quotes/integrity?nonce=68WirHfhkMptW1DaRkG9&mask=0x408400&vmask=0x808000&partial=0
2020-06-14 20:27:49.835 - keylime.cloudagent - INFO - GET integrity quote returning 200 response.
2020-06-14 20:27:51.027 - keylime.revocation_notifier - WARNING - Unable to check signature of revocation message: /var/lib/keylime/secure/unzipped/RevocationNotifier-cert.crt not available
```

**Comment by lukehinds** [comment]
Hi Han0nly,

Are you using a TPM emulator?

**Comment by Han0nly** [comment]
Yes, I use Vmware Workstation to create a TPM2.0 device on a VM.

**Comment by Han0nly** [comment]
Hi @lukehinds , 

Do I need to use the TPM emulator embedded in the Keylime installation scripts using `-s` option?

**Comment by lukehinds** [comment]
Hi @Han0nly , I have no experience with the VMWare tpm, so can't help much there.

There are two ways of doing this. 

One is the tpm emulator, you can see how this is installed in our docker file:

https://github.com/keylime/keylime/blob/89e2ffb55829ea3af7cb602b7df90e43d23372e1/docker/Dockerfile-tpm20#L71-L77

One this is installed you will need to run the following steps to enable it:

https://github.com/keylime/keylime/blob/89e2ffb55829ea3af7cb602b7df90e43d23372e1/.ci/test_wrapper.sh#L6-L33

You should then be able to run `tpm2_pccread` and see a lot of hash values come back.

Using the emulator, will mean the tpm starts *after* IMA in the kernel, so IMA does not register the TPM (as it can't see one). We get around this using an ima emulator. You can run this with:

`keylime_ima_emulator`

The second option is to use the vTPM, here is a script to show how to set up a hypervisor host and deploy a vTPM into a virtual machine

https://github.com/keylime/keylime/blob/master/scripts/vtpm.sh

I will try and take some time to go over the vTPM as well,. as I am not sure if IMA see's it!

**Comment by kaifeng** [comment]
vTPM is just like a real TPM and keylime works great on it. One thing worth to note is that due to the random system boot sequence, the PCR10 can't be trusted, I think this is understandable, as long as we replay the calculation to reach the end result, it should be fine.

**Comment by Han0nly** [comment]
Hi @kaifeng , is this error `ERROR - No Root CA matched EK Certificate` rooted in vTPM? or due to some misconfigurations by myself?

**Comment by lukehinds** [comment]
This might be because we need an entry in `https://github.com/keylime/keylime/tree/master/tpm_cert_store`

You can get around that for now by changing the following to False:

https://github.com/keylime/keylime/blob/89e2ffb55829ea3af7cb602b7df90e43d23372e1/keylime.conf#L321

Just thinking @kaifeng / @Han0nly , should we set up a [enhancement proposal](https://github.com/keylime/enhancements) for the OpenStack integration? . I would really like to get any deployment notes etc documented for other community members to use.

**Comment by kaifeng** [comment]
> Hi @kaifeng , is this error `ERROR - No Root CA matched EK Certificate` rooted in vTPM? or due to some misconfigurations by myself?

Sorry I couldn't remember the details, last time I used keylime on a VM with vTPM days back to two months ago, and I still don't have an enviroment ready to play :(
Judging by code, it's unlikely I didn't have this issue though, but I didn't aware it caused any trouble to me. I think this might be what you are looking for: https://github.com/stefanberger/swtpm/wiki/Certificates-created-by-swtpm_setup

**Comment by kaifeng** [comment]
> Just thinking @kaifeng / @Han0nly , should we set up a [enhancement proposal](https://github.com/keylime/enhancements) for the OpenStack integration? . I would really like to get any deployment notes etc documented for other community members to use.

@lukehinds Honestly speaking, integration with openstack sounds quite big to me, maybe we need to break down into smaller features that would be easier to land, e.g., integrates keylime agent into ironic-python-agent so that we can get quote from the machine where the ramdisk is running. Currently keylime services are under the same project, this might have some issue in the packaging.

**Comment by kaifeng** [comment]
> hi @kaifeng @lukehinds , I have ran OPENCIT for a couple of times , but it only support TPM1.2 and it's new version SecL can't be built in my environment, so I turn to Keylime for help. I'll try to make some contribution to Keylime and nice to meet you guys!

opencit was unmaintained for a few years, I have successfully built and running on the VM with vTPM, with a few tweaks, but it would be a nightmare to maintain.
