### ISSUE TITLE
registrar needs indepent messaging

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#350]
When starting `keylime_registrar` on its own its log messaging suggests it should be on the same machine as the verifier, whereas going forward this is not the only deployment option 

```
keylime_registrar 
Using config file /etc/keylime.conf
2020-09-08 14:11:31.098 - keylime.cloudverifier_common - INFO - Setting up TLS...
Traceback (most recent call last):
  File "/usr/local/bin/keylime_registrar", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')()
  File "/usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime/cmd/registrar.py", line 21, in main
    'registrar', 'registrar_tls_port'), config.getint('registrar', 'registrar_port'))
  File "/usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime/registrar_common.py", line 516, in start
    generatedir='reg_ca')
  File "/usr/local/lib/python3.7/site-packages/keylime-0.0.0-py3.7.egg/keylime/cloud_verifier_common.py", line 128, in init_mtls
    "It appears that the verifier has not yet created a CA and certificates, please run the verifier first")
Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first
```

**Comment by nabilschear** [comment]
FYI: this only happens when you tell the registrar to share the TLS CA with the verifier (and it sorta implicitly assumes that they are on the same machine.  You can just set a ca dir and the registrar will establish it's own ca and certs.
