### ISSUE TITLE
keylime_agent: Read EK Cert fail with authorization failure in Hyper-V vTPM 

### ISSUE THREAD

**Issue by dnoliver** [keylime/keylime#503]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora Server 33
 * Processor architecture:  x86_64
 * TPM Manufacturer:  Virtual TPM provided by HyperV
 * Keylime version:  

```
# Using the rpm version
# The intention is to make this work in Fedora IoT 33
# So, the rpm is required to get ostree happy
[test@fedora-server ~]$ rpm -qa keylime
keylime-5.7.2-2.fc33.noarch
```

# Description 

Cannot run `keylime_agent`, it fails to get the EKCert.

## Expected behavior vs. actual behavior 

Expected: should work
Actual: fail with tpm-tools error message

## Steps to reproduce problem
1.  Install Fedora Server 33 
2. `sudo dnf install -y keylime`
3. `sudo keylime_agent`

# Relevant logs

Full execution log below

```
# Start with the TPM Cleared
[test@fedora-server ~]$ tpm2_clear 

# Check that the EKCert exists and can be read before running keylime_agent
[test@fedora-server ~]$ tpm2_nvread -C o 0x1C00002
00?J{6'&*H
010
220113195925Z0(1&0$U CA0                                                             0       *H          Microsoft Hyper-V Virtual TPM0"0
y/<b;}OS        9XVC?zŇu>AD?Wwk/:gVrFcte^6aVY\SZ{ҧQ|X^SnX-<̓_KC/l(Q*0c)               )}k_IA_Ci*i*QXQ>2L|pۄd
         4&㠡&t<00U                                                                  0U 0aUW0US0Q10g
               id:201%0#g
                         Firmware:538247443.139472210g

0                                                     id:4D5346540!U    00g1

 2.0t0U 0U
0@0U%   00U#0;(
        *H     ckt6zu0
        s8LG0U0y8}܇
)%*=STP=MY1Q\9ZH       KVaxXtB*j.DGP4y&ӿ0EM,\:zEZvSNKR/kP!)mZC6,֌7H Y
                                                                      $̊^_
*Q,=v:=!&ۺ/@sVwGO̒Ly

# Run keylime_agent and watch it fail
[test@fedora-server ~]$ sudo keylime_agent
Using config file /etc/keylime.conf
2021-01-13 17:10:30.040 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 4.3.0
2021-01-13 17:10:30.089 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2021-01-13 17:10:30.149 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2021-01-13 17:10:30.149 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81000000
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/agent.py", line 15, in main
    keylime_agent.main()
  File "/usr/lib/python3.9/site-packages/keylime/keylime_agent.py", line 502, in main
    (ek, ekcert, aik, ek_tpm, aik_name) = tpm.tpm_init(self_activate=False, config_pw=config.get(
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py", line 945, in tpm_init
    ekcert = self.read_ekcert_nvram()
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py", line 1264, in read_ekcert_nvram
    raise Exception("tpm2_nvread for ekcert failed with code "+str(code)+": "+str(errout))
Exception: tpm2_nvread for ekcert failed with code 1: ['WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error \n', 'ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x000009a2) \n', 'ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications\n', 'ERROR: Failed to read NVRAM area at index 0x1C00002\n', 'ERROR: Unable to run tpm2_nvread\n']

# Now try to read the EKCert, get the same failure
[test@fedora-server ~]$ tpm2_nvread -C o 0x1C00002
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread

# Version of tools
[test@fedora-server ~]$ rpm -qa tpm2*
tpm2-tss-3.0.1-1.fc33.x86_64
tpm2-tools-4.3.0-1.fc33.x86_64
tpm2-abrmd-selinux-2.3.1-2.fc33.noarch
tpm2-abrmd-2.3.3-1.fc33.x86_64
```

From here, I have to run `tpm2_clear` to go back to initial state

Attach any relevant log files that can help to debug your issue.

**Comment by kaifeng** [comment]
Hi @dnoliver, are you running on a emulator? I wonder if the nvram has some kind of policy preset, maybe nvlist could dump some useful information.

**Comment by dnoliver** [comment]
Find some information about the vTPM below.
I have no tpm2_nvlist command. 

This is an standard HyperV VM.
Using "Second Generation" to boot in UEFI Mode
Secure Boot is enabled and working.
vTPM is added from the VM configuration page.
So far, the vTPM is fully functional: Clevis TPM disk encryption, IMA, tpm2-pkcs11 and tpm2-tools command works out of the box. 

I think the problem is caused when the `tpm2_changeauth` command is called by the `keylime_agent` command.
But still could not find a way of reproducing this with just `tpm2_tools` commands. 

```shell
[test@fedora-server ~]$ tpm2_clear                                                                                                                                                                                                   

[test@fedora-server ~]$ tpm2_getcap properties-fixed
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  value: 1.16
TPM2_PT_DAY_OF_YEAR:
  raw: 0x12E
TPM2_PT_YEAR:
  raw: 0x7DE
TPM2_PT_MANUFACTURER:
  raw: 0x4D534654
  value: "MSFT"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x496F5420
  value: "IoT"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x536F6674
  value: "Soft"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x77617265
  value: "ware"
TPM2_PT_VENDOR_STRING_4:
  raw: 0x2054504D
  value: "TPM"
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x1
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x20150113
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x154822
TPM2_PT_INPUT_BUFFER:
  raw: 0x400
TPM2_PT_HR_TRANSIENT_MIN:
  raw: 0x3
TPM2_PT_HR_PERSISTENT_MIN:
  raw: 0x2
TPM2_PT_HR_LOADED_MIN:
  raw: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  raw: 0x40
TPM2_PT_PCR_COUNT:
  raw: 0x18
TPM2_PT_PCR_SELECT_MIN:
  raw: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  raw: 0xFFFFFFFF
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x0
TPM2_PT_NV_INDEX_MAX:
  raw: 0x800
TPM2_PT_MEMORY:
  raw: 0x6
TPM2_PT_CLOCK_UPDATE:
  raw: 0x1000
TPM2_PT_CONTEXT_HASH:
  raw: 0xB
TPM2_PT_CONTEXT_SYM:
  raw: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  raw: 0x100
TPM2_PT_ORDERLY_COUNT:
  raw: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  raw: 0x1000
TPM2_PT_MAX_RESPONSE_SIZE:
  raw: 0x1000
TPM2_PT_MAX_DIGEST:
  raw: 0x30
TPM2_PT_MAX_OBJECT_CONTEXT:
  raw: 0x5F0
TPM2_PT_MAX_SESSION_CONTEXT:
  raw: 0x134
TPM2_PT_PS_FAMILY_INDICATOR:
  raw: 0x0
TPM2_PT_PS_LEVEL:
  raw: 0x0
TPM2_PT_PS_REVISION:
  raw: 0x0
TPM2_PT_PS_DAY_OF_YEAR:
  raw: 0x0
TPM2_PT_PS_YEAR:
  raw: 0x0
TPM2_PT_SPLIT_MAX:
  raw: 0x80
TPM2_PT_TOTAL_COMMANDS:
  raw: 0x6A
TPM2_PT_LIBRARY_COMMANDS:
  raw: 0x69
TPM2_PT_VENDOR_COMMANDS:
  raw: 0x1

[test@fedora-server ~]$ tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  0
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x2
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x0
TPM2_PT_HR_PERSISTENT_AVAIL: 0x6
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0x20
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x3
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x3
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

[test@fedora-server ~]$ tpm2_getcap handles-nv-index
- 0x1C00002
- 0x1C08001
```

**Comment by lukehinds** [comment]
tagging @stefanberger who may have some ideas here.

**Comment by stefanberger** [comment]
I would try running `tpm2_nvreadpublic` to see what it returns in terms of attribute/access flags. (One of) mine returns:
```
0x1c00002:
  name: 000ba384a40f903451f809cc86fd6419a7a458715912fe04ad73f58cd5bd0a4eed31
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writeall|ppread|ownerread|authread|policyread|no_da|written|platformcreate
    value: 0x1100F62
  size: 991
```

**Comment by dnoliver** [comment]
```
[test@fedora-server ~]$ tpm2_nvreadpublic
0x1c00002:
  name: 000b474101b463956bd38d0ee97be0c20508090a32408749c0d7e80c010bb31d9aa2
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|ownerread|authread|no_da|platformcreate
    value: 0x4000642
  size: 1536

0x1c08001:
  name: 000b164fa3559862b9e7e5365677bd23d29c5500d518eb2e3f33b7bdcf2047a1b715
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|ownerread|authread|no_da|platformcreate
    value: 0x4000642
  size: 2048
```

**Comment by stefanberger** [comment]
Reading from `0x1c00002` with `keylime` as password works, right?

**Comment by stefanberger** [comment]
Since version 2.1 of the TCG specification 'TCG EK Credential Profile' there's a table there now that indicates what attibutes should be set; pdf page 50: https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_EKCredentialProfile_v2p3_r2_pub.pdf

```
TPMA_NV_PPWRITE = 0
TPMA_NV_OWNERWRITE = 0
TPMA_NV_AUTHWRITE = 0
TPMA_NV_POLICYWRITE = 1
TPM_NT = 0
TPMA_NV_POLICY_DELETE = 0
TPMA_NV_WRITELOCKED = 0
TPMA_NV_WRITEALL = 1
TPMA_NV_WRITEDEFINE = 0
TPMA_NV_WRITE_STCLEAR = 0
TPMA_NV_GLOBALLOCK = 0
TPMA_NV_PPREAD = 1
TPMA_NV_OWNERREAD = 1
TPMA_NV_AUTHREAD = 1
TPMA_NV_POLICYREAD = 1
TPMA_NV_NO_DA = 1
TPMA_NV_ORDERLY = 0
TPMA_NV_CLEAR_STCLEAR = 0
TPMA_NV_READLOCKED = 0
TPMA_NV_WRITTEN = 1
TPMA_NV_PLATFORMCREATE = 0
TPMA_NV_READ_STCLEAR = 0
(0x220F1008)
```

My guess is yours doesn't have the right flags set.

**Comment by dnoliver** [comment]
After running `sudo keylime_agent`, I can't read the handle, even with the keylime password

```shell
[test@fedora-server ~]$ tpm2_nvread -P keylime 0x1c00002
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread

[test@fedora-server ~]$ tpm2_nvread -C o -P keylime 0x1c00002
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x0000014a)
ERROR: Esys_NV_Read(0x14A) - tpm:error(2.0): an NV Index is used before being initialized or the state saved by TPM2_ShutdownSTATE could not be restored
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread

[test@fedora-server ~]$ tpm2_nvread -C o 0x1c00002
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread
```

I added a `logger.debug()` call in the `__run()` method to see what commands are being executed:

```shell
[test@fedora-server ~]$ sudo /usr/bin/keylime_agent
Using config file /etc/keylime.conf
2021-01-14 12:17:11.340 - keylime.tpm2 - INFO - tpm2_startup --version
2021-01-14 12:17:11.345 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 4.3.0
2021-01-14 12:17:11.345 - keylime.tpm2 - INFO - tpm2_startup -c
2021-01-14 12:17:11.367 - keylime.tpm2 - INFO - tpm2_getcap algorithms
2021-01-14 12:17:11.386 - keylime.tpm2 - INFO - tpm2_getcap properties-fixed
2021-01-14 12:17:11.400 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2021-01-14 12:17:11.400 - keylime.tpm2 - INFO - tpm2_changeauth -c o keylime
2021-01-14 12:17:11.425 - keylime.tpm2 - INFO - tpm2_changeauth -c e keylime
2021-01-14 12:17:11.451 - keylime.tpm2 - INFO - tpm2_changeauth -c o -p keylime keylime
2021-01-14 12:17:11.485 - keylime.tpm2 - INFO - tpm2_changeauth -c e -p keylime keylime
2021-01-14 12:17:11.517 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
2021-01-14 12:17:11.518 - keylime.tpm2 - INFO - Flushing old ek handle: 0x81000000
2021-01-14 12:17:11.518 - keylime.tpm2 - INFO - tpm2_getcap handles-persistent
2021-01-14 12:17:11.530 - keylime.tpm2 - INFO - tpm2_evictcontrol -C o -c 0x81000000 -P keylime
2021-01-14 12:17:11.561 - keylime.tpm2 - INFO - tpm2_createek -c - -G rsa -u /tmp/tmpj6zb5e4v -w keylime -P keylime
2021-01-14 12:17:11.656 - keylime.tpm2 - INFO - tpm2_readpublic -c 0x81000000 -o /tmp/tmp_a486xcv -f pem
2021-01-14 12:17:11.671 - keylime.tpm2 - INFO - tpm2_nvreadpublic
2021-01-14 12:17:11.696 - keylime.tpm2 - INFO - tpm2_nvread 0x1c00002 -s 1536 -o /tmp/tmp1m0ujw8j
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/agent.py", line 15, in main
    keylime_agent.main()
  File "/usr/lib/python3.9/site-packages/keylime/keylime_agent.py", line 502, in main
    (ek, ekcert, aik, ek_tpm, aik_name) = tpm.tpm_init(self_activate=False, config_pw=config.get(
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py", line 947, in tpm_init
    ekcert = self.read_ekcert_nvram()
  File "/usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py", line 1266, in read_ekcert_nvram
    raise Exception("tpm2_nvread for ekcert failed with code "+str(code)+": "+str(errout))
Exception: tpm2_nvread for ekcert failed with code 1: ['WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error \n', 'ERROR:esys:src/tss2-esys/api/Esys_NV
_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x000009a2) \n', 'ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications\n', 'ERROR: Failed to read NVRA
M area at index 0x1C00002\n', 'ERROR: Unable to run tpm2_nvread\n']
```

I run into the same problem by executing the commands in the same order:

```shell
[test@fedora-server ~]$ tpm2_startup -c
[test@fedora-server ~]$ tpm2_changeauth -c o keylime
[test@fedora-server ~]$ tpm2_changeauth -c e keylime
[test@fedora-server ~]$ tpm2_changeauth -c o -p keylime keylime
[test@fedora-server ~]$ tpm2_changeauth -c e -p keylime keylime
[test@fedora-server ~]$ tpm2_readpublic -c 0x81000000 -o /tmp/tmp_a486xcv -f pem
name: 000ba4b4285753eb50753398b27fa5d82e92db40660e303c305bc5708ef2c52e3d10
qualified name: 000bcb66bd6a06b9ae467d8dfed7d3622056a452c8f5c9c4bb4e72472801c37db4b4
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: db792fc93caf62f5d53bfbd47d4f13530906d7398e58e4c4b2ed0085c55684a2438798fa9d3f7a111713c587
75c63e96eb9d41b6443f5782d416776b2f3ad667e6d5569d9c72a08adcdfbdeb461f63748d6597b1d95e3661ed565
9135c535a7ba8d2a78e035198d07c585eadd51511189fe48d5390cac96ed8c858be2d3c81a6cd83cd5fd74bb74317
f0e210f4cee6fe9d2f156c288d9f512a30ae92b463f99c4000e4e3f0a008dedd29050a35d8a66a2c764cd1bd14bb8
533b64c072a692a85a351aea358513e32bc4c9604008bbc7c7086e5b6d8a588db8464870d9c29020e7d6b5f069649
82415f43b269fb0b3411bcc1ed26e3a0a1b326bc9d89743cb0f3
authorization policy: 837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa

[test@fedora-server ~]$ tpm2_nvread 0x1c00002 -s 1536 -o /tmp/tmp1m0ujw8j
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x00000
9a2)
ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread

[test@fedora-server ~]$ tpm2_nvread 0x1c00002 -s 1536 -o /tmp/tmp1m0ujw8j -P keylime
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x00000
9a2)
ERROR: Esys_NV_Read(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread

[test@fedora-server ~]$ tpm2_nvread 0x1c00002 -s 1536 -o /tmp/tmp1m0ujw8j -P keylime -C o
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x00000
1c4)
ERROR: Esys_NV_Read(0x1C4) - tpm:parameter(1):value is out of range or is not correct for the
 context
ERROR: Failed to read NVRAM area at index 0x1C00002
ERROR: Unable to run tpm2_nvread
```

> My guess is yours doesn't have the right flags set.

So the vTPM from Microsoft HyperV is bad? :(

**Comment by stefanberger** [comment]
It looks like the 'written' attribute is not even set, so the NVRAM location may be empty.

**Comment by dnoliver** [comment]
I harcoded this changes in the agent

```python

            # Read the RSA EK cert from NVRAM (DER format)
            if tools_version == "3.2":
                retDict = self.__run("tpm2_nvread -x 0x1c00002 -s %s -f %s -a 0x01c00002"%(ekcert_size, nvpath.name), raiseOnError=False, outputpaths=nvpath.name)
            elif tools_version in ["4.0", "4.2"]:
                if ekcert_size <= 1024:
                    retDict = self.__run("tpm2_nvread 0x1c00002 -s %s -o %s"%(ekcert_size, nvpath.name), raiseOnError=False, outputpaths=nvpath.name)
                else:
                    owner_pw = self.get_tpm_metadata('owner_pw')
                    retDict = self.__run("tpm2_nvread 0x1c00002 -s 1024 -o %s -C o -P %s"%(nvpath.name, owner_pw), raiseOnError=False, outputpaths=nvpath.name)
                    tmpRetDict = self.__run("tpm2_nvread 0x1c00002 -s 512b -C o -P %s >> %s"%(owner_pw, nvpath.name), raiseOnError=False, outputpaths=nvpath.name)
            output = common.list_convert(retDict['retout'])
            errout = common.list_convert(retDict['reterr'])
            code = retDict['code']
            ekcert = retDict['fileouts'][nvpath.name]
```

And now I can start the `keylime_verifier`, `keylime_registrar` and `keylime_agent` :)

I think there are 2 potential issues in the keylime_agent:
1. with tpm2-tools 4.3, you need to pass `-C o -P ownerpassword` to `tpm2_nvread`, otherwise will fail with auth error
2. for certs with size > 1024, you need to read it in chunks of 1024 bytes. I harcoded mine for 1024 + 5012 and it seems to work
3. The Microsoft vTPM Root CA is not in `/var/lib/keylime/tpm_cert_store`. 

And I think that debug statement in the `__run()` method is the most helpful thing to understand what keylime is doing (if you already have experience with `tpm2-tools`)

**Comment by dnoliver** [comment]
Following up with this:

1. It seems like the Hyper-V vTPM is misbehaving. It does not allow you to read a nv index with a size greater than 1024 after changing the owner authorization. The vTPM EKCert size is 1536 bytes :(. See https://github.com/tpm2-software/tpm2-tools/issues/2302#issuecomment-768430688 for a test to reproduce this. So, to make the `keylime_agent` to work with this vTPM in Hyper-V, I have to change the agent code with this

```diff
[root@fedora-server keylime]# diff /usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py.bak /usr/lib/python3.9/site-packages/keylime/tpm/tpm2.py --color
329a330
>         logger.info(cmd)
1221,1222c1222,1235
<                 retDict = self.__run(["tpm2_nvread", "0x1c00002", "-s", ekcert_size, "-o", nvpath.name],
<                                      raiseOnError=False, outputpaths=nvpath.name)
---
>                 # Fails because of https://github.com/keylime/keylime/issues/503
>                 #
>                 # retDict = self.__run(["tpm2_nvread", "0x1c00002", "-s", ekcert_size, "-o", nvpath.name],
>                 #                      raiseOnError=False, outputpaths=nvpath.name)
>                 #
>                 if int(ekcert_size) <= 1024:
>                     retDict = self.__run(["tpm2_nvread", "0x1c00002", "-s", ekcert_size, "-o", nvpath.name],
>                                          raiseOnError=False, outputpaths=nvpath.name)
>                 else:
>                     owner_pw = self.get_tpm_metadata('owner_pw')
>                     retDict = self.__run(["tpm2_nvread", "0x1c00002", "-s", "1024", "-o", nvpath.name, "-C", "o", "-P", owner_pw],
>                                          raiseOnError=False, outputpaths=nvpath.name)
>                     tmpRetDict = self.__run(["tpm2_nvread", "0x1c00002", "-s", "512b", "-C", "o", "-P", owner_pw, ">>", nvpath.name],
>                                             raiseOnError=False, outputpaths=nvpath.name)
```

2. it seems like the vTPM EKCert is issued by a local "Microsoft Hyper-V CA". The problem is that it seems like there is no documentation on how to get this certificate on your local machine. I posted a question in https://docs.microsoft.com/en-us/answers/questions/236764/location-of-34microsoft-hyper-v-ca34.html to try to find it, but no luck to this date. Until that cert location is revealed, I have to turn off the requirement of an EKCert to make the `keylime_tenant` work

```shell
[root@fedora-server issue-2302]# cat /etc/keylime.conf | grep require_ek_cert
require_ek_cert = False
```

3. In the process of searching this cert, I found that Microsoft provides an extensive cabinet file with several Root CA used to verify TPM EKCerts. The cabinet file can be found here https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates.

**Comment by ansasaki** [comment]
I think this issue is no longer relevant after the python agent removal. Maybe we could consider adding the Microsoft vTPM Root CA to our certificate store.

We should close this issue and create a new one in case the [Rust agent implementation](https://github.com/keylime/rust-keylime) has the same issue.

**Comment by stefanberger** [comment]
I agree.
