### ISSUE TITLE
isAlive deprecated in python 3.9.0

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#528]
```
2021-01-26 14:42:36.685 - keylime.registrar - INFO - Starting Cloud Registrar Server on ports 8890 and 8891 (TLS) use <Ctrl-C> to stop
Traceback (most recent call last):
  File "/usr/local/bin/keylime_registrar", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')())
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cmd/registrar.py", line 21, in main
    registrar_common.start(
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/registrar_common.py", line 505, in start
    if not any([thread.isAlive() for thread in threads]):
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/registrar_common.py", line 505, in <listcomp>
    if not any([thread.isAlive() for thread in threads]):
AttributeError: 'Thread' object has no attribute 'isAlive'
```

threading.Thread 's method `isAlive()` was renamed to `is_alive()` since Python 3.9.0

a good example of a useless, but breaking change in upstream python.

**Comment by lukehinds** [comment]
This is backported to Python 3.6 so we can change to `is_alive` and it won't have any impact on non ELA python releases

https://bugs.python.org/issue37804
