### ISSUE TITLE
Error running keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f filetosend

### ISSUE THREAD

**Issue by kgold2** [keylime/keylime#551]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: ubuntu 20
 * Processor architecture: x86
 * TPM Manufacturer: SW TPM
 * Keylime version: 

# Description 

I get an error when I run this for the first time:
keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f filetosend

## Expected behavior vs. actual behavior 

The error message asks if the TPM has a valid EK.  TPM 2.0 always has a valid EK.  Is it asking whether it's loaded>  Whether it has an EK certificate?

## Steps to reproduce problem
1. keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f filetosend

# Relevant logs

sing config file /etc/keylime.conf
2021-02-17 16:33:41.308 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-02-17 16:33:41.309 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-02-17 16:33:41.309 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-17 16:33:44.386 - keylime.registrar_client - WARNING - TLS is enabled.
2021-02-17 16:33:44.386 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-17 16:33:44.466 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 5.0
2021-02-17 16:33:44.550 - keylime.tenant - WARNING - WARNING: This UUID had more than one ek-ekcert registered to it!  This might indicate that your system is misconfigured.  Run 'regdelete' for this agent and restart
2021-02-17 16:33:44.551 - keylime.tpm2 - ERROR - not enough data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 869, in verify_ek
    ek509 = M2Crypto.X509.load_cert_der_string(ekcert)
  File "/usr/local/lib/python3.8/dist-packages/M2Crypto/X509.py", line 885, in load_cert_der_string
    cptr = m2.d2i_x509(bio._ptr())
M2Crypto.X509.X509Error: not enough data
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-17 16:33:45.099 - keylime.tenant - INFO - Agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000 stopped
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 869, in verify_ek
    ek509 = M2Crypto.X509.load_cert_der_string(ekcert)
  File "/usr/local/lib/python3.8/dist-packages/M2Crypto/X509.py", line 885, in load_cert_der_string
    cptr = m2.d2i_x509(bio._ptr())
M2Crypto.X509.X509Error: not enough data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1010, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 867, in do_quote
    raise e
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 817, in do_quote
    if not self.validate_tpm_quote(public_key, quote, tpm_version, hash_alg):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 480, in validate_tpm_quote
    if not self.check_ek(reg_keys['ek'], reg_keys['ekcert'], tpm):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 437, in check_ek
    elif not tpm.verify_ek(base64.b64decode(ekcert), ek):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 890, in verify_ek
    raise Exception("Error processing ek/ekcert. Does this TPM have a valid EK?").with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm2.py", line 869, in verify_ek
    ek509 = M2Crypto.X509.load_cert_der_string(ekcert)
  File "/usr/local/lib/python3.8/dist-packages/M2Crypto/X509.py", line 885, in load_cert_der_string
    cptr = m2.d2i_x509(bio._ptr())
Exception: Error processing ek/ekcert. Does this TPM have a valid EK?

**Comment by lukehinds** [comment]
> WARNING: This UUID had more than one ek-ekcert registered to it!

It looks like there might have been an attempt to add before which never completed. However I do think we might have a bug here, even in as much as the stack trace is unmeaningful and could be handled more gracefully.

could you try again with `-c delete` and then run again with `-c add`

**Comment by kgold2** [comment]
If I delete and then add, I get a longer error trace.  Here it is:

Using config file /etc/keylime.conf
2021-02-18 15:35:46.527 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-02-18 15:35:46.527 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-02-18 15:35:46.527 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 752, in do_quote
    response = do_quote.get(
  File "/usr/local/lib/python3.8/dist-packages/keylime/requests_client.py", line 29, in get
    return self.session.get(self.base_url + url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1010, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 759, in do_quote
    if response.status_code in (503, 504):
AttributeError: 'NoneType' object has no attribute 'status_code'

**Comment by lukehinds** [comment]
hmm this looks like the tenant is not able to connect, does the agent say anything?

**Comment by kgold2** [comment]
I tried the latest master at someone's advice.  Here's what I get now.  https issues, an odd message about more than one EK, a python backtrace, and then a mesaage that the quote is invalid but not why.

What should I try next?

keylime_tenant -c add -t 127.0.0.1 -v 127.0.0.1 -u D432FBB3-D2F1-4A97-9EF7-75BD81C00000 -f filetosend
Using config file /etc/keylime.conf
2021-03-05 11:35:35.381 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-03-05 11:35:35.385 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-05 11:35:35.385 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-03-05 11:35:35.385 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-03-05 11:35:36.048 - keylime.registrar_client - WARNING - TLS is enabled.
2021-03-05 11:35:36.048 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-03-05 11:35:36.161 - keylime.tenant - WARNING - WARNING: This UUID had more than one ek-ekcert registered to it!  This might indicate that your system is misconfigured.  Run 'regdelete' for this agent and restart
2021-03-05 11:35:36.163 - keylime.tpm - ERROR - No Root CA matched EK Certificate
2021-03-05 11:35:36.163 - keylime.tenant - WARNING - Invalid EK certificate
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-03-05 11:35:36.220 - keylime.tenant - INFO - Agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1009, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 866, in do_quote
    raise e
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 817, in do_quote
    raise UserError(
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: reI2MYcz7SqKRrl8oelE

**Comment by kgold2** [comment]
The agent says this:

2021-03-05 11:41:08.951 - keylime.cloudagent - INFO - GET invoked from ('127.0.0.1', 58520) with uri:/quotes/identity?nonce=LRimAiv0qkneRkLTU40s
2021-03-05 11:41:09.007 - keylime.cloudagent - INFO - GET invoked from ('127.0.0.1', 58521) with uri:/quotes/integrity?nonce=OrDbgwqnfT1uWz3WqTWo&mask=0x408000&vmask=0x808000&partial=0
2021-03-05 11:41:09.567 - keylime.cloudagent - INFO - GET identity quote returning 200 response.
2021-03-05 11:41:09.866 - keylime.cloudagent - INFO - GET integrity quote returning 200 response.

**Comment by lukehinds** [comment]
Thi should be simple:

`cp -r keylime/tpm_cert_store /var/lib/keylime`

**Comment by lukehinds** [comment]
although you will need a signing cert in there (this is where the manufacturer certs go).

**Comment by kgold2** [comment]
Thanks.  This is obscure enough that I suggest adding it to the install instructions.

**Comment by lukehinds** [comment]
> Thanks. This is obscure enough that I suggest adding it to the install instructions.

I do agree, I have an issue to capture if gracefully and inform the user, as the current message is not very helpful

https://github.com/keylime/keylime/issues/553

**Comment by lkatalin** [comment]
Just a comment that I am having these same issues (more than one EK, Quote intermittently invalid, and frequently the Connection Aborted message with the tenant) and `cp -r keylime/tpm_cert_store /var/lib/keylime` has not helped for my case. Especially on the frequent aborted connections I would love to know how to fix it.
