### ISSUE TITLE
The current code does not allow the deployment of agents onto verifiers (regression)

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#556]
Using latest Keylime (Feb 24th 2021 commits) and attempting to deploy an `agent` on a `verifier`.

```
/usr/local/bin/keylime_tenant -c update -t 100.64.14.16 -v 100.64.14.15 -u 0FC2F2DC-E946-5F94-9D03-5A542D237927 --cert /var/lib/keylime/ca/0FC2F2DC-E946-5F94-9D03-5A542D237927 --tpm_policy '{"23":"0000000000000000000000000000000000000000000000000000000000000000"}'
Using config file /etc/keylime.conf
2021-02-25 20:45:21.849 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-02-25 20:45:21.853 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-02-25 20:45:21.853 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x800000
2021-02-25 20:45:21.853 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
Please enter the password to decrypt your keystore:
2021-02-25 20:45:25.781 - keylime.ca-util - INFO - Creating cert package for 0FC2F2DC-E946-5F94-9D03-5A542D237927 in 0FC2F2DC-E946-5F94-9D03-5A542D237927-pkg.zip
2021-02-25 20:45:25.877 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2021-02-25 20:45:25.884 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.15:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-25 20:45:25.925 - urllib3.connectionpool - DEBUG - https://100.64.14.15:8881 "DELETE /agents/0FC2F2DC-E946-5F94-9D03-5A542D237927 HTTP/1.1" 200 49
2021-02-25 20:45:25.927 - keylime.tenant - INFO - Agent 0FC2F2DC-E946-5F94-9D03-5A542D237927 deleted from the CV
2021-02-25 20:45:25.929 - keylime.tenant - DEBUG - b64_v:9dh2W49sqGQhDhTO4cvN5StWlrJDfCQViWRIR7jhKoo=
2021-02-25 20:45:25.932 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.15:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-25 20:45:25.971 - urllib3.connectionpool - DEBUG - https://100.64.14.15:8881 "POST /agents/0FC2F2DC-E946-5F94-9D03-5A542D237927 HTTP/1.1" 200 49
2021-02-25 20:45:25.975 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 100.64.14.16:9002
2021-02-25 20:45:26.676 - urllib3.connectionpool - DEBUG - http://100.64.14.16:9002 "GET /quotes/identity?nonce=6A8GwTwxfR1YfkHNlvWF HTTP/1.1" 200 None
2021-02-25 20:45:26.680 - keylime.tenant - DEBUG - agent_quote received quote: reJz7H+Ls3iDBoMTA/ay8d1nT74qV4Y+7F/4z5/G9o+P1yDggMdTveo3YhO2zZRlEzBwt3MtDyivSggwj07I9/HLKwt0YQIDrQB+QZAYxGRXE2SQZxMzMQGwGbmZGIKmQwTZh/VJbY+f0Z3uefPGNyvx7cfu0vFaFzQoit7dESX7xBgD8VyyF:eJwBBgH5/gAUAAsBAFDmhYLZBB6vbh2Eq2gkCVcUUhpBjr9AAXUVMC1Kt7fJRA9GkMqazQCUTcyGC/iFzhV0l/NKHfll3Dc8ftuYXzsUYITeEXyp+M5GMJUs/j8j22Cf4CgbJrH6ARbdBobPF8qI4HV5sMNvyP7+OtvQMTIcaYJp336Ebe8hj/P3TAP23BOB7D+vqrWUp0j6IWZWHeKi8iPwwcjxoLVlA6reui6prQHRsrBw6ydSCEYPy+satNR7L3Zpd4pKQ0bFuqGXr2xYVlgyNqY+9Kxm1dfKcr/IEZMUkt58kwi4OQ5q2h58+01CpSxOCyT4eb6GvWhMc7cVTdXij0snDNdFtoFnKbjimn2P:eJxjZGBg4GZgZmRgZBgwALKaCYgVGGTbX9Qq7Dsf+ipz44wVO+bKHTnXrr7DRT9rsQBr2Ka5fjGETFJgsDvpk+K58S/PtrMnlr9UcmtUWWTCotzeNVEtYpuasNd1Y9r7ZhRQCwAAUbod9Q==
2021-02-25 20:45:26.681 - keylime.tenant - DEBUG - agent_quote received public key: -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3pUhxCfJkUV3eJqrGKZo
zKT+/n+KxI4jxWAnepS9OxdtcjLpjSDd5hCruEnUr4BII/ysIwOZaaWpcRsliYnP
B1h0CrzRDABWQqNI0Fp02BPJ5Ju4m7g+gNWC6W5EAoVXTQKCtV9gODsSSBebWuJa
jICZirLfTaMo3eqJKfJwUjJVnjnVdy+rHWwEtzb7Stx4tEwEBahgdIEKxl15OmxQ
SSPG+LnyJfXNPUjIlhSNEt8axJLazscPdFDzgAjUiV7wUrt4Ry5UkgTcBr3mEnQp
ybHTSBhY9e99CHbHeyqFs5Qob4yOgvh33yKopInB9H2HMHOva0qVu3QrAwg8ZWf9
KwIDAQAB
-----END PUBLIC KEY-----
2021-02-25 20:45:26.688 - keylime.tenant - DEBUG - agent_quote received hash algorithm: sha256
2021-02-25 20:45:26.688 - keylime.tenant - DEBUG - agent_quote received encryption algorithm: rsa
2021-02-25 20:45:26.689 - keylime.tenant - DEBUG - agent_quote received signing algorithm: rsassa
2021-02-25 20:45:26.690 - keylime.registrar_client - WARNING - TLS is enabled.
2021-02-25 20:45:26.690 - keylime.registrar_client - INFO - Setting up client TLS...
2021-02-25 20:45:26.693 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.240.14:18891
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-25 20:45:26.733 - urllib3.connectionpool - DEBUG - https://100.64.240.14:18891 "GET /agents/0FC2F2DC-E946-5F94-9D03-5A542D237927 HTTP/1.1" 200 None
2021-02-25 20:45:26.772 - keylime.tpm - ERROR - PCR #16: invalid bind data 3ec94c6449b1fd0cb6cdc8a7e922468124a2340423878a912658b626134ad733 from quote does not match expected value 269fc9c338529e1d87259c32be69e72ef8b8a8043d2d0e48090397e1d532905c
2021-02-25 20:45:26.776 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 100.64.14.15:8881
/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-02-25 20:45:26.806 - urllib3.connectionpool - DEBUG - https://100.64.14.15:8881 "PUT /agents/0FC2F2DC-E946-5F94-9D03-5A542D237927/stop HTTP/1.1" 200 49
2021-02-25 20:45:26.807 - keylime.tenant - INFO - Agent 0FC2F2DC-E946-5F94-9D03-5A542D237927 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 1017, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 866, in do_quote
    raise e
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 817, in do_quote
    raise UserError(
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: 6A8GwTwxfR1YfkHNlvWF
```

Notes:
* The relevant line seems to be: `2021-02-25 20:45:26.772 - keylime.tpm - ERROR - PCR #16: invalid bind data 3ec94c6449b1fd0cb6cdc8a7e922468124a2340423878a912658b626134ad733 from quote does not match expected value 269fc9c338529e1d87259c32be69e72ef8b8a8043d2d0e48090397e1d532905c`
* The same problem manifests itself even without the custom "TPM policy" enabled by the `--tpm_policy` CLI flag for `keylime_tenant`
* Initial debugging pointed out the method `sim_extend` on the `tpm` class (`tpm_main.py`) as the component failing to properly calculate the correct value for PCR16
* Had a quick chat on slack and @lukehinds was able to independently confirm the problem

**Comment by lukehinds** [comment]
@puiterwijk could you take a glance at this on Monday please.

**Comment by lukehinds** [comment]
using PR #557 

![image](https://user-images.githubusercontent.com/7058938/109497829-8a578880-7a8a-11eb-846b-48351dff5fb2.png)

**Comment by maugustosilva** [comment]
@lukehinds works for me with this new PR
