### ISSUE TITLE
keylime_webapp fails to set up client TLS in Ubuntu 20.04 (Fedora 33 works)

### ISSUE THREAD

**Issue by MartinMa28** [keylime/keylime#577]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 20.04.2 LTS
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: 6.0.1

# Description 
This issue is a follow-up to #519 .
Basically, in #519, keylime_webapp has two problems (still not fixed yet in 6.0.1):
1. The python installation directory (site-packages or dist-packages) doesn't have /static (js, css, and html files).
2.  In line 660 of `tenant_webapp.py`, the path of `client-cert.crt` and `client-private.pem` is wrong.

The two problems above can be solved by doing [this](https://github.com/keylime/keylime/issues/519#issuecomment-778323883). Then, in Fedora 33 server, keylime_webapp starts normally.

However, in Ubuntu 20.04, even after the correction of `client-cert.crt` and `client-private.pem`'s path, keylime_webapp still cannot run. In fact, in ubuntu 20.04, `client-cert.crt` and `client-private.pem` don't exist in '/var/lib/keylime/cv_ca'.
![image](https://user-images.githubusercontent.com/31215089/110446906-84f2d300-8074-11eb-9c92-8c83bc5538e6.png)

While, in fedora 33, they are there.
![image](https://user-images.githubusercontent.com/31215089/110447001-a227a180-8074-11eb-90d6-49c0b749cbfe.png)

Where the problem is in [tenant_webapp.py](https://github.com/keylime/keylime/blob/master/keylime/tenant_webapp.py#L660)
![image](https://user-images.githubusercontent.com/31215089/110444708-33e1df80-8072-11eb-83cf-46192c98951d.png)

## Expected behavior vs. actual behavior 
Expected: should start
Actually: fails to start

## Steps to reproduce problem
1. Install keylime, libtpms, swtpm, tpm2-tss, tpm2-tools, tpm2-abrmd like [this shell script](https://github.com/CS6620-S21/Performance-analysis-of-Keylime/blob/d5ed56263cadb529fb4f35ebcbc8360c4856d0b6/ubuntu_setup_script.sh).

Dependency version:
1. keylime v6.0.1
2. libtpms v0.7.7
3. swtpm v0.5.2
4. tpm2-tss 3.0.3
5. tpm2-tools 4.3.0
6. tpm2-abrmd 2.3.3
# Relevant logs
As for the first two problems (/static and wrong path), please refer to #519.

Error log for this issue:
root@keylime-ubuntu-20:~# keylime_webapp 
Using config file /etc/keylime.conf
2021-03-09 08:53:05.567 - keylime.tpm - INFO - TPM2-TOOLS Version: 3.2.2
2021-03-09 08:53:05.569 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-09 08:53:05.569 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-09 08:53:05.570 - keylime.tenant_webapp - INFO - Starting Tenant WebApp (tornado) on port 443 use <Ctrl-C> to stop
2021-03-09 08:53:05.571 - keylime.tenant_webapp - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-09 08:53:05.571 - keylime.tenant_webapp - INFO - ################################  debug  ####################################
2021-03-09 08:53:05.572 - keylime.tenant_webapp - INFO - tls_dir: /var/lib/keylime/cv_ca
2021-03-09 08:53:05.572 - keylime.tenant_webapp - INFO - my_tls_cert path: /var/lib/keylime/cv_ca/client-cert.crt
2021-03-09 08:53:05.572 - keylime.tenant_webapp - INFO - my_tls_priv_key path: /var/lib/keylime/cv_ca/client-private.pem
2021-03-09 08:53:05.572 - keylime.tenant_webapp - INFO - ################################  debug  ####################################
Traceback (most recent call last):
  File "/usr/local/bin/keylime_webapp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant_webapp.py", line 714, in main
    server_context = get_tls_context()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant_webapp.py", line 672, in get_tls_context
    context.load_cert_chain(
FileNotFoundError: [Errno 2] No such file or directory

Attach any relevant log files that can help to debug your issue.

**Comment by lukehinds** [comment]
thanks for detailed report @MartinMa28 , I can't say I know who maintains the Ubuntu package. 

@galmasi would this be a downstream pull from your debian package?

**Comment by stefanberger** [comment]
Can you try again with latest code from master?

**Comment by MartinMa28** [comment]
Will test it next week, since I am currently working in a fedora environment where keylime is installed using dnf.

**Comment by THS-on** [comment]
This can be closed because both issues are fixed.
1. is fixed in https://github.com/keylime/keylime/commit/d1599e1de2626b39fbb46c5faee45b0118a746ab
2. is fixed I think in https://github.com/keylime/keylime/commit/0558bfaec8b3b8b49960a2cbe82184f00f049d1c

cc: @mpeters
