### ISSUE TITLE
keylime_verifier fails to start on Ubuntu 18.04 (on Z) due to SQLAlchemy

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#586]
# Environment
 * OS / version: Ubuntu 18.04
 * Processor architecture: Z
 * TPM Manufacturer: None
 * Keylime version: git master (1766957a748)

```
# pip3 freeze
alembic==1.4.3
asn1==2.4.1
asn1crypto==1.4.0
astroid==1.6.0
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
colorama==0.4.4
command-not-found==0.3
coverage==4.5.2
cryptography==3.3.1
decorator==4.4.2
distro-info==0.0.0
enum-compat==0.0.3
green==2.13.0
idna==2.10
importlib-metadata==1.7.0
isort==4.3.4
jeepney==0.4.3
keylime @ file:///home/stefanb/keylime
keyring==21.4.0
keyrings.alt==3.4.0
language-selector==0.1
lazy-object-proxy==1.3.1
logilab-common==1.4.1
lxml==4.6.1
M2Crypto==0.36.0
Mako==1.1.3
MarkupSafe==1.1.1
mccabe==0.6.1
netifaces==0.10.9
numpy==1.19.2
olefile==0.46
paramiko==2.0.0
Pillow==5.1.0
plumbum==1.6.9
pyasn1==0.4.8
pycodestyle==2.3.1
pycparser==2.20
pycrypto==2.6.1
pygobject==3.26.1
pylint==1.8.3
python-apt==1.6.5+ubuntu0.4
python-dateutil==2.8.1
python-editor==1.0.4
pyxdg==0.25
PyYAML==3.12
pyzmq==19.0.2
requests==2.24.0
rpyc==3.4.4
scipy==0.19.1
SecretStorage==3.1.2
simplejson==3.17.2
six==1.15.0
SQLAlchemy==1.3.19
termstyle==0.1.11
tornado==6.0.4
ufw==0.36
Unidecode==1.1.1
urllib3==1.25.10
wrapt==1.9.0
zipp==3.1.0
```

# Description 

Start of keylime_verifier fails like this:

```
 /usr/local/bin/keylime_verifier 
Using config file /etc/keylime.conf
2021-03-15 12:34:06.040 - keylime.keylime_db - WARNING - database_url is not set, using deprecated database configuration options
2021-03-15 12:34:06.095 - keylime.keylime_db - WARNING - database_url is not set, using deprecated database configuration options
2021-03-15 12:34:06.096 - alembic.env - INFO - Migrating database cloud_verifier
2021-03-15 12:34:06.096 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-03-15 12:34:06.097 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-03-15 12:34:06.100 - alembic.runtime.migration - INFO - Running upgrade  -> 8a44a4364f5a, Initial database migration
2021-03-15 12:34:06.105 - alembic.runtime.migration - INFO - Running upgrade 8a44a4364f5a -> eeb702f77d7d, allowlist rename
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "ima_whitelist": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_verifier", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/keylime/cmd/verifier.py", line 19, in main
    keylime.cmd.migrations_apply.apply('cloud_verifier')
  File "/usr/local/lib/python3.6/dist-packages/keylime/cmd/migrations_apply.py", line 31, in apply
    alembic.config.main(argv=alembic_args)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 581, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 575, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.6/dist-packages/alembic/config.py", line 555, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.6/dist-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.6/dist-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.6/dist-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/keylime/migrations/env.py", line 147, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.6/dist-packages/keylime/migrations/env.py", line 127, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.6/dist-packages/alembic/runtime/migration.py", line 522, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python3.6/dist-packages/keylime/migrations/versions/eeb702f77d7d_allowlist_rename.py", line 20, in upgrade
    globals()["upgrade_%s" % engine_name]()
  File "/usr/local/lib/python3.6/dist-packages/keylime/migrations/versions/eeb702f77d7d_allowlist_rename.py", line 41, in upgrade_cloud_verifier
    op.alter_column('verifiermain', 'ima_whitelist', new_column_name='allowlist', existing_type=sa.Text(length=429400000), existing_nullable=True)
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/ops.py", line 1779, in alter_column
    return operations.invoke(alt)
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/base.py", line 373, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.6/dist-packages/alembic/operations/toimpl.py", line 56, in alter_column
    **operation.kw
  File "/usr/local/lib/python3.6/dist-packages/alembic/ddl/impl.py", line 233, in alter_column
    existing_nullable=existing_nullable,
  File "/usr/local/lib/python3.6/dist-packages/alembic/ddl/impl.py", line 141, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "ima_whitelist": syntax error
[SQL: ALTER TABLE verifiermain RENAME ima_whitelist TO allowlist]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by stefanberger** [comment]
I had this running on 'Z' before but hadn't followed the git tree in a while. Troubles started when upgrading to master and DB update/migration failed. The above is now a result of me removing the sqlite database files entirely.

**Comment by mpeters** [comment]
What version of SQLite are you running? I didn't realize that column renaming support is relatively new (v3.25.0) for sqlite, so we might have to go with the `batch_op` approach that we use for things like `DROP COLUMN` for sqlite.

**Comment by stefanberger** [comment]
@mpeters 

```
$ dpkg --list | grep qlit
ii  libsqlite0                             2.8.17-14fakesync1                     s390x        SQLite 2 shared library
ii  libsqlite3-0:s390x                     3.22.0-1ubuntu0.4                      s390x        SQLite 3 shared library
ii  sqlite3                                3.22.0-1ubuntu0.4                      s390x        Command line interface for SQLite 3
```

**Comment by mpeters** [comment]
@stefanberger can you see if https://github.com/keylime/keylime/pull/587 fixes this for you?

**Comment by mpeters** [comment]
Well, hold off, it's not working in CI. Tracking down why

**Comment by stefanberger** [comment]
This issue is now resolved.
