### ISSUE TITLE
tpm2_quote reporting 'out of memory for object contexts'

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#602]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora-CoreOS 33
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: https://github.com/keylime/keylime/commit/00fe135c1f2c0973947f38102ce0310a0cb283fc

# Description 

I created a container with the keylime agent. There's no tpm2-abrmd running inside this container but the tpm2 tools are directly talking to /dev/tpm0 or /dev/tpmrm0, which is passed into the container. It seems to be working fine at the beginning but then tpm2_quote fails.

## Expected behavior vs. actual behavior 

tpm2_quote should return a valid result but instead the following happens when `keylime_agent` is used to `-c add` the system:

```
Using config file /etc/keylime.conf
importing [''], __package__='keylime.elchecking'
2021-03-24 21:47:23.201 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-03-24 21:47:23.253 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.0
2021-03-24 21:47:23.263 - keylime.secure_mount - INFO - mounting secure storage location /var/lib/keylime/secure on tmpfs
2021-03-24 21:47:23.292 - keylime.tpm - WARNING - INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
2021-03-24 21:47:23.293 - keylime.tpm - WARNING - INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
2021-03-24 21:47:23.293 - keylime.tpm - WARNING - INSECURE: Only use Keylime in this mode for testing or debugging purposes.
2021-03-24 21:47:23.293 - keylime.tpm - INFO - Taking ownership with config provided TPM owner password
2021-03-24 21:47:23.378 - keylime.tpm - INFO - TPM Owner password confirmed: keylime
2021-03-24 21:47:23.973 - keylime.cloudagent - INFO - Agent UUID: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2021-03-24 21:47:25.280 - keylime.registrar_client - INFO - Agent registration requested for D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2021-03-24 21:47:25.399 - keylime.tpm - INFO - AIK activated.
2021-03-24 21:47:25.890 - keylime.registrar_client - INFO - Registration activated for agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000.
2021-03-24 21:47:26.513 - keylime.cloudagent - INFO - Starting Cloud Agent on 0.0.0.0:9002 use <Ctrl-C> to stop
2021-03-24 21:47:26.516 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 127.0.0.1:8992
2021-03-24 21:47:36.497 - keylime.cloudagent - INFO - GET invoked from ('192.168.122.200', 44068) with uri: /quotes/identity?nonce=vKezf88PchzwUAHP67Mi
2021-03-24 21:47:36.630 - keylime.cloudagent - INFO - GET identity quote returning 200 response.
2021-03-24 21:47:36.919 - keylime.cloudagent - INFO - GET invoked from ('192.168.122.200', 44074) with uri: /quotes/integrity?nonce=B0DEeo5F7R7n2ZFxUXK1&mask=0x408000&vmask=0x808000&partial=0
----------------------------------------
Exception occurred during processing of request from ('192.168.122.200', 44074)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib64/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/site-packages/keylime/keylime_agent.py", line 114, in do_GET
    quote = tpm_instance.create_quote(
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 951, in create_quote
    retDict = self.__run(command, lock=False, outputpaths=[quotepath.name, sigpath.name, pcrpath.name])
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 375, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_quote', '-c', '/var/lib/keylime/secure/tmpts2vwb7x', '-l', 'sha256:15,16,22', '-q', '42304445656f35463752376e325a467855584b31', '-m', '/tmp/tmp3quonc27', '-s', '/tmp/tmp7kvblrge', '-o', '/tmp/tmp8wdhlk3q', '-g', 'sha256', '-p', 'ws9DfDzzEwsI5EXcbJqD'] returned 1, expected 0, output [], stderr [b'WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:279:Esys_ContextLoad_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902) \n', b'ERROR: Esys_ContextLoad(0x902) - tpm:warn(2.0): out of memory for object contexts\n', b'ERROR: Invalid key authorization\n', b'ERROR: Unable to run tpm2_quote\n']
----------------------------------------
^C2021-03-24 21:47:42.590 - keylime.cloudagent - INFO - TERM Signal received, shutting down...
```

Is it possible to use all tpm2_tools without tpm2-abrmd or just 'some'?

**Comment by stefanberger** [comment]
As it turns out the container works fine once tpm2-abrmd is also running inside. It looks like some commands can be used without it, some, like tpm2_quote, need tpm2-abrmd for context management.
