### ISSUE TITLE
keylime_webapp fails with FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kgoldman** [keylime/keylime#604]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: fedora 32
 * Processor architecture: x86
 * TPM Manufacturer: na
 * Keylime version: today's master

# Description 

keylime_verifier doesn't work with latest master.  It worked recently.

## Expected behavior vs. actual behavior 

Expected program to run.  Got error.

Suggestion:  It would be useful, either in the error message or in code comments, to indicate the file name.

## Steps to reproduce problem
1. keylime_webapp

# Relevant logs

Attach any relevant log files that can help to debug your issue. 

Using config file /etc/keylime.conf
importing [''], __package__='keylime.elchecking'
2021-03-29 17:19:58.425 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.3
2021-03-29 17:19:58.426 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-29 17:19:58.427 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-03-29 17:19:58.428 - keylime.tenant_webapp - INFO - Starting Tenant WebApp (tornado) on port 443 use <Ctrl-C> to stop
2021-03-29 17:19:58.429 - keylime.tenant_webapp - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
Traceback (most recent call last):
  File "/usr/local/bin/keylime_webapp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/local/lib/python3.8/site-packages/keylime/tenant_webapp.py", line 718, in main
    server_context = get_tls_context()
  File "/usr/local/lib/python3.8/site-packages/keylime/tenant_webapp.py", line 677, in get_tls_context
    context.load_cert_chain(
FileNotFoundError: [Errno 2] No such file or directory

**Comment by stefanberger** [comment]
I ran into this issue also today and this here seems to be a solution: https://github.com/keylime/keylime/issues/519#issuecomment-778323883

**Comment by stefanberger** [comment]
Can also try this with latest code from master?

**Comment by kgold2** [comment]
> Can also try this with latest code from master?

I don't get the original error.  However, I now get this as soon as I browse to the URL.  The warning repeats about once per second.

/usr/lib/python3.8/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(

**Comment by stefanberger** [comment]
The repeating warning seems expected now. I think you can close this issue since the original error is resolved.

**Comment by kgold2** [comment]
I'd like to leave it open to let other people look at it.

1. If end users see a continuous stream of warnings, they will think something is wrong and ask for support.
2. I suspect that the fix to #605 may have added a frequent polling.  When I connect with a more browsers, the warnings get faster.

I think a UI person should decide whether this is a good design.  Besides the bandwidth and warnings, it could be annoying when an end user is viewing a web page and it refreshes in the middle of the analysis.

**Comment by mpeters** [comment]
> I'd like to leave it open to let other people look at it.

Closed issues are still searchable.

> 1. If end users see a continuous stream of warnings, they will think something is wrong and ask for support.

I agree that this warning should be fixed, but it's not specific to this issue and happens in lots of other contexts as well. It should be a separate issue.

> 2. I suspect that the fix to #605 may have added a frequent polling.  When I connect with a more browsers, the warnings get faster.
> 
> I think a UI person should decide whether this is a good design. Besides the bandwidth and warnings, it could be annoying when an end user is viewing a web page and it refreshes in the middle of the analysis.

Agreed we should probably have some sort of control for that in the UI. But like has been mentioned before the web UI has been mostly ignored for a while. I suspect there are lots of UI issues that can be improved. But again, they should be separate issues.

Unless there's some other objection why this issue should continue to be open I'll close it after a bit.
