### ISSUE TITLE
keylime_tenant add crash with TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by jronnblom** [keylime/keylime#619]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Ubuntu 18.04
 * Processor architecture: VM
 * TPM Manufacturer: swtpm - stefan berger
 * Keylime version: latest as of today (git clone)

# Description 
Trying to add a compute to KL using keylime_tenant.

keylime_tenant -c add -u 817B07F2-24F0-4EB5-B686-F15D0B4DF2A4 -t xxx -v yyy --cert /var/lib/keylime/ca

# Relevant logs
2021-04-09 14:38:29.787 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-04-09 14:38:29.789 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-04-09 14:38:29.790 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-04-09 14:38:29.790 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2021-04-09 14:38:29.791 - keylime.tenant - WARNING - CA directory does not exist. Creating...
Please enter the password to decrypt your keystore: 
2021-04-09 14:38:33.499 - keylime.ca_impl_openssl - WARNING - CRL creation with openssl is not supported
2021-04-09 14:38:33.500 - keylime.ca-util - INFO - CA certificate created successfully in /var/lib/keylime/ca
2021-04-09 14:38:33.784 - keylime.ca-util - INFO - Created certificate for name 817B07F2-24F0-4EB5-B686-F15D0B4DF2A4 successfully in /var/lib/keylime/ca
2021-04-09 14:38:33.834 - keylime.ca-util - INFO - Creating cert package for 817B07F2-24F0-4EB5-B686-F15D0B4DF2A4 in 817B07F2-24F0-4EB5-B686-F15D0B4DF2A4-pkg.zip
2021-04-09 14:38:33.976 - keylime.ca-util - INFO - Created certificate for name RevocationNotifier successfully in /var/lib/keylime/ca
2021-04-09 14:38:34.027 - keylime.ca-util - INFO - Creating cert package for RevocationNotifier in RevocationNotifier-pkg.zip
2021-04-09 14:38:34.029 - keylime.tenant - DEBUG - b64_v: Bmswx+oDZNshkJZNbh82rVnX5kIV7Kl96B/aREAX+qg=
Traceback (most recent call last):
  File "/usr/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')()
  File "/usr/lib/python3/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/lib/python3/dist-packages/keylime/tenant.py", line 1083, in main
    mytenant.do_cv()
  File "/usr/lib/python3/dist-packages/keylime/tenant.py", line 554, in do_cv
    json_message = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

Attach any relevant log files that can help to debug your issue.

**Comment by mpeters** [comment]
I think this is the same issue that @stefanberger mentioned in slack and might be related to this change https://github.com/keylime/keylime/commit/23c2ae3f9aa1ab22f9a2fec02fc5e888475c38b3 from @kaifeng

**Comment by kaifeng** [comment]
I will take a look on this issue, probably something introduced during rebase. The alllowlist change shouldn't introduce bytes data.

**Comment by kaifeng** [comment]
I didn't find evidence on how 23c2ae3 leads to this issue, my suspicion is something has changed in the process_allowlists which included bytes, @jronnblom could you print the ``data`` to the console so we know which part of data is violating the serialization?

**Comment by galmasi** [comment]
@kaifeng @jronnblom @stefanberger I hit this issue over the weekend. 

I do not understand the history of changes that led to this bug yet, but it's fairly easy to reproduce with python 3.8.7 over Fedora 32.

=========== bug description ==============

* A private key is read from a zip file by tenant.py during "init_add" (tenant.py line 366)
* The revocation key is assigned from `privkey` in line 396.
* The revocation key is thus "bytes" not "string", as it was read directly from a file.
* `do_cv` sends information from the deployer to the agent, (tenant.py line 554)
* JSON.dumps does not handle the revocation key, because -- as mentioned before -- it is of type `bytes`
* One can fix this bug trivially by forcing the revocation key to be a string (revocation_key = str....

A similar problem exists around line 421 with auth_tag --- Stefan's crypto.do_hmac returns a hex digest which is apparently of type `bytes` and JSON can similarly not handle it. 

====== proposed simplistic fix ========

I propose to open a PR (20 minutes?) in which I force both offending objects to type `string`. There should really not be a problem with making either of the two objects into strings, so I don't see a big drawback except for the fact that I don't understand how this change _came to be_.

**Comment by stefanberger** [comment]
@jronnblom Can you try again with the latest master and see whether the problem has been fixed?

**Comment by jronnblom** [comment]
> @jronnblom Can you try again with the latest master and see whether the problem has been fixed?

I'll try and then report the result back here.

**Comment by aplanas** [comment]
I think that this one can be closed
