### ISSUE TITLE
Local tests are failing since PR #654 was merged

### ISSUE THREAD

**Issue by stefanberger** [keylime/keylime#660]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 33
 * Processor architecture: cx86_64
 * TPM Manufacturer: 
 * Keylime version:  1f550cca728

# Description 

Tests are failing

## Expected behavior vs. actual behavior 

Tests should not fail  [they don't fail when one checks one step *before* 1f550cca728]

## Steps to reproduce problem
```
1.  cd .ci
2. ./run_local.sh ${PWD}/..
```
# Relevant logs

```
est.test_crypto
  Crypto_Test
.   test_aes
.   test_errors
.   test_hmac
.   test_rsa
.   test_rsa_sign
.   test_xor
test.test_ima_verification
  TestIMAVerification
.   test_measurment_verification
.   test_mixed_verfication
.   test_read_allowlist
.   test_signature_verification
test.test_registrar_db
  TestRegistrarDB
.   test_add_agent
.   test_delete_agent
DONE
Found dbus service: com.intel.tss2.Tabrmd
Restarting tpm2-abrmd.service.

Cloud Verifier Thread
Using config file /etc/keylime.conf
2021-05-07 18:19:42.173 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2021-05-07 18:19:42.268 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_verifier", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_verifier')()
  File "/usr/local/lib/python3.7/site-packages/keylime/cmd/verifier.py", line 19, in main
    keylime.cmd.migrations_apply.apply('cloud_verifier')
  File "/usr/local/lib/python3.7/site-packages/keylime/cmd/migrations_apply.py", line 31, in apply
    alembic.config.main(argv=alembic_args)
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 533, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/keylime/migrations/env.py", line 147, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.7/site-packages/keylime/migrations/env.py", line 110, in run_migrations_online
    rec["connection"] = conn = engine.connect()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2318, in raw_connection
    self.pool.unique_connection, _connection
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect
    e, dialect, self
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
Registrar Thread
Using config file /etc/keylime.conf

2021-05-07 18:20:12.193 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options

2021-05-07 18:20:12.287 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options

Traceback (most recent call last):

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect

    return fn()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection

    return _ConnectionFairy._checkout(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout

    fairy = _ConnectionRecord.checkout(pool)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout

    rec = pool._do_get()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get

    return self._create_connection()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection

    return _ConnectionRecord(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__

    self.__connect(first_connect_check=True)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect

    pool.logger.debug("Error on connect(): %s", e)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__

    exc_value, with_traceback=exc_tb,

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_

    raise exception

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect

    connection = pool._invoke_creator(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect

    return dialect.connect(*cargs, **cparams)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 488, in connect

    return self.dbapi.connect(*cargs, **cparams)

sqlite3.OperationalError: unable to open database file



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/usr/local/bin/keylime_registrar", line 11, in <module>

    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')()

  File "/usr/local/lib/python3.7/site-packages/keylime/cmd/registrar.py", line 19, in main

    keylime.cmd.migrations_apply.apply('registrar')

  File "/usr/local/lib/python3.7/site-packages/keylime/cmd/migrations_apply.py", line 31, in apply

    alembic.config.main(argv=alembic_args)

  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 559, in main

    CommandLine(prog=prog).main(argv=argv)

  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 553, in main

    self.run_cmd(cfg, options)

  File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 533, in run_cmd

    **dict((k, getattr(options, k, None)) for k in kwarg)

  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade

    script.run_env()

  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env

    util.load_python_file(self.dir, "env.py")

  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file

    module = load_module_py(module_id, path)

  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py

    spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/site-packages/keylime/migrations/env.py", line 147, in <module>

    run_migrations_online()

  File "/usr/local/lib/python3.7/site-packages/keylime/migrations/env.py", line 110, in run_migrations_online

    rec["connection"] = conn = engine.connect()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2218, in connect

    return self._connection_cls(self, **kwargs)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__

    else engine.raw_connection()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2318, in raw_connection

    self.pool.unique_connection, _connection

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect

    e, dialect, self

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection

    sqlalchemy_exception, with_traceback=exc_info[2], from_=e

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_

    raise exception

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect

    return fn()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection

    return _ConnectionFairy._checkout(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout

    fairy = _ConnectionRecord.checkout(pool)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout

    rec = pool._do_get()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get

    return self._create_connection()

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection

    return _ConnectionRecord(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__

    self.__connect(first_connect_check=True)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect

    pool.logger.debug("Error on connect(): %s", e)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__

    exc_value, with_traceback=exc_tb,

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_

    raise exception

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect

    connection = pool._invoke_creator(self)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect

    return dialect.connect(*cargs, **cparams)

  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 488, in connect

    return self.dbapi.connect(*cargs, **cparams)

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by mpeters** [comment]
This is a bit strange. Running the tests directly using `tests/run_tests.sh` on Fedora works just fine and CI uses the containers and runs them just fine as well. I'll try tracking down the differences between CI and local run to see what's up.

**Comment by maugustosilva** [comment]
@stefanberger thanks for pointing this out, I see the error now. @mpeters funnily enough, those errors are only caught by running "local" tests, not by the CI (and not by my "end-to-end" testing). Will have a PR soon

**Comment by stefanberger** [comment]
Resolved now.
