### ISSUE TITLE
The CLI utility `keylime_tenant` is broken after the merging of PR #597

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#667]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora Core 33
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm 
 * Keylime version: 3eed812c9afdc08808a09a1dab90b1e9685e3c7b

# Description 
The `add` operation on `keylime_tenant` CLI, used without measured boot or IMA, results in error.

## Expected behavior vs. actual behavior 
This command should work, adding a given `agent` to given `verifier`

## Steps to reproduce problem
```
[root@css-flex14vm1 keylime]# /usr/local/bin/keylime_tenant -c update -t 100.64.14.14 -v 100.64.14.13 -u 64124A95-1E10-543E-9560-DC8BF962E60D --cert /var/lib/keylime/ca/64124A95-1E10-543E-9560-DC8BF962E60D
Using config file /etc/keylime.conf
2021-05-11 19:46:27.895 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
2021-05-11 19:46:27.902 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-05-11 19:46:27.903 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-05-11 19:46:27.903 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
Traceback (most recent call last):
  File "/usr/lib64/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'ima_allowlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 1146, in main
    mytenant.init_add(vars(args))
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 277, in init_add
    self.process_allowlist(args)
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/tenant.py", line 210, in process_allowlist
    self.allowlist = ima.process_allowlists(al_data, excl_data)
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/ima.py", line 326, in process_allowlists
    allowlist = read_allowlist()
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/ima.py", line 348, in read_allowlist
    al_path = config.get('tenant', 'ima_allowlist')
  File "/usr/local/lib/python3.8/site-packages/keylime-0.0.0-py3.8.egg/keylime/config.py", line 159, in get
    return get_config().get(section, option)
  File "/usr/lib64/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'ima_allowlist' in section: 'tenant'
``` 

# Relevant logs
The output above should be enough

Attach any relevant log files that can help to debug your issue.

**Comment by maugustosilva** [comment]
I've tested the fix, and it works properly. Closing the issue to avoid cluttering.
