### ISSUE TITLE
Event log parsing fails because PyYAML does not accept special characters

### ISSUE THREAD

**Issue by THS-on** [keylime/keylime#760]
# Environment
 * OS / version: Fedora (Keylime Docker images)
 * Processor architecture: x86
 * TPM Manufacturer: swtpm
 * Keylime version: git snapshot of 2d70b99d9cdcbcbb1642f12510444723c68473a1

# Description 
If a UEFI event log contains non printable characters in strings like "\u0008" (backspace) PyYAML breaks and causes an unhandled exception in the verifier. 

This is caused in our case by GRUB 2 because `read` captures also non printable characters and assigns them a variable.

We could do something like `yaml.reader.Reader.NON_PRINTABLE = re.compile("[.]")` to allow any unprintable characters, but I don't  if this a good solution.

## Expected behavior vs. actual behavior 
The expected behavior is that we get the full string for validation, instead we get an exception.

## Steps to reproduce problem
1. Either create an event log containing a backspace somewhere or do the following
2. Open a python3 interpreter
3. Import the config module ` from keylime import config`
4. Try to parse yaml containing "\u008" to a dict with: `config.yaml_to_dict(["\u0008"])`

```
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-4: truncated \uXXXX escape
>>> config.yaml_to_dict(["\u0008"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/keylime/config.py", line 252, in yaml_to_dict
    return yaml.load(sep.join(arry), Loader=SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 702, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.reader.ReaderError: unacceptable character #x0008: control characters are not allowed
  in "<unicode string>", position 0
```

# Relevant logs
```
verifier_1   | 2021-09-16 20:15:19.382 - keylime.cloudverifier - ERROR - unacceptable character #x0008: control characters are not allowed
verifier_1   |   in "<unicode string>", position 99844
verifier_1   | Traceback (most recent call last):
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/cloud_verifier_tornado.py", line 739, in invoke_get_quote
verifier_1   |     failure = cloud_verifier_common.process_quote_response(agent, json_response['results'], agentAttestState)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/cloud_verifier_common.py", line 250, in process_quote_response
verifier_1   |     quote_validation_failure = get_tpm_instance().check_quote(
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1126, in check_quote
verifier_1   |     return self.check_pcrs(agentAttestState, tpm_policy, pcrs, data, False, ima_measurement_list, allowlist, ima_keyring, mb_measurement_list, mb_refstate)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_abstract.py", line 252, in check_pcrs
verifier_1   |     mb_pcrs_sha256, boot_aggregates, mb_measurement_data, mb_failure = self.parse_mb_bootlog(mb_measurement_list)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1359, in parse_mb_bootlog
verifier_1   |     mb_measurement_data = self._parse_mb_bootlog(mb_measurement_list)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1348, in _parse_mb_bootlog
verifier_1   |     return self.parse_binary_bootlog(log_bin)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1329, in parse_binary_bootlog
verifier_1   |     log_parsed_data = config.yaml_to_dict(log_parsed_strs, add_newlines=False)
verifier_1   |   File "/usr/local/lib/python3.9/site-packages/keylime/config.py", line 252, in yaml_to_dict
verifier_1   |     return yaml.load(sep.join(arry), Loader=SafeLoader)
verifier_1   |   File "/usr/lib64/python3.9/site-packages/yaml/__init__.py", line 114, in load
verifier_1   |     return loader.get_single_data()
verifier_1   |   File "/usr/lib64/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
verifier_1   |     node = self.get_single_node()
verifier_1   |   File "yaml/_yaml.pyx", line 707, in yaml._yaml.CParser.get_single_node
verifier_1   |   File "yaml/_yaml.pyx", line 725, in yaml._yaml.CParser._compose_document
verifier_1   |   File "yaml/_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
verifier_1   |   File "yaml/_yaml.pyx", line 890, in yaml._yaml.CParser._compose_mapping_node
verifier_1   |   File "yaml/_yaml.pyx", line 774, in yaml._yaml.CParser._compose_node
verifier_1   |   File "yaml/_yaml.pyx", line 851, in yaml._yaml.CParser._compose_sequence_node
verifier_1   |   File "yaml/_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
verifier_1   |   File "yaml/_yaml.pyx", line 892, in yaml._yaml.CParser._compose_mapping_node
verifier_1   |   File "yaml/_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
verifier_1   | yaml.reader.ReaderError: unacceptable character #x0008: control characters are not allowed
verifier_1   |   in "<unicode string>", position 99844
```

**Comment by THS-on** [comment]
please assign

**Comment by mpeters** [comment]
@mbestavros can you look into why the github-actions bot didn't react to Thore's "please assign" comment like it claimed it would?

**Comment by mbestavros** [comment]
@mpeters It doesn't seem like it was designed to react to messages in the first place - the bot message is from the "Greetings" workflow [here](https://github.com/keylime/keylime/blob/master/.github/workflows/greetings.yml).

AFAICT, it'll just print that message on someone's first contribution. It won't take any further action.

**Comment by mpeters** [comment]
@mbestavros ah, I was confused and thought this was part of the other workflow stuff you worked on. Thanks for the pointer and it should be fixed in https://github.com/keylime/keylime/pull/904

**Comment by THS-on** [comment]
Newer versions of tpm2-tools (>= 5.4) is now escaping most characters and we handle failures correctly, so I'm to close this.
