### ISSUE TITLE
What shall I do with Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0 error?

### ISSUE THREAD

**Issue by cdz99** [keylime/keylime#765]
When I start keylime_agent, on CentOS7

the error appears. what shall I do?

[root@localhost ~]# /usr/local/bin/keylime_agent
Using config file /etc/keylime.conf
2021-09-29 14:19:01.683 - keylime.tpm - INFO - TPM2-TOOLS Version: 3.2.2
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 5, in <module>
    from keylime.cmd.agent import main
  File "/usr/local/lib/python3.6/site-packages/keylime/cmd/agent.py", line 9, in <module>
    from keylime import keylime_agent
  File "/usr/local/lib/python3.6/site-packages/keylime/keylime_agent.py", line 53, in <module>
    tpm_instance = tpm(need_hw_tpm=True)
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 236, in __init__
    self.__startup_tpm()
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 393, in __startup_tpm
    retDict = self.__run(['tpm2_startup', '-c'])
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 383, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_startup', '-c'] returned 1, expected 0, output [], stderr [b'ERROR:tcti:src/tss2-tcti/tcti-device.c:281:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpmrm0: No such file or directory \n', b'ERROR: tcti init allocation routine failed for library: "device" options: "/dev/tpmrm0"\n', b'ERROR: Could not load tcti, got: "device"\n']

**Comment by THS-on** [comment]
What kernel version are you running?

We are now using the kernel resource manager for the TPM. If you are running a Kernel older than 4.12 this feature is no available.
Instead install tpm2-abrmd and export `TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd` before starting the agent.

**Comment by cdz99** [comment]
It is Linux 3.10.0-693.el7.x86_64. I use tpm_emulator.service as tpm. can It work?

**Comment by cdz99** [comment]
It is Linux 3.10.0-693.el7.x86_64. I use tpm_emulator.service as tpm. can It work?

**Comment by cdz99** [comment]
yum install tpm2-abrmd
export TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd

[root@localhost ~]# /usr/local/bin/keylime_agent
Using config file /etc/keylime.conf
2021-09-29 15:59:52.318 - keylime.tpm - INFO - TPM2-TOOLS Version: 3.2.2
Traceback (most recent call last):
  File "/usr/local/bin/keylime_agent", line 5, in <module>
    from keylime.cmd.agent import main
  File "/usr/local/lib/python3.6/site-packages/keylime/cmd/agent.py", line 9, in <module>
    from keylime import keylime_agent
  File "/usr/local/lib/python3.6/site-packages/keylime/keylime_agent.py", line 53, in <module>
    tpm_instance = tpm(need_hw_tpm=True)
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 236, in __init__
    self.__startup_tpm()
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 393, in __startup_tpm
    retDict = self.__run(['tpm2_startup', '-c'])
  File "/usr/local/lib/python3.6/site-packages/keylime/tpm/tpm_main.py", line 383, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_startup', '-c'] returned 1, expected 0, output [], stderr [b'ERROR: Could not dlopen library: "tabrmd"\n', b'ERROR: Could not load tcti, got: "tabrmd"\n']

**Comment by THS-on** [comment]
I don't know what kind of emulator `tpm_emulator.service` is which package contains that service.

I would recommend either to use swtpm integration into QEMU/libvrit if that is your hypervisor.
If you want to run a virtual TPM for testing on the same system use swtpm.

Some information can be found here: https://keylime-docs.readthedocs.io/en/latest/installation.html#tpm-2-0-support
