### ISSUE TITLE
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) type modifier is not allowed for type "text"

### ISSUE THREAD

**Issue by bnevis-i** [keylime/keylime#814]
# Environment
 * OS / version: Fedora 35
 * Processor architecture: x86_64
 * TPM Manufacturer: libvirt virtual TPM
 * Keylime version: master (4a1b69b1e759d824c3561ac4eb92e38dd6bb0d77)

# Description 
Error message while initializing postgres database (verifier service)

## Steps to reproduce problem
1. Configure `/etc/keylime.conf` (verifier service)
2. `systemctl start keylime_verifier`
3. `journalctl -u keylime_verifier`

# Relevant logs

```
Dec 21 14:25:16 keylime-v systemd[1]: Started keylime_verifier.service.
Dec 21 14:25:17 keylime-v keylime_verifier[17061]: Using config file /etc/keylime.conf
Dec 21 14:25:17 keylime-v keylime_verifier[17061]: 2021-12-21 14:25:17.543 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
Dec 21 14:25:17 keylime-v python3[17061]: detected unhandled Python exception in '/usr/local/bin/keylime_verifier'
Dec 21 14:25:17 keylime-v keylime_verifier[17061]: Traceback (most recent call last):
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "/usr/local/bin/keylime_verifier", line 33, in <module>
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:     sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_verifier')())
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "/usr/local/bin/keylime_verifier", line 25, in importlib_load_entry_point
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:     return next(matches).load()
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:     module = import_module(match.group('module'))
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Dec 21 14:25:17 keylime-v keylime_verifier[17061]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
...skipping...
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     return conn.execute(construct, multiparams)
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     return connection._execute_ddl(
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     ret = self._execute_context(
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     self._handle_dbapi_exception(
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     util.raise_(
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     raise exception
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     self.dialect.do_execute(
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:   File "/usr/local/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:     cursor.execute(statement, parameters)
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) type modifier is not allowed for type "text"
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: LINE 12:  ima_whitelist TEXT(429400000),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:                         ^
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: [SQL:
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: CREATE TABLE verifiermain (
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         agent_id VARCHAR(80) NOT NULL,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         v VARCHAR(45),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         ip VARCHAR(15),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         port INTEGER,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         operational_state INTEGER,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         public_key VARCHAR(500),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         tpm_policy VARCHAR(1000),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         vtpm_policy VARCHAR(1000),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         meta_data VARCHAR(200),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         ima_whitelist TEXT(429400000),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         revocation_key VARCHAR(2800),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         tpm_version INTEGER,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         accept_tpm_hash_algs TEXT,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         accept_tpm_encryption_algs TEXT,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         accept_tpm_signing_algs TEXT,
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         hash_alg VARCHAR(10),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         enc_alg VARCHAR(10),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         sign_alg VARCHAR(10),
Dec 21 14:33:00 keylime-v keylime_verifier[20488]:         PRIMARY KEY (agent_id)
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: )
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: ]
Dec 21 14:33:00 keylime-v keylime_verifier[20488]: (Background on this error at: https://sqlalche.me/e/14/f405)
Dec 21 14:33:00 keylime-v systemd[1]: keylime_verifier.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 14:33:00 keylime-v systemd[1]: keylime_verifier.service: Failed with result 'exit-code'.
```

# Related issues
- https://github.com/eNMS-automation/eNMS/issues/138

**Comment by THS-on** [comment]
@bnevis-i can you check if #815 works for you?

**Comment by sergio-correia** [comment]
Not @bnevis-i, but It worked for me on postgres. Didn't check mysql to see if it still works, though.

**Comment by THS-on** [comment]
I've ran the migration steps against a mysql database and it does not break there.

**Comment by bnevis-i** [comment]
@THS-on Ok.  Will pull the branch and test.
