### ISSUE TITLE
I suffer a problem when first using of keylime with one machine.

### ISSUE THREAD

**Issue by mengwangict** [keylime/keylime#817]
# Environment
 * OS / version: 
 * Processor architecture: 
 
[root@keylime-fedora33 ~]# uname -a
Linux keylime-fedora33 5.8.15-301.fc33.x86_64 #1 SMP Thu Oct 15 16:58:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 * TPM Manufacturer: 
I use emulator with ibmtpm1119.tar.gz and tpm2-abrmd.

 * Keylime version: 
[root@keylime-fedora33 ~]# rpm -qa | grep keylime
keylime-6.1.0-2.fc33.noarch

# Description 
     I just setup keylime in one machine and want to see if it's works ok. But it always failed. 
Is there  a nice version in some linux release versions? I am a rookie, and want to use it easily.

## Expected behavior vs. actual behavior 
Expected the keylime work good but failed

## Steps to reproduce problem
1.  setup all kind of softeares
2.  make emulator work well.
     [root@keylime-fedora33 ~]# netstat -anlp | grep 2321
tcp        0      0 0.0.0.0:2321            0.0.0.0:*               LISTEN      1024/tpm_server     
tcp        0      0 127.0.0.1:2321          127.0.0.1:54590         ESTABLISHED 1024/tpm_server     
tcp        0      0 127.0.0.1:54590         127.0.0.1:2321          ESTABLISHED 1029/tpm2-abrmd 

2.  run keylime_verifier; keylime_register; keylime_agent
3. run ” keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f /root/ima-fulesigning.pem  --uuid D432FBB3-D2F1-4A97-9EF7-75BD81C00000 --allowlist allowlist.txt  --exclude exclude.txt -c add ”
   Then, it failed, with logs below.
 
# Relevant logs

Attach any relevant log files that can help to debug your issue. 
2021-12-29 10:05:30.262 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.2
2021-12-29 10:05:30.270 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-12-29 10:05:30.270 - keylime.registrar_client - WARNING - TLS is enabled.
2021-12-29 10:05:30.270 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-12-29 10:05:30.290 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2021-12-29 10:05:30.291 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-12-29 10:05:31.414 - keylime.tpm - ERROR - Error verifying quote: Command: ['tpm2_checkquote', '-u', '/tmp/tmp7epgibb7', '-m', '/tmp/tmpvh44agss', '-s', '/tmp/tmpxthvizcv', '-f', '/tmp/tmp6fikz48g', '-g', 'sha256', '-q', '3161784f6363334b6f6e697039346e4b48474a6a'] returned 1, expected 0, output [b'pcrs:\n', b'  sha256:\n', b'    0 : 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'    16: 0xE7C4B87FAD3DBADD65BDA9B6BB0CB6FBC766A412047E2B11C0366B24CC4BF2FD\n', b'sig: 469fcd02c424cf2632cb3a47de00576e222e7dc50ccf1911f017649feca76d62141e643908c4b1c232220d598bf8b60f6f5238ad81e51662d9d3ff4bc439899066638d71bdfa2152562558089eff7c3e4eb89ede5c5f6ad1a30826a58c5a2f6bab842b82eb2d5a22e006bdf235d29a446b475e98de8a1eb96f3276f2918e10843cae9330348f5f865866ba8cedafa1f4521e01a4cab540da5782548a05609d0a709a37895cfa8e86c24cd76c731ecc819668441c1a2857d0fe8101d12e9cfefec9018bb744a993b24b73cbabaa8aa54b711e50c3c92428b41f905742140f449616a12a119487392616ada2f9d9b74a1111b8897b19d18702df8001a311eea74d\n'], stderr [b'ERROR: Error validating signed message with public key provided\n', b'ERROR: Verify signature failed!\n', b'ERROR: Unable to run tpm2_checkquote\n']
2021-12-29 10:05:31.414 - keylime.tpm - ERROR - Command: ['tpm2_checkquote', '-u', '/tmp/tmp7epgibb7', '-m', '/tmp/tmpvh44agss', '-s', '/tmp/tmpxthvizcv', '-f', '/tmp/tmp6fikz48g', '-g', 'sha256', '-q', '3161784f6363334b6f6e697039346e4b48474a6a'] returned 1, expected 0, output [b'pcrs:\n', b'  sha256:\n', b'    0 : 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'    16: 0xE7C4B87FAD3DBADD65BDA9B6BB0CB6FBC766A412047E2B11C0366B24CC4BF2FD\n', b'sig: 469fcd02c424cf2632cb3a47de00576e222e7dc50ccf1911f017649feca76d62141e643908c4b1c232220d598bf8b60f6f5238ad81e51662d9d3ff4bc439899066638d71bdfa2152562558089eff7c3e4eb89ede5c5f6ad1a30826a58c5a2f6bab842b82eb2d5a22e006bdf235d29a446b475e98de8a1eb96f3276f2918e10843cae9330348f5f865866ba8cedafa1f4521e01a4cab540da5782548a05609d0a709a37895cfa8e86c24cd76c731ecc819668441c1a2857d0fe8101d12e9cfefec9018bb744a993b24b73cbabaa8aa54b711e50c3c92428b41f905742140f449616a12a119487392616ada2f9d9b74a1111b8897b19d18702df8001a311eea74d\n'], stderr [b'ERROR: Error validating signed message with public key provided\n', b'ERROR: Verify signature failed!\n', b'ERROR: Unable to run tpm2_checkquote\n']
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 1052, in _tpm2_checkquote
    retDict = self.__tpm2_checkquote(aikFile.name, nonce, quoteFile.name, sigFile.name, pcrFile.name, hash_alg)
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 991, in __tpm2_checkquote
    retDict = self.__run(command, lock=False)
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 375, in __run
    raise Exception("Command: %s returned %d, expected %d, output %s, stderr %s" % (cmd, code, expectedcode, retout, reterr))
Exception: Command: ['tpm2_checkquote', '-u', '/tmp/tmp7epgibb7', '-m', '/tmp/tmpvh44agss', '-s', '/tmp/tmpxthvizcv', '-f', '/tmp/tmp6fikz48g', '-g', 'sha256', '-q', '3161784f6363334b6f6e697039346e4b48474a6a'] returned 1, expected 0, output [b'pcrs:\n', b'  sha256:\n', b'    0 : 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'    16: 0xE7C4B87FAD3DBADD65BDA9B6BB0CB6FBC766A412047E2B11C0366B24CC4BF2FD\n', b'sig: 469fcd02c424cf2632cb3a47de00576e222e7dc50ccf1911f017649feca76d62141e643908c4b1c232220d598bf8b60f6f5238ad81e51662d9d3ff4bc439899066638d71bdfa2152562558089eff7c3e4eb89ede5c5f6ad1a30826a58c5a2f6bab842b82eb2d5a22e006bdf235d29a446b475e98de8a1eb96f3276f2918e10843cae9330348f5f865866ba8cedafa1f4521e01a4cab540da5782548a05609d0a709a37895cfa8e86c24cd76c731ecc819668441c1a2857d0fe8101d12e9cfefec9018bb744a993b24b73cbabaa8aa54b711e50c3c92428b41f905742140f449616a12a119487392616ada2f9d9b74a1111b8897b19d18702df8001a311eea74d\n'], stderr [b'ERROR: Error validating signed message with public key provided\n', b'ERROR: Verify signature failed!\n', b'ERROR: Unable to run tpm2_checkquote\n']
/usr/lib/python3.9/site-packages/urllib3/connectionpool.py:997: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2021-12-29 10:05:32.630 - keylime.tenant - INFO - Agent D432FBB3-D2F1-4A97-9EF7-75BD81C00000 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')())
  File "/usr/local/lib/python3.9/site-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 1226, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 927, in do_quote
    raise e
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 880, in do_quote
    raise UserError(
keylime.tenant.UserError: TPM Quote from cloud agent is invalid for nonce: 1axOcc3Konip94nKHGJj

**Comment by mpeters** [comment]
Are you also running the `keylime_ima_emulator` tool? If you are using a software TPM then the IMA part of the kernel can't use it because it starts too late. So you need to use the `keylime_ima_emulator` so that it takes the IMA measurements and extends them into the software TPM.

**Comment by mengwangict** [comment]
Whether I run the cmd of keylime_ima_emulator or not, the problem keep the same.
----------------
[root@keylime-fedora33 ~]# keylime_ima_emulator 
Using config file /etc/keylime.conf
2022-01-05 15:46:34.600 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.3.2
Client accepted
Client accepted
Monitoring /sys/kernel/security/ima/ascii_runtime_measurements
extending hash 0adefe762c149c7cec19da62f0da1297fcfbffff for boot_aggregate
extending hash 5dae5b3e06d7aca5b4eb94e08aeec759c17d9f8a for /usr/lib/systemd/system-generators/kdump-dep-generator.sh
extending hash 832df71070a8de6d3909aa48404c4ab9d83a7c2e for /usr/lib/systemd/system-generators/systemd-cryptsetup-generator
extending hash b3ae1bd3fd2d652e5b00c8dd3c3519829b29bc16 for /usr/lib/systemd/system-generators/systemd-debug-generator
extending hash 676beecf5ddfe728f78ee68c78b02c07a527c188 for /usr/lib/systemd/system-generators/systemd-bless-boot-generator
extending hash 53415ebb8016648ae23e43ef303dda685ed12979 for /usr/lib/systemd/system-generators/lvm2-activation-generator
extending hash f984e4330995c6b740ee58d59732f66efed1d08e for /usr/lib/systemd/system-generators/systemd-gpt-auto-generator
extending hash 1e774a8188d166f176dbc08d10ffa80b3311c1d3 for /usr/lib/systemd/system-generators/selinux-autorelabel-generator.sh
extending hash 351797204cea04b738f74183a33c6b2008eb50d1 for /usr/lib/systemd/system-generators/systemd-hibernate-resume-generator
extending hash bad261ca7bcd3668b1c4a83453fd70fc44bb3d9c for /usr/lib/systemd/system-generators/systemd-system-update-generator
extending hash 4ffa1c39f0cfa2365668aca6c63bceb3d016c07f for /usr/lib/systemd/system-generators/systemd-rc-local-generator
extending hash f6792ac3d5ca936408bd4cb9b3db6750002d496e for /usr/lib/systemd/system-generators/systemd-veritysetup-generator
extending hash c665bdaef831d3d93a33f714b313cb4d7e10e6a1 for /usr/lib/systemd/system-generators/systemd-run-generator
extending hash d40c1835b0d1309dc94c093d52afec8edee72c99 for /usr/lib/systemd/system-generators/systemd-sysv-generator
extending hash 4e3dd53c3150d3189465254006f5193ae4ac865d for /usr/lib64/ld-2.32.so
extending hash 6c5efa1939301ff5d53a9b5a4d801ab6c1cc274b for /usr/lib/systemd/system-generators/systemd-getty-generator
extending hash 30f121a074d13860ac71c786c1d4ac6ef987e862 for /usr/lib/system
.......

**Comment by kkaarreell** [comment]
Hi @mengwangict , 
I do not have a straightforward procedure for you but maybe keylime-tests repo I am contributing to will provide you some hints.

Please take a look at https://github.com/RedHat-SP-Security/keylime-tests
Usually my procedure for the basic singlehost scenario is like this:
 - Execute https://github.com/RedHat-SP-Security/keylime-tests/blob/main/setup/configure_tpm_emulator/test.sh (may not be necessary if you have TPM already configured and functional)
 - Execute https://github.com/RedHat-SP-Security/keylime-tests/blob/main/setup/install_upstream_keylime/test.sh to download and install keylime bits
 - Execute test doing basic attestation on localhost - https://github.com/RedHat-SP-Security/keylime-tests/blob/main/functional/basic-attestation-on-localhost/test.sh

Also, please note that  I am using some custom bash functions, these either come from beakerlib package or from this file https://github.com/RedHat-SP-Security/keylime-tests/blob/main/Library/test-helpers/lib.sh

If nothing else it can at least give you some understanding about the order of required (setup) actions.

**Comment by mengwangict** [comment]
The problem resolved. This can be close. Thanks for  all the help

**Comment by THS-on** [comment]
:+1: If you have any further questions either just open a new issue or join `#keylime` on the [CNCF Slack](https://slack.cncf.io/).
