### ISSUE TITLE
verifier ends with Traceback after receiving SIGINT

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#841]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora35
 * Processor architecture: x86_64
 * TPM Manufacturer: virtual TPM
 * Keylime version: current latest upstream (f3fb006)

# Description 
This does not happen always but quite frequently (30-50%)

## Expected behavior vs. actual behavior 
verifier should terminate cleanly

## Steps to reproduce problem
1.  can be reproduced with CI tests (basic-attestation-on-localhost) with slight modification in Library/test-helpers/lib.sh
enabling failure (RET=2) when Traceback is found in the service log.
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/Library/test-helpers/lib.sh#L306
-----
- #RET=2
+ RET=2
-----

# Relevant logs

2022-01-18 07:31:11.609 - keylime.cloudverifier_common - WARNING - Non-fatal problem ocurred while attempting to evaluate agent attribute "mb_refstate" (('malformed node or string: <ast.Name object at 0x7f3bcd006040>',)). Will just consider the value of this attribute to be "None"
2022-01-18 07:31:21.342 - keylime.revocation_notifier - INFO - Stopping revocation notifier...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/revocation_notifier.py", line 42, in worker
    zmq.device(zmq.FORWARDER, frontend, backend)
  File "zmq/backend/cython/_device.pyx", line 54, in zmq.backend.cython._device.device
  File "zmq/backend/cython/_device.pyx", line 95, in zmq.backend.cython._device.proxy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/cloud_verifier_tornado.py", line 1016, in <lambda>
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/revocation_notifier.py", line 44, in worker
    context.destroy()
  File "/usr/lib64/python3.9/site-packages/zmq/sugar/context.py", line 215, in destroy
    self.term()
  File "/usr/lib64/python3.9/site-packages/zmq/sugar/context.py", line 165, in term
    return super(Context, self).term()
  File "zmq/backend/cython/context.pyx", line 82, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt

**Comment by THS-on** [comment]
Are your first sending a SIGINT and then a SIGTERM?
For me it looks like that during shutdown it tries to handle do both and then fails because of that.
`device.destroy()` does block until all sockets are closed, so maybe the interval between those two signals is too short.

If this is not the case we can also probably drop the `device.destroy()` and let the garbage collection do the cleanup.

**Comment by kkaarreell** [comment]
I do not recall if this was the case. I will give it another try and report back.

**Comment by kkaarreell** [comment]
I am sorry for the confusion. I have tested it again and this traceback appears after receiving SIGINT (only).
Currently it can be visible in test results for
https://github.com/RedHat-SP-Security/keylime-tests/pull/33

**Comment by THS-on** [comment]
I can reproduce this on my system. There is probably something with how signal handlers work in Python and the process for the revocation notifier.

**Comment by kkaarreell** [comment]
@THS-on I cannot reproduce it anymore even with the current upstream. I think we can close this one.

I have tested also code from PR#889 and it also worked well in the descrived (SIGINT) scenario.

**Comment by ansasaki** [comment]
@THS-on Hello, should this be closed via #889?

**Comment by THS-on** [comment]
@ansasaki yes.

**Comment by THS-on** [comment]
@kkaarreell can you close this issue?

**Comment by kkaarreell** [comment]
This is now fixed.
