### ISSUE TITLE
registrar db code seems to be mixing str and bytes

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#863]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: CentOS Stream 9
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current latest upstream (15663f0)

# Description 
While working on a e2e test for keylime using postgresql I have encountered a failure when keylime agent starts.
In the registrar log there were failures like
```
2022-01-28 10:01:04.551 - keylime.registrar - ERROR - SQLAlchemy Error: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(45)

[SQL: INSERT INTO registrarmain (agent_id, key, aik_tpm, ekcert, ek_tpm, mtls_cert, virtual, ip, port, active, provider_keys, regcount) VALUES (%(agent_id)s, %(key)s, %(aik_tpm)s, %(ekcert)s, %(ek_tpm)s, %(mtls_cert)s, %(virtual)s, %(ip)s, %(port)s, %(active)s, %(provider_keys)s, %(regcount)s)]
[parameters: {'agent_id': 'd432fbb3-d2f1-4a97-9ef7-75bd81c00000', 'key': b'OXY5YXhWaTl5VUJNenh0cEZJdjdyZ2tlSXo3N2JFdjk=', 'aik_tpm': 'ARgAAQALAAUAcgAAABAAFAAECAAAAAAAAQDXsn0xvMJMRd66oR2oSAjE8E4tPruODm9451LBl57QuaSaG4neegj2yv+u+Cceb19FZjj/MzuItSGAw5jukPUfAQJP26mZevi4dbpcmhKLt49f/fgma ... (78 characters truncated) ... jvp9kJZG+NMufZrbo1K1pQckbxEAajCFnk0DpcCKwndCpnHRAvpePmLpMuMBYI2P2pN/QelLknakkkNUHyyqCpxJFxc5YNSshdaxM87VRZci3JCQQ7Ok2X1A+1pHgayZbJEYO4w68xnieJGb/jmV9', 'ekcert': 'MIID9DCCAlygAwIBAgIBODANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDEw1zd3RwbS1sb2NhbGNhMCAXDTIyMDEyODE1MDA0N1oYDzk5OTkxMjMxMjM1OTU5WjASMRAwDgYDVQQDEwd1bmtub3duM ... (1058 characters truncated) ... aQBXK0XAGp2IY5RPrICd9Mhx1gd7vPV8y271if/oKc7V6Rg18TumhVVit6998XgPa6MhVclJQtaNOcyyf2sOoYAeZroe6oeje0u7gUdFc67euJZ8k+pntIVMwk3vLcWMMb9xdPUHrioctsA588bs=', 'ek_tpm': b'AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEA7N/V8dKnXkl4Q85QYk5U+R8VY5s/kcl7jDl1tTi3IJ5SOW3YXCORBMgyuNkZg+levx6n ... (127 characters truncated) ... 4/+oPC52xe4s6JnyTU8Xc+54rMucLsIE0Ll+l1uRFwUZ9c8/b/HnDzo9D/VfgihL+W/cK4dpICEW6VvdxiOvFj5mTduyO8I9TrPQsy9uSujw+Ney9uQLygotqf6c2K81nE7RHozYS4i7Pb5ptNw==', 'mtls_cert': '-----BEGIN CERTIFICATE-----\nMIIC6jCCAdKgAwIBAgIUQgi7UNbyAmDRZdyeoehkfL/RmRIwDQYJKoZIhvcNAQEL\nBQAwLzEtMCsGA1UEAwwkZDQzMmZiYjMtZDJmMS00YTk3LTllZjctNz ... (790 characters truncated) ... yVp4GTEqihZn\nUdRcwvG9s1pAcd2DQn8/7EcKFQuO/9XTWKoz4WjqvMNEw5SR1vQuVyPHLBCkOyFm\nehM0xC1OZlVfyCOp4IHlcqqSsmGJGI7tgYsi5Wpj\n-----END CERTIFICATE-----\n', 'virtual': 0, 'ip': '127.0.0.1', 'port': 9002, 'active': 0, 'provider_keys': '{}', 'regcount': 1}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2022-01-28 10:01:04.553 - keylime.registrar - WARNING - POST for d432fbb3-d2f1-4a97-9ef7-75bd81c00000 returning 400 response. Error: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(45)

```
After changing the respective value in keylime/migrations/versions/8a44a4364f5a_initial_database_migration.py to `180` similar error appeared:
```
[SQL: INSERT INTO registrarmain (agent_id, key, aik_tpm, ekcert, ek_tpm, mtls_cert, virtual, ip, port, active, provider_keys, regcount) VALUES (%(agent_id)s, %(key)s, %(aik_tpm)s, %(ekcert)s, %(ek_tpm)s, %(mtls_cert)s, %(virtual)s, %(ip)s, %(port)s, %(active)s, %(provider_keys)s, %(regcount)s)]
[parameters: {'agent_id': 'd432fbb3-d2f1-4a97-9ef7-75bd81c00000', 'key': b'UUg0RzQ5NVlBcFRLRGx0d2tVUDIyNzNlMVJwa0V1U08=', 'aik_tpm': 'ARgAAQALAAUAcgAAABAAFAAECAAAAAAAAQCmY3S6CvQkzfnSN9kT6GVl2aWCldyK+d4ds/Vg+ZkKt5nmV9oK/6fGxfhXmCdu8VrP/mi7ODOP1V3YJbLio1l6wMrjCzqWqCHd4+c9cbBZZVEF6+S5I ... (78 characters truncated) ... uZ3sPkKqj8fgufQB+aBWC/LVEN+AwnEYMGKvkg3ghBQZzFNtj/ov/UNUoBMyJ0C5fnG2zdn6pwXR6Oz/9yVaQOHqpkmVVtZkZOBjxsGSg+V/mGqCAIAvQ2GU3nFclUI0WwVMx5mh8oDCSVl0LncRj', 'ekcert': 'MIID9DCCAlygAwIBAgIBMjANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDEw1zd3RwbS1sb2NhbGNhMCAXDTIyMDEyODE0NTM1MVoYDzk5OTkxMjMxMjM1OTU5WjASMRAwDgYDVQQDEwd1bmtub3duM ... (1058 characters truncated) ... qQo1Id1tCh5h2Bq6MLp8mX3u9qASxRbBtiyGyNz5dfOP06sHwIlcXev03EQ9Vkaps303OmIF5CqdhiE2rSFwWUC4uw4L6noMEB863sdCHIE8qrjGi6vTc9YKDpfm/uIewHMfEp4wu30mijhZfl4o=', 'ek_tpm': b'AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEA0VwBN5+ms/rk+/24NyjAtdv/agylqoFi7x63FnCD1pD5dkDBXC1v5Lj6ofJOK2bCJQB8 ... (127 characters truncated) ... LtDokIyeDlOE4NhkB9aAgoEnSlqhBOv6bkJzds1K9JMD970KO7EmOJHmb0Qp4n6EQDkNUd15LiAj7Rar9atbtdL9hdrb1WsSaQRdTU/G4IlODQg0c7BiPvUyTV45PjDDaUpoc+Rl25eboft3ggQ==', 'mtls_cert': '-----BEGIN CERTIFICATE-----\nMIIC6jCCAdKgAwIBAgIUQgi7UNbyAmDRZdyeoehkfL/RmRIwDQYJKoZIhvcNAQEL\nBQAwLzEtMCsGA1UEAwwkZDQzMmZiYjMtZDJmMS00YTk3LTllZjctNz ... (790 characters truncated) ... yVp4GTEqihZn\nUdRcwvG9s1pAcd2DQn8/7EcKFQuO/9XTWKoz4WjqvMNEw5SR1vQuVyPHLBCkOyFm\nehM0xC1OZlVfyCOp4IHlcqqSsmGJGI7tgYsi5Wpj\n-----END CERTIFICATE-----\n', 'virtual': 0, 'ip': '127.0.0.1', 'port': 9002, 'active': 0, 'provider_keys': '{}', 'regcount': 1}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
2022-01-28 09:54:09.033 - keylime.registrar - WARNING - POST for d432fbb3-d2f1-4a97-9ef7-75bd81c00000 returning 400 response. Error: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(500)
```
I have replaced lengths of 500 to 1500 and then I ended up with the following error:
```
2022-01-28 09:56:45.315 - keylime.registrar - WARNING - PUT for d432fbb3-d2f1-4a97-9ef7-75bd81c00000 returning 400 response. Error: key: expected bytes or bytearray, but got 'str'
2022-01-28 09:56:45.315 - keylime.registrar - ERROR - key: expected bytes or bytearray, but got 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/registrar_common.py", line 479, in do_PUT
    ex_mac = crypto.do_hmac(agent.key, agent_id)
  File "/usr/local/lib/python3.9/site-packages/keylime-0.0.0-py3.9.egg/keylime/crypto.py", line 153, in do_hmac
    h = hmac.new(key, msg=None, digestmod=hashlib.sha384)
  File "/usr/lib64/python3.9/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib64/python3.9/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```
This makes me believe that database fields do not have enough size since the code is mixing strings and bytes.

## Expected behavior vs. actual behavior 
registrar should started without an error.

## Steps to reproduce problem
1. Please see /functional/db-postgresql-sanity-on-localhost from keylime-tests repository
currently available in
https://github.com/RedHat-SP-Security/keylime-tests/pull/43

# Relevant logs
I can provide additional logs on demain. Eventually, on Fedora systems the test can be easily executed using the `tmt` tool following
https://github.com/RedHat-SP-Security/keylime-tests/blob/main/TESTING.md#running-tests-in-a-virtual-system-using-tmt

**Comment by kkaarreell** [comment]
Also, later in the test following traceback appears. There should be probably some test first if data exists.
```
:: [ 10:40:55 ] :: [  BEGIN   ] :: Running 'lime_keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist allowlist.txt --exclude excludelist.txt -f /etc/hostname -c add'
Reading configuration from ['/etc/keylime.conf']
2022-01-28 10:40:55.969 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-01-28 10:40:55.971 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-01-28 10:40:55.972 - keylime.registrar_client - WARNING - TLS is enabled.
2022-01-28 10:40:55.972 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-01-28 10:40:56.001 - keylime.registrar_client - CRITICAL - Error: unexpected http response code from Registrar Server: 404
2022-01-28 10:40:56.002 - keylime.registrar_client - CRITICAL - Response code 404: agent_id not found
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_tenant')())
  File "/usr/local/lib/python3.10/site-packages/keylime-0.0.0-py3.10.egg/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.10/site-packages/keylime-0.0.0-py3.10.egg/keylime/tenant.py", line 1412, in main
    mytenant.init_add(vars(args))
  File "/usr/local/lib/python3.10/site-packages/keylime-0.0.0-py3.10.egg/keylime/tenant.py", line 298, in init_add
    if self.registrar_data.get("mtls_cert", None) is None:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by kkaarreell** [comment]
Looking into registrar_common.py , the dictionary `d` stored into the db contain following types:
```
Key agent_id has type <class 'str'>
Key ek_tpm has type <class 'bytes'>
Key aik_tpm has type <class 'str'>
Key ekcert has type <class 'str'>
Key ip has type <class 'str'>
Key mtls_cert has type <class 'str'>
Key port has type <class 'int'>
Key virtual has type <class 'int'>
Key active has type <class 'int'>
Key key has type <class 'bytes'>
Key provider_keys has type <class 'dict'>
Key regcount has type <class 'int'>
```

**Comment by kkaarreell** [comment]
I made my tests to work with the following changes.
https://github.com/kkaarreell/keylime/commit/086d91eb603b750dfbe0e0ecf9a482a9c841fa45
But I don't know if they are correct and especially whether `ek_tpm.decode('UTF-8')` won't break something in the code as I am not reverse the conversion anywhere in the code.

**Comment by kkaarreell** [comment]
I have updated
https://github.com/RedHat-SP-Security/keylime-tests/pull/43
adding a similar test using mariadb (mysql fork) instead of postgresql and there is a failure in a verifier.
```
2022-01-31 09:59:29.510 - keylime.tenant - ERROR - Response code 400: Exception error: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'allowlist' at row 1")
[SQL: INSERT INTO verifiermain (agent_id, v, ip, verifier_id, verifier_ip, verifier_port, port, operational_state, public_key, tpm_policy, vtpm_policy, meta_data, allowlist, ima_sign_verification_keys, mb_refstate, revocation_key, accept_tpm_hash_algs, accept_tpm_encryption_algs, accept_tpm_signing_algs, hash_alg, enc_alg, sign_alg, boottime, ima_pcrs, pcr10, next_ima_ml_entry, severity_level, last_event_id, learned_ima_keyrings, supported_version, ak_tpm, mtls_cert) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
...
...
(Background on this error at: https://sqlalche.me/e/14/9h9h)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'allowlist' at row 1")

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/keylime-0.0.0-py3.10.egg/keylime/cloud_verifier_tornado.py", line 503, in post
    raise e
  File "/usr/local/lib/python3.10/site-packages/keylime-0.0.0-py3.10.egg/keylime/cloud_verifier_tornado.py", line 500, in post
    session.commit()
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3502, in _flush
    with util.safe_reraise():
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/lib64/python3.10/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
```
My allowlist is definitely not big, the input file has just 476807 bytes
```
-rw-r--r--. 1 root root 476807 Jan 31 09:59 allowlist.txt
```
while verifier_db defines it as
```
allowlist = Column(Text().with_variant(Text(429400000), "mysql"))
```

**Comment by THS-on** [comment]
> I made my tests to work with the following changes.
kkaarreell@086d91e
But I don't know if they are correct and especially whether ek_tpm.decode('UTF-8') won't break something in the code as I do not reverse the conversion anywhere in the code.

Thanks for taking a look at it.  I'll make a PR ensures those type conversions.


For the mysql issue: can you check on the mysql side what the properties of the columns are?

**Comment by kkaarreell** [comment]
Hi @THS-on , I think I have a fix for the mysql issue. I have just pushed an update to my fork
https://github.com/keylime/keylime/compare/master...kkaarreell:db_fix

**Comment by kkaarreell** [comment]
PR for the mysql issue is https://github.com/keylime/keylime/pull/865

**Comment by kkaarreell** [comment]
MySQL/MariaDB issue has been addressed with https://github.com/keylime/keylime/commit/7a43084cb64137d2ae9eda88ce21afe94750df97
IMHO this issue can be closed as resolved.
