### ISSUE TITLE
Issue running "keylime_tenant -h"

### ISSUE THREAD

**Issue by Praneshss** [keylime/keylime#901]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: 
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: 

# Description 

## Steps to reproduce problem
1. Python3_8) ps@PS:~$ keylime_tenant -h
Reading configuration from []
Traceback (most recent call last):
  File "/home/ps/Python3_8/bin/keylime_tenant", line 5, in <module>
    from keylime.cmd.tenant import main
  File "/home/ps/Python3_8/lib/python3.8/site-packages/keylime/cmd/tenant.py", line 8, in <module>
    from keylime import keylime_logging
  File "/home/ps/Python3_8/lib/python3.8/site-packages/keylime/keylime_logging.py", line 22, in <module>
    logging.config.fileConfig(config.get_config())
  File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
@Praneshss which version of Keylime are you using?

The tenant requires to read the `keylime.conf` normally located under `/etc/keylime.conf`. If you used the installer.sh script this file is only readable as root.

**Comment by Praneshss** [comment]
Keylime version is 6.3.1 Yes, I have used the installer.sh to install it. So, what should I do now? Should I run as root? or any other way?

**Comment by Praneshss** [comment]
Problem Solved with chmod +r /etc/keylime.conf

**Comment by THS-on** [comment]
Changing the `keylime.conf` to be world readable is not a good idea because it can contain passwords. A better way is to create a new group that can read that file and add your user to it, if you don't want to run keylime_tenant as root.

**Comment by Praneshss** [comment]
Okay, Now running from root. Previous error has gone, but I got this new one.
(Python3_8) root@PS:/home/Ps/keylime# keylime_agent -h
Reading configuration from ['/etc/keylime.conf']
2022-02-28 14:26:05.283 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 14:26:05.314 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 14:26:05.323 - keylime.tpm - INFO - Taking ownership with config provided TPM owner password
2022-02-28 14:26:06.182 - keylime.tpm - INFO - TPM Owner password confirmed: keylime
2022-02-28 14:26:06.183 - keylime.tpm - INFO - Flushing old ek handle: 0x*********
2022-02-28 14:26:07.392 - keylime.tpm - INFO - Flushing old ak handle: /var/lib/keylime/secure/tmpgejswgaw
2022-02-28 14:26:08.637 - keylime.cloudagent - INFO - Agent UUID: d**************************************
2022-02-28 14:26:08.639 - keylime.cloudagent - INFO - Using existing key in /var/lib/keylime/secure/tci_rsa_key
2022-02-28 14:26:08.652 - keylime.cloudagent - INFO - Using existing mTLS cert in /var/lib/keylime/secure/tci_mtls_cert
Traceback (most recent call last):
  File "/home/psantikellur/Python3_8/bin/keylime_agent", line 8, in <module>
    sys.exit(main())
  File "/home/psantikellur/Python3_8/lib/python3.8/site-packages/keylime/cmd/agent.py", line 15, in main
    keylime_agent.main()
  File "/home/psantikellur/Python3_8/lib/python3.8/site-packages/keylime/keylime_agent.py", line 727, in main
    context = web_util.generate_mtls_context(server.mtls_cert_path, server.rsakey_path, keylime_ca, logger=logger)
  File "/home/psantikellur/Python3_8/lib/python3.8/site-packages/keylime/web_util.py", line 110, in generate_mtls_context
    context.load_verify_locations(cafile=ca_path)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by THS-on** [comment]
The agent, verifier and registrar have no `-h` option, they only use the `keylime.conf`.  The agent also requires a certificate of the Keylime CA (https://keylime-docs.readthedocs.io/en/latest/rest_apis.html#agent-keylime-ca) which is by default generated by the verifier.

If you are running all components on the same device start them in the following order:
1. keylime_verifier: generates all the required certificates
2. keylime_registrar: is required by the agent
3. keylime_agent

**Comment by Praneshss** [comment]
Okay, Thank you. Yes, I'm running all of them on the same device. running the `keylime_verifier `seems to take indefinite time. It has been stuck at the below point for more than 10 minutes.
```
root@PS:/home/ps/keylime# keylime_verifier 
Reading configuration from ['/etc/keylime.conf']
2022-02-28 14:50:22.128 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 14:50:22.188 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 14:50:22.189 - alembic.env - INFO - Migrating database cloud_verifier
2022-02-28 14:50:22.189 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2022-02-28 14:50:22.189 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - Current API version 2.0
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - Supported older API versions: 1.0
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - Setting up TLS...
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - Generating a new CA in /var/lib/keylime/cv_ca and a client certificate for connecting
2022-02-28 14:50:22.200 - keylime.cloudverifier - INFO - use keylime_ca -d /var/lib/keylime/cv_ca to manage this CA
2022-02-28 14:50:22.200 - keylime.cloudverifier - WARNING - CAUTION: using default password for CA, please set private_key_pw to a strong password


```

**Comment by THS-on** [comment]
This is expected. They are all long running services, that do not go into the background.

**Comment by Praneshss** [comment]
Okay, Thank you. I got it. But running parallelly `keylime_registrar` is giving following error. Please note that my `keylime_verifier` is still on.
```
root@PS:/home/ps/keylime# keylime_registrar 
Reading configuration from ['/etc/keylime.conf']
2022-02-28 15:01:15.228 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 15:01:15.291 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 15:01:15.292 - alembic.env - INFO - Migrating database registrar
2022-02-28 15:01:15.292 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2022-02-28 15:01:15.292 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2022-02-28 15:01:15.300 - keylime.registrar - INFO - Setting up TLS...
Traceback (most recent call last):
  File "/usr/local/bin/keylime_registrar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/registrar.py", line 21, in main
    registrar_common.start(
  File "/usr/local/lib/python3.8/dist-packages/keylime/registrar_common.py", line 538, in start
    context, _ = web_util.init_mtls(section='registrar', generatedir='reg_ca', logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/keylime/web_util.py", line 67, in init_mtls
    raise Exception(
Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first
```

**Comment by THS-on** [comment]
Ok that is strange. Can you list the content of `/var/lib/keylime` and its sub directories?

**Comment by Praneshss** [comment]
Here, it is:
```
root@PS:/home/ps# tree /var/lib/keylime/
/var/lib/keylime/
├── ca
├── cv_ca
├── cv_data.sqlite
├── reg_data.sqlite
├── secure
│   ├── tci_mtls_cert
│   ├── tci_rsa_key
│   └── tmpa5_3mf9r
├── tpm_cert_store
│   ├── GS_TPM_RT.pem
│   ├── IFX15.pem
│   ├── IFX1.pem
│   ├── IFX2.pem
│   ├── IFX3.pem
│   ├── IFX4.pem
│   ├── IFX5.pem
│   ├── IFX8.pem
│   ├── IFX_ECC_034.pem
│   ├── IFX_RSA_01I.pem
│   ├── IFX_RSA_02I.pem
│   ├── IFX_RSA_034.pem
│   ├── IFX_RSA_03I.pem
│   ├── IFX_RSA_04I.pem
│   ├── IFX_RSA_05I.pem
│   ├── IFX_RSA_08I.pem
│   ├── IFX_RSA_17I.pem
│   ├── IFX_RSA_18I.pem
│   ├── IFX_RSA_20I.pem
│   ├── IFX_RSA_21I.pem
│   ├── IFX_RSA_RT.pem
│   ├── INF_ECC_010I.pem
│   ├── INF_ECC_010RT.pem
│   ├── INF_ECC_011.pem
│   ├── INF_RSA_010I.pem
│   ├── INF_RSA_010RT.pem
│   ├── INF_RSA_011.pem
│   ├── INF_RSA_022.pem
│   ├── INTEL_I.pem
│   ├── INTEL_RT.pem
│   ├── NTC1.pem
│   ├── NTC2.pem
│   ├── NUVO_0100.pem
│   ├── NUVO_1110.pem
│   ├── NUVO_1111.pem
│   ├── NUVO_2110.pem
│   ├── NUVO_2111.pem
│   ├── STM_ECC_01I.pem
│   ├── STM_ECC_01RT.pem
│   ├── STM_RSA_01I.pem
│   ├── STM_RSA_02I.pem
│   ├── STM_RSA_03I.pem
│   ├── STM_RSA_04I.pem
│   ├── STM_RSA_05I.pem
│   ├── STM_RSA_06I.pem
│   ├── STM_RSA_07I.pem
│   └── STM_RSA_RT.pem
└── tpmdata.yml

4 directories, 53 files

```

**Comment by THS-on** [comment]
Try deleting the cv_ca folder and `cv_data.sqlite` and restart the verifier. The cv_ca folder should contain multiple certificates.

**Comment by Praneshss** [comment]
It didn't help much. The problem persists. I see that no keys are generated inside the CV_CA folder.

**Comment by Praneshss** [comment]
I'm running on Ubuntu 20.04.3 LTS with Python3.8. I have virtualbox installed with no images running in it.

**Comment by Praneshss** [comment]
Now, after more than 30 min, I got the debug prints from the terminal running  `keylime_verifier`. 
```
2022-02-28 16:10:05.687 - keylime.ca-util - INFO - CA certificate created successfully in /var/lib/keylime/cv_ca
2022-02-28 16:10:06.163 - keylime.ca-util - INFO - Created certificate for name TII-PSANTIKELLUR1 successfully in /var/lib/keylime/cv_ca
```
`keylime_registrar` seems to work fine now.

**Comment by Praneshss** [comment]
Now, after more than 10 min, I got the debug prints from the terminal running `keylime_verifier`.

2022-02-28 16:10:05.687 - keylime.ca-util - INFO - CA certificate created successfully in /var/lib/keylime/cv_ca
2022-02-28 16:10:06.163 - keylime.ca-util - INFO - Created certificate for name PS successfully in /var/lib/keylime/cv_ca

keylime_registrar seems to work fine now.

**Comment by THS-on** [comment]
Ok then the entropy pool for the VM might very low or it has not much CPU resources to generate the certificates.

**Comment by Praneshss** [comment]
Does this mean I got the key_agent attestation fine?
```
(Python3_8) root@TII-PSANTIKELLUR1:/home/ps/keylime# keylime_agent  -u d****-****-****-***** -c add -t 127.0.0.1 -v 127.0.0.1 -f test-requirements.txt 
Reading configuration from ['/etc/keylime.conf']
2022-02-28 16:17:59.224 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 16:17:59.256 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 16:17:59.265 - keylime.tpm - INFO - Taking ownership with config provided TPM owner password
2022-02-28 16:18:00.143 - keylime.tpm - INFO - TPM Owner password confirmed: keylime
2022-02-28 16:18:00.143 - keylime.tpm - INFO - Flushing old ek handle: 0x*******
2022-02-28 16:18:01.388 - keylime.tpm - INFO - Flushing old ak handle: /var/lib/keylime/secure/tmp49v3m1p9
2022-02-28 16:18:02.712 - keylime.cloudagent - INFO - Agent UUID: d****-****-****-***** 
2022-02-28 16:18:02.715 - keylime.cloudagent - INFO - Using existing key in /var/lib/keylime/secure/tci_rsa_key
2022-02-28 16:18:02.754 - keylime.cloudagent - INFO - Using existing mTLS cert in /var/lib/keylime/secure/tci_mtls_cert
2022-02-28 16:18:03.000 - keylime.registrar_client - INFO - Agent registration requested for d****-****-****-***** 
2022-02-28 16:18:04.146 - keylime.tpm - INFO - AIK activated.
2022-02-28 16:18:04.165 - keylime.registrar_client - INFO - Registration activated for agent d****-****-****-***** .
2022-02-28 16:18:04.171 - keylime.cloudagent - INFO - Starting Cloud Agent on 127.0.0.1:9002 with API version 2.0. Use <Ctrl-C> to stop
2022-02-28 16:18:04.177 - keylime.revocation_notifier - INFO - Waiting for revocation messages on 0mq 127.0.0.1:8992

```
From the terminal of registrar:
```

root@PS:/home/ps/keylime# keylime_registrar 
Reading configuration from ['/etc/keylime.conf']
2022-02-28 16:11:14.766 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 16:11:14.830 - keylime.keylime_db - INFO - database_url is not set, using multi-parameter database configuration options
2022-02-28 16:11:14.830 - alembic.env - INFO - Migrating database registrar
2022-02-28 16:11:14.831 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2022-02-28 16:11:14.831 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2022-02-28 16:11:14.839 - keylime.registrar - INFO - Setting up TLS...
2022-02-28 16:11:14.839 - keylime.registrar - INFO - Starting Cloud Registrar Server on ports 8890 and 8891 (TLS) use <Ctrl-C> to stop
2022-02-28 16:11:14.839 - keylime.registrar - INFO - Current API version 2.0
2022-02-28 16:11:14.839 - keylime.registrar - INFO - Supported older API versions: 1.0
2022-02-28 16:16:42.526 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 16:16:42.637 - keylime.tpm - INFO - Encrypting AIK for UUID d****-****-****-***** 
2022-02-28 16:16:42.644 - keylime.registrar - INFO - POST returning key blob for agent_id: d****-****-****-***** 
2022-02-28 16:16:43.833 - keylime.registrar - INFO - PUT activated: d****-****-****-***** 
2022-02-28 16:18:02.835 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-02-28 16:18:02.980 - keylime.tpm - INFO - Encrypting AIK for UUID d****-****-****-***** 
2022-02-28 16:18:02.992 - keylime.registrar - INFO - Overwriting previous registration for this UUID.
2022-02-28 16:18:02.999 - keylime.registrar - INFO - POST returning key blob for agent_id: d****-****-****-***** 
2022-02-28 16:18:04.164 - keylime.registrar - INFO - PUT activated: d****-****-****-***** 
```
But I have no prints from verifier side.

**Comment by THS-on** [comment]
You now have setup all the basic components, but not added the agent to attestation.
On how to do that refer either to the README (https://github.com/keylime/keylime#running-keylime) or the Keylime documentation (https://keylime-docs.readthedocs.io/en/latest/)

**Comment by Praneshss** [comment]
Thank you @THS-on . When I run `keylime_verifier` on an Ubuntu guest image in Virtual Box, the keys don't appear in the `cv_ca` folder even after half an hour. is it a different problem? or related to computational constraints of virtual image for key generation? How can I tell if it is only stuck at the generation of the keys?

**Comment by THS-on** [comment]
Can you enable DEBUG logging in the `keylime.conf` and post the output the `keylime_verifier` here?
Also what kind of resources did you give the VM (memory, CPU, etc.)?

If it is an entropy problem you can check the current available entropy with:
```
cat /proc/sys/kernel/random/entropy_avail
```

If it is below 1000 you can use something like `haveged` to add more, but this might degrade the quality of the entropy, so use it ideally only for testing.

**Comment by THS-on** [comment]
@Praneshss did you get Keylime running and can this be closed or do you require further assistance?

**Comment by THS-on** [comment]
:+1: If you have any further questions either just open a new issue or join `#keylime` on the [CNCF Slack](https://slack.cncf.io/).
