### ISSUE TITLE
keylime_tenant -c deleteallowlist produce json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#924]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: F35
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current latest upstream ffe2b77

# Description 

allowlist is deleted but requests.exceptions.JSONDecodeError is raised.

```
# cat allowlist.txt 
0000000000000000000000000000000000000000000000000000000000000001  boot_aggregate
# keylime_tenant -c addallowlist -v 127.0.0.1 --allowlist allowlist.txt --allowlist-name mylist
Reading configuration from ['/etc/keylime.conf']
2022-03-16 08:08:55.204 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-03-16 08:08:55.206 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 08:08:55.207 - keylime.tenant - WARNING - Using default UUID d432fbb3-d2f1-4a97-9ef7-75bd81c00000
2022-03-16 08:08:55.207 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2022-03-16 08:08:55.207 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
{'code': 201, 'status': 'Created', 'results': {}}
# keylime_tenant -c showallowlist -v 127.0.0.1 --allowlist-name mylist
Reading configuration from ['/etc/keylime.conf']
2022-03-16 08:09:09.391 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-03-16 08:09:09.407 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 08:09:09.411 - keylime.tenant - WARNING - Using default UUID d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Show allowlist command response: 200.
{'code': 200, 'status': 'Success', 'results': {'name': 'mylist', 'tpm_policy': '{"22": ["0000000000000000000000000000000000000001", "0000000000000000000000000000000000000000000000000000000000000001", "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001", "ffffffffffffffffffffffffffffffffffffffff", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], "15": ["0000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000000", "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"], "mask": "0x408400"}', 'vtpm_policy': '{"23": ["ffffffffffffffffffffffffffffffffffffffff", "0000000000000000000000000000000000000000"], "15": ["0000000000000000000000000000000000000000"], "mask": "0x808000"}', 'ima_policy': None}}
# 
# keylime_tenant -c deleteallowlist -v 127.0.0.1 --allowlist-name mylist
Reading configuration from ['/etc/keylime.conf']
2022-03-16 08:09:18.721 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-03-16 08:09:18.724 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 08:09:18.724 - keylime.tenant - WARNING - Using default UUID d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 33, in <module>
    sys.exit(load_entry_point('keylime==6.3.1', 'console_scripts', 'keylime_tenant')())
  File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/tenant.py", line 1456, in main
    mytenant.do_delete_allowlist(args.allowlist_name)
  File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/tenant.py", line 1193, in do_delete_allowlist
    print(response.json())
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
# 
# keylime_tenant -c showallowlist -v 127.0.0.1 --allowlist-name mylist
Reading configuration from ['/etc/keylime.conf']
2022-03-16 08:09:22.053 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-03-16 08:09:22.055 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 08:09:22.056 - keylime.tenant - WARNING - Using default UUID d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Show allowlist command response: 404.
{'code': 404, 'status': 'Allowlist mylist not found', 'results': {}}

```
## Expected behavior vs. actual behavior
Command should end with success (200)

**Comment by THS-on** [comment]
@kkaarreell can you check if this still happens?

**Comment by kkaarreell** [comment]
@THS-on No, I do not see this failure in recent test logs. I believe we can close it.
