### ISSUE TITLE
about tpm_tenent add question

### ISSUE THREAD

**Issue by wahahaha123** [keylime/keylime#925]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version:  20.04.1
 * Processor architecture: 
 * TPM Manufacturer: ibmtpm tpm2-tools:4.0
 * Keylime version: 6.3

# Description 
When I use keylime_tenent to add a node, when checking_quote, it will prompt yaml.scanner.ScannerError: while scanning a simple key error

## Steps to reproduce problem
1. sudo keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f exclude.txt --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist list.txt --exclude exclude.txt

Reading configuration from ['/etc/keylime.conf']
2022-03-16 20:16:12.036 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.0
2022-03-16 20:16:12.037 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 20:16:12.037 - keylime.registrar_client - WARNING - TLS is enabled.
2022-03-16 20:16:12.037 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 20:16:12.052 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2022-03-16 20:16:12.052 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2022-03-16 20:16:12.054 - keylime.ima - WARNING - No boot_aggregate value found in allowlist, adding an empty one
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
<Response [200]>
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 20:16:12.212 - keylime.tenant - INFO - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1419, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1108, in do_quote
    raise e
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1058, in do_quote
    if not self.validate_tpm_quote(public_key, quote, algorithms.Hash(hash_alg)):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 548, in validate_tpm_quote
    failure = self.tpm_instance.check_quote(AgentAttestState(self.agent_uuid), self.nonce, public_key, quote,
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 1183, in check_quote
    jsonout = config.yaml_to_dict(retout, logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/keylime/config.py", line 172, in yaml_to_dict
    return yaml.load(sep.join(arry), Loader=SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 9, column 1
could not find expected ':'
  in "<unicode string>", line 10, column 1

What can I do to fix this problem
what should I do 
# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by THS-on** [comment]
How have you installed Keylime? are you using the master branch or the 6.3.0/1 tag?

How did you setup the TPM?

Can you patch `/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py` to log the output where the yaml parsing fails and then post logs again?
```patch
diff --git a/keylime/tpm/tpm_main.py b/keylime/tpm/tpm_main.py
index df97a9e..d4480f5 100644
--- a/keylime/tpm/tpm_main.py
+++ b/keylime/tpm/tpm_main.py
@@ -1172,6 +1172,7 @@ class tpm(tpm_abstract.AbstractTPM):
             return failure
 
         pcrs = []
+        logger.info("CHECK_QUOTE output: %s", str(retout))
         jsonout = config.yaml_to_dict(retout, logger=logger)
         if jsonout is None:
             failure.add_event("quote_validation", {"message": "YAML parsing failed for quote validation using tpm2-tools.",
```

**Comment by wahahaha123** [comment]
I I installed it by` ./instal`l and started tpm by `systemctl start tpm-server`
This is the log output after my modification

```
sudo keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f exclude.txt --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist list.txt --exclude exclude.txt
Reading configuration from ['/etc/keylime.conf']
2022-03-16 20:41:47.357 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.0
2022-03-16 20:41:47.358 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 20:41:47.358 - keylime.registrar_client - WARNING - TLS is enabled.
2022-03-16 20:41:47.358 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 20:41:47.371 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2022-03-16 20:41:47.372 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2022-03-16 20:41:47.373 - keylime.ima - WARNING - No boot_aggregate value found in allowlist, adding an empty one
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
<Response [200]>
2022-03-16 20:41:47.604 - keylime.tpm - INFO - CHECK_QUOTE output: [b'pcrs:\n', b'  sha1:\n', b'    0 : 0x0000000000000000000000000000000000000000\n', b'    16: 0xA64A7E252186447BF78AA30CA7DCAD67DB9E0A81\n', b'196540524ad3e7bb9e19fa3f976270989de845aa68d9a452511c39ac4982d60f17dc78c2a26b513a743a156ae67aa028c7247726cd4b9e68c396c99af28f5f0b68fad7659c0a41eaa2a5492c9de657290f0bab3f6d10e17a2f1716e3154b44ec7a712c45817e9be20d4d590b7a4b454cfeb085ad4b60fb6cc95811028ec3907b8c3c130d563747b0af3784859a4446d12539cb5a173bf0205920259a4759597d27081e47ecce10ce518b545fab400185382ec326754359ac9ca593093a633f02d6e8a527147d7d2b61cb8c7cc1e17dafd1bd63fec3067fc1119125700354268f33afc572cb8ecdbf1f3c552935f573b02cbee8b0a8264687a792c820664688c3']
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 20:41:47.615 - keylime.tenant - INFO - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 stopped
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1419, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1108, in do_quote
    raise e
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1058, in do_quote
    if not self.validate_tpm_quote(public_key, quote, algorithms.Hash(hash_alg)):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 548, in validate_tpm_quote
    failure = self.tpm_instance.check_quote(AgentAttestState(self.agent_uuid), self.nonce, public_key, quote,
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 1185, in check_quote
    jsonout = config.yaml_to_dict(retout, logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/keylime/config.py", line 172, in yaml_to_dict
    return yaml.load(sep.join(arry), Loader=SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 9, column 1
could not find expected ':'
  in "<unicode string>", line 10, column 1
```

**Comment by THS-on** [comment]
Interesting the `sig:` prefix is gone missing. Can you try to install a newer version of tpm2-tools?

I currently have no test setup with tpm2-tools 4.0 installed, so reproducing this will take some time.

Can you generate a quote and validating it manually by running the following steps and post the output here?
```
tpm2_createek -c 0x81010001 -G rsa -u ekpub.pem -f pem

tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha256 \
              -u akpub.pem -f pem -n ak.name

tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha256 \
              -u akpub.pem -f pem -n ak.name

tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha256 \
              -u akpub.pem -f pem -n ak.name
```

**Comment by wahahaha123** [comment]
I installed the 5.2 version of tpm-tools before, but there was a problem when I createdek, and I couldn't find the ek handle, so I installed the lower version of tpm-tools.
When I execute tpm2_createeek manually, the same problem occurs. I don't know where this authorization value is set. The parameters in tpmdata.yml are like this
```
tpm2_createek -c 0x81010001 -p keylime -G rsa -u ekpub.pem -f pem
WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2) 
ERROR: Esys_CreatePrimary(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run tpm2_createek
```
```
aik_handle: /var/lib/keylime/secure/tmplvaa24u_
aik_pw: 9CkzChZSGdLJsWZYK5Np
aik_tpm: !!binary |
  QVJnQUFRQUxBQVVBY2dBQUFCQUFGQUFFQ0FBQUFBQUFBUUNiTmFxWDB5bGVhTTdiRW9mS3d0SUhG
  K3VHaytkM3hmR3VWZ0VCTHQwTm1KMkYwS1NpR3lBWGRWMndDT2ZjMndOZUt1RWI5cnU2dElXNG00
  SUZoY3lWYUc5K3owNXFzNnJ5UlIyOGVjYXZYSTlBSWJsR0lDWFdQNTlNYmpNLzJiUUNkaGozRE9t
  YlYyNFhBRjhxSllQajFxblpoM0YxVURacEIwR1Q3aXpMZ01SbXppa2hzTndqUEJobjVJRGw1OFFS
  YTN0NmttRWMzNk1TdHVqSjJkdlRpUVBrU0RZYjJMOXBGL2JpK25HczduczdmenJCMGdUQXg3SzRr
  VEE4WldZTnhKTGlkYmdycitiNVQxQWhoWWJzck9ORlNnNjJ6cVNyU0gwQlU4a3VEazVzRllxQnRu
  UkxpeFpzZ0J0MHMyRzUxU1Q0UzBGRDRNSDYydXlkbG9tVg==
ek_alg: rsa
ek_handle: 2164260864
ek_pw: Cl7tErdzJHqtWmxmCcEy
ek_tpm: !!binary |
  QVRvQUFRQUxBQU1Bc2dBZ2czR1haMFNFcy9nYWtNeU5ScVhYSlAxUzEyNEdVZ3RrOHFIYUd6TVVh
  YW9BQmdDQUFFTUFFQWdBQUFBQUFBRUFzMUVRaW1TOHpkTmhKVzZHZStheFNpaFBKaVVERnBvdG9q
  NlRpNFpQM2MyU0xLUEdBSFE1TVRMWFBjaVZ6RmMzd2RmdlV3Y2hwRDlqWXZUTlMrakJCV29DeUJs
  cXN5MXNhQWRHUVBXMmhuTDd2UzBBQVVicVg0Z1VMZUZ3WVBITUFYZmNQakhMWGFrbStwc21TaVZl
  bHY1ZUxsOTFKdG9pOHFYZ3JmeFhoYzQ2WGlTSmN1WnNSZkExNzkyWlV2aFZtZURvbHZCai81cnFW
  RkZVUGU1MEhYSmVrQUprd01ycXVFL1JjaGFGa0JjaUJxZExnSzVRekk3T0lPNzhkcEJtSE5KZnYv
  V2J6YTNTTjlGZEM3MVJKUit1NUJtcDdDMDVyZkxhRTdDbjh2TTBZUDNhNElmVEkxRlZ0K2s5TFdo
  VmFSbGhTVEpQZ001SUhraWtoN2ZrZFE9PQ==
owner_pw: keylime
```

**Comment by wahahaha123** [comment]
When I update tpm-tools to the latest version 5.2, this problem occurs when I execute keylime_tenent
```
sudo keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -f exclude.txt --uuid d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --allowlist list.txt --exclude exclude.txt
Reading configuration from ['/etc/keylime.conf']
2022-03-16 21:24:36.707 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-03-16 21:24:36.708 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-03-16 21:24:36.708 - keylime.registrar_client - WARNING - TLS is enabled.
2022-03-16 21:24:36.709 - keylime.registrar_client - INFO - Setting up client TLS...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 21:24:36.723 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2022-03-16 21:24:36.723 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2022-03-16 21:24:36.725 - keylime.ima - WARNING - No boot_aggregate value found in allowlist, adding an empty one
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
<Response [200]>
2022-03-16 21:24:36.913 - keylime.tpm - INFO - CHECK_QUOTE output: [b'pcrs:\n', b'  sha1:\n', b'    0 : 0x0000000000000000000000000000000000000000\n', b'    16: 0x5E38D632DD904F0061855866BB9553D166EA0C06\n', b'sig: 03a609edcd2c5a68dc16ea836fe4a259cc247e0d95a4d6a49bd3cb61b2a9d5e4ccbb65a8b3eb51a7fd9a7a1fe7a0c3c38ade85088977b3d2116ca5aafd0c32769b392ac3cf17cf79532ea06a9b4a5f61e7fdbf2a01cf3be2a249f2d1c605a6498f396b8750672de8fde7cffa1196e11dc7ce238449012e90e118b611846216d96d6d93345379971e059480141190aceaa3b3d2e32495260e5cbecda3e7fc3a5e093a696fb5b0c39fc9c14f400b1d5aa31174c1def65aac5b8cfafc2139ec41b0e662237d7ea325dc0612e4a414517d181f34a34c2cf8ea11117553eadf5ac806e0032f42afc8f343038fef5d08133af111b13c71193904448a19549ee2335fdb\n']
2022-03-16 21:24:36.914 - keylime.tpm - WARNING - PCR #0 in quote not found in tpm_policy, skipping.
2022-03-16 21:24:36.914 - keylime.tpm - ERROR - error parsing asn1 value: ParseError { kind: ShortData }
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 902, in verify_ek
    ek509 = x509.load_der_x509_certificate(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/x509/base.py", line 538, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
ValueError: error parsing asn1 value: ParseError { kind: ShortData }
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-03-16 21:24:36.932 - keylime.tenant - INFO - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 stopped
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 902, in verify_ek
    ek509 = x509.load_der_x509_certificate(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/x509/base.py", line 538, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
ValueError: error parsing asn1 value: ParseError { kind: ShortData }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/tenant.py", line 15, in main
    tenant.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1419, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1108, in do_quote
    raise e
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 1058, in do_quote
    if not self.validate_tpm_quote(public_key, quote, algorithms.Hash(hash_alg)):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 565, in validate_tpm_quote
    if not self.check_ek(self.registrar_data['ekcert']):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tenant.py", line 523, in check_ek
    elif not self.tpm_instance.verify_ek(base64.b64decode(ekcert)):
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 932, in verify_ek
    raise Exception("Error processing ek/ekcert. Does this TPM have a valid EK?").with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/keylime/tpm/tpm_main.py", line 902, in verify_ek
    ek509 = x509.load_der_x509_certificate(
  File "/usr/local/lib/python3.8/dist-packages/cryptography/x509/base.py", line 538, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
Exception: Error processing ek/ekcert. Does this TPM have a valid EK?
```

**Comment by THS-on** [comment]
@wahahaha123 does it work with `require_ek_cert` set to `False`?

**Comment by wahahaha123** [comment]
Sorry for taking so long to reply, after I set require_ek_cert=False, it works normally.

**Comment by THS-on** [comment]
Awesome! I think this can then be closed.

If you have further questions you can also join the `#keylime` channel on the [CNCF Slack](https://slack.cncf.io/).

**Comment by wahahaha123** [comment]
OK, thank you very much.
