### ISSUE TITLE
Incorrect exclude list validation in cloud_verifier

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#945]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora35
 * Processor architecture: x86_64
 * TPM Manufacturer: 
 * Keylime version: current upstream [e7dcad7]

# Description 
On
https://github.com/keylime/keylime/blob/master/keylime/cloud_verifier_common.py#L303
there is `lists.get('exclude')`  without a fallback option.

## Expected behavior vs. actual behavior 
cloud_verifier should deal with `exclude` key absence.

```
 2022-03-29 09:46:08.421 - keylime.cloudverifier - ERROR - 'exclude'
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/cloud_verifier_tornado.py", line 835, in invoke_get_quote
     failure = cloud_verifier_common.process_quote_response(agent, json_response['results'], agentAttestState)
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/cloud_verifier_common.py", line 143, in process_quote_response
     quote_validation_failure = get_tpm_instance().check_quote(
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/tpm/tpm_main.py", line 1195, in check_quote
     return self.check_pcrs(agentAttestState, tpm_policy, pcrs, data, False, ima_measurement_list, allowlist,
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/tpm/tpm_abstract.py", line 279, in check_pcrs
     ima_failure = AbstractTPM.__check_ima(agentAttestState, pcrs[config.IMA_PCR], ima_measurement_list, allowlist,
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/tpm/tpm_abstract.py", line 208, in __check_ima
     _, ima_failure = ima.process_measurement_list(agentAttestState, ima_measurement_list.split('\n'), allowlist,
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/ima.py", line 316, in process_measurement_list
     running_hash, failure = _process_measurement_list(agentAttestState, lines, hash_alg, lists=lists, m2w=m2w,
   File "/usr/local/lib/python3.10/site-packages/keylime-6.3.1-py3.10.egg/keylime/ima.py", line 220, in _process_measurement_list
     exclude_list = lists['exclude']
 KeyError: 'exclude'
```
## Steps to reproduce problem
1. modify tenant.py to send allowlist without `exclude` key:
```
            #self.allowlist = ima.process_allowlists(al_data, excl_data)
            self.allowlist = {'allowlist': al_data}
```

**Comment by THS-on** [comment]
Thanks for finding this. I already wanted to restructure the IMA allwlist/exclude API because it is more than that, but I haven't got around doing it.

**Comment by THS-on** [comment]
@mpeters can you assign this to me?

**Comment by maugustosilva** [comment]
Is it still relevant?

**Comment by THS-on** [comment]
I don't think so, because that entire code has changed. @kkaarreell can you confirm this?

**Comment by THS-on** [comment]
The IMA policy format now has changed significantly, so I don't think this issue applies anymore.
