### ISSUE TITLE
Verifier hangs on cfsslproc.communicate

### ISSUE THREAD

**Issue by edwards-n** [keylime/keylime#966]
# Environment
 * OS / version:  Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-37-generic x86_64)
 * Processor architecture: x86_64  Virtual Box Version 6.1.32 r149290 (Qt5.6.2)
 * TPM Manufacturer: Software emulated TPM installed by ./keylime/installer.sh -s
 * Keylime version: 9a03bd4

# Description 
When starting up for the first time after a fresh install keylime_verifier appears to hang on cfsslproc.communicate

## Expected behavior vs. actual behavior 
With the verifier running, attempting to start the keylime_registrar results in it exiting with the following message:
Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first.

More details in the next section.

## Steps to reproduce problem
With the verifier running, I tried to start the keylime_registrar and got the following (although the  verifier is running):
```
2022-04-06 14:09:45.955 - keylime.registrar - INFO - Setting up TLS...
Traceback (most recent call last):
  File "/usr/local/bin/keylime_registrar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/registrar.py", line 21, in main
    registrar_common.start(
  File "/usr/local/lib/python3.8/dist-packages/keylime/registrar_common.py", line 541, in start
    context, _ = web_util.init_mtls(section='registrar', generatedir='reg_ca', logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/keylime/web_util.py", line 67, in init_mtls
    raise Exception(
Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first
```
It seems the verifier is hung. Killing the verifier generates the following:
```
^CTraceback (most recent call last):
  File "/usr/local/bin/keylime_verifier", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/keylime/cmd/verifier.py", line 21, in main
    cloud_verifier_tornado.main()
  File "/usr/local/lib/python3.8/dist-packages/keylime/cloud_verifier_tornado.py", line 1105, in main
    context, mtls_options = web_util.init_mtls(logger=logger)
  File "/usr/local/lib/python3.8/dist-packages/keylime/web_util.py", line 57, in init_mtls
    ca_util.cmd_init(tls_dir)
  File "/usr/local/lib/python3.8/dist-packages/keylime/ca_util.py", line 151, in cmd_init
    cacert, ca_pk, _ = [ca_impl.mk](http://ca_impl.mk/)_cacert()  # pylint: disable=W0632
  File "/usr/local/lib/python3.8/dist-packages/keylime/ca_impl_cfssl.py", line 122, in mk_cacert
    stop_cfssl()
  File "/usr/local/lib/python3.8/dist-packages/keylime/ca_impl_cfssl.py", line 89, in stop_cfssl
    cfsslproc.communicate()
  File "/usr/lib/python3.8/subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```
So it looks like it is hung on cfsslproc.communicate(). I commented out cfsslproc.communicate() at line 89 of ca_impl_cfssl.py and the error goes away. 

```
diff --git a/keylime/ca_impl_cfssl.py b/keylime/ca_impl_cfssl.py
index 5a0db9a..20932bb 100644
--- a/keylime/ca_impl_cfssl.py
+++ b/keylime/ca_impl_cfssl.py
@@ -86,7 +86,7 @@ def stop_cfssl():
     global cfsslproc
     if cfsslproc is not None:
         cfsslproc.kill()
-        cfsslproc.communicate()
+        #cfsslproc.communicate()
         os.system("pkill -x cfssl")
         cfsslproc = None
```

The registrar, verifier start without exceptions and I can register the agent using the tenant..

**Comment by THS-on** [comment]
@sergio-correia any idea why you added `cfsslproc.communicate()` in https://github.com/keylime/keylime/pull/747?

**Comment by sergio-correia** [comment]
> @sergio-correia any idea why you added `cfsslproc.communicate()` in #747?

I don't remember exactly, but if I am not mistaken, it was fixing a leak reported by the cfssl (`test_ca_impl_cfssl.py`) unit tests.

**Comment by THS-on** [comment]
Ok, but why can this hang after a SIG_KILL?

**Comment by sergio-correia** [comment]
No idea yet. I will investigate this.

**Comment by THS-on** [comment]
@sergio-correia no need to investigate this any further. We decided to drop support for CFSSL. See #1012
