### ISSUE TITLE
Tenant add returns agent not found

### ISSUE THREAD

**Issue by iammrgenie** [keylime/keylime#988]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version:  Ubuntu 20.04
 * Processor architecture: 
 * TPM Manufacturer: Lenovo
 * Keylime version: 

# Description 
Testing out keylime with a lenovo laptop equipped with tpm2 and a virtualbox ubuntu vm as the verifier and registrar. Verifier runs fine and registrar seems to work fine with the client registered. However, when I try to run the tenant add operation, I get agent not found in registrar error. I am using cfssl.

## Steps to reproduce problem
1. sudo keylime_registrar
Reading configuration from ['/etc/keylime.conf']
2022-05-11 08:16:09.248 - keylime.keylime_db - INFO - database_url is set, using it to establish database connection
2022-05-11 08:16:09.323 - keylime.keylime_db - INFO - database_url is set, using it to establish database connection
2022-05-11 08:16:09.331 - alembic.env - INFO - Migrating database registrar
2022-05-11 08:16:09.332 - alembic.runtime.migration - INFO - Context impl PostgresqlImpl.
2022-05-11 08:16:09.332 - alembic.runtime.migration - INFO - Will assume transactional DDL.
2022-05-11 08:16:09.355 - keylime.registrar - INFO - Loaded 3 public keys from database
2022-05-11 08:16:09.368 - keylime.registrar - INFO - Setting up TLS...
2022-05-11 08:16:09.375 - keylime.registrar - INFO - Starting Cloud Registrar Server on ports 8890 and 8891 (TLS) use <Ctrl-C> to stop
2022-05-11 08:16:09.375 - keylime.registrar - INFO - Current API version 2.1
2022-05-11 08:16:09.376 - keylime.registrar - INFO - Supported older API versions: 1.0, 2.0
2022-05-11 08:16:09.376 - keylime.registrar - INFO - Deprecated API versions (soon to be removed): 1.0
2022-05-11 08:17:12.579 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:16.556 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:20.546 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:24.548 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:28.580 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:32.580 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:17:36.590 - keylime.registrar - INFO - GET returning 200 response for agent_id list
2022-05-11 08:19:40.891 - keylime.registrar - INFO - GET returning 200 response for agent_id: T14-G-01
2022-05-11 08:21:09.406 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-05-11 08:21:09.451 - keylime.tpm - INFO - Encrypting AIK for UUID ee297a92-615f-4a14-93c1-3cedc54cd154
2022-05-11 08:21:09.467 - keylime.registrar - INFO - POST returning key blob for agent_id: ee297a92-615f-4a14-93c1-3cedc54cd154
2022-05-11 08:21:10.734 - keylime.registrar - INFO - PUT activated: ee297a92-615f-4a14-93c1-3cedc54cd154
2022-05-11 08:22:27.654 - keylime.registrar - INFO - GET returning 200 response for agent_id: ee297a92-615f-4a14-93c1-3cedc54cd154
2022-05-11 08:25:30.189 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-05-11 08:25:30.381 - keylime.tpm - INFO - Encrypting AIK for UUID aac6de5f-0bbc-4baa-bd55-68444e95efa1
2022-05-11 08:25:30.392 - keylime.registrar - INFO - POST returning key blob for agent_id: aac6de5f-0bbc-4baa-bd55-68444e95efa1
2022-05-11 08:25:31.619 - keylime.registrar - INFO - PUT activated: aac6de5f-0bbc-4baa-bd55-68444e95efa1
2022-05-11 08:26:10.726 - keylime.registrar - INFO - GET returning 200 response for agent_id: aac6de5f-0bbc-4baa-bd55-68444e95efa1

2. sudo keylime_tenant -c add -t *host-ip* -v *vm-ip* -u aac6de5f-0bbc-4baa-bd55-68444e95efa1
Reading configuration from ['/etc/keylime.conf']
2022-05-11 08:26:10.711 - keylime.tpm - INFO - TPM2-TOOLS Version: 4.1.1
2022-05-11 08:26:10.713 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-05-11 08:26:10.714 - keylime.registrar_client - WARNING - TLS is enabled.
2022-05-11 08:26:10.714 - keylime.registrar_client - INFO - Setting up client TLS...
2022-05-11 08:26:10.727 - keylime.registrar_client - ERROR - ("read error: Error([('SSL routines', '', 'unexpected eof while reading')])",)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', '', 'unexpected eof while reading')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keylime/registrar_client.py", line 87, in getData
    response = client.get(f'/v{api_version}/agents/{agent_id}', cert=tls_cert_info, verify=ca_cert)
  File "/usr/local/lib/python3.8/dist-packages/keylime/requests_client.py", line 52, in get
    return self.session.get(self.base_url + url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 332, in recv_into
    raise ssl.SSLError("read error: %r" % e)
ssl.SSLError: ("read error: Error([('SSL routines', '', 'unexpected eof while reading')])",)
2022-05-11 08:26:10.731 - keylime.tenant - ERROR - Agent $aac6de5f-0bbc-4baa-bd55-68444e95efa1 data not found in the Registrar.

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by mpeters** [comment]
Are you running the `keylime_tenant` commands on the same machine with the verifier and/or registrar? If not, you need to copy over the CA certs that the verifier generates so that it's using the same ones as the verifier/registrar.

**Comment by iammrgenie** [comment]
> Are you running the `keylime_tenant` commands on the same machine with the verifier and/or registrar? If not, you need to copy over the CA certs that the verifier generates so that it's using the same ones as the verifier/registrar.

Yeah. The tenant, registrar, and verifier are on the same virtual machine. And the agent runs on the host machine. I checked the registrar database and I can see the details of the registered agent.

**Comment by THS-on** [comment]
Can you check the content of `/var/lib/keylime/cv_ca` and post the list of files here?


Also does switching to openssl help?

**Comment by iammrgenie** [comment]
> Can you check the content of `/var/lib/keylime/cv_ca` and post the list of files here?
> 
> Also does switching to openssl help?

Here is the content of the cv_ca folder along with the permissions. Using openssl has the same issues.
total 56
-rw------- 1 keylime keylime   451 May 11 13:54 ca-public.pem
-rw------- 1 keylime keylime  1314 May 11 13:54 cacert.crt
-rw------- 1 keylime keylime   475 May 11 13:54 cacrl.der
-rw------- 1 keylime keylime   694 May 11 13:54 cacrl.pem
-rw------- 1 keylime keylime  1456 May 11 13:54 client-cert.crt
-rw------- 1 keylime keylime  1704 May 11 13:54 client-private.pem
-rw------- 1 keylime keylime   451 May 11 13:54 client-public.pem
-rw------- 1 keylime keylime 13387 May 11 13:54 private.yml
-rw------- 1 keylime keylime  1464 May 11 13:54 vm-ver-02-cert.crt
-rw------- 1 keylime keylime  1704 May 11 13:54 vm-ver-02-private.pem
-rw------- 1 keylime keylime   451 May 11 13:54 vm-ver-02-public.pem
