### ISSUE TITLE
The `verifier` is leaving a node in "Get Quote" state when the `agent` running there becomes unreachable (e.g., kernel panic)

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#996]
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora Core 35
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: post-6.4.0

# Description 

The `agent` running on a node suddenly becomes unreachable due to the fact that the node suffered a failure (e.g., power outage, kernel panic). The `verifier` fails to contact it, prints out an error on the log, but the `agent`'s state is still shown as "Get Quote"

## Expected behavior vs. actual behavior 

The `verifier` needs to place the `agent` in the FAILED state
 
## Steps to reproduce problem
1. Add a single `agent` to a `verifier`
2. Shutdown the NIC on the node where the `agent` is running
3. Watch for error in `verifier`'s log
4. Query the status of the `agent`

# Relevant logs

`Verifier` log

```
2022-05-19 18:03:11.582 - keylime.cloudverifier - DEBUG - Setting up callback to check again in 5.000000 seconds
2022-05-19 18:03:36.601 - keylime.cloudverifier - INFO - Connection to 100.127.0.14 refused after 1/5 tries, trying again in 2.000000 seconds
2022-05-19 18:03:58.618 - keylime.cloudverifier - INFO - Connection to 100.127.0.14 refused after 2/5 tries, trying again in 4.000000 seconds
2022-05-19 18:04:05.679 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f6f7e6310d0>>, <Task finished name='Task-146' coro=<invoke_get_quote() done, defined at /usr/local/lib/python3.9/site-packages/keylime-6.4.0-py3.9.egg/keylime/cloud_verifier_tornado.py:751> exception=OSError(113, 'No route to host')>)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/lib64/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.9/site-packages/keylime-6.4.0-py3.9.egg/keylime/cloud_verifier_tornado.py", line 777, in invoke_get_quote
    response = await res
  File "/usr/local/lib/python3.9/site-packages/keylime-6.4.0-py3.9.egg/keylime/tornado_requests.py", line 37, in request
    response = await http_client.fetch(req)
OSError: [Errno 113] No route to host
```

**Comment by mpeters** [comment]
> The verifier needs to place the agent in the FAILED state

I wonder if we need another state. Maybe `UNREACHABLE`? As we have more IoT and Edge scenarios, network connectivity will be a real issue and allowing the user to decide if they should treat `UNREACHABLE` and `FAILED` as the same thing or not seems like a good feature.

**Comment by THS-on** [comment]
> I wonder if we need another state. Maybe UNREACHABLE? As we have more IoT and Edge scenarios, network connectivity will be a real issue and allowing the user to decide if they should treat UNREACHABLE and FAILED as the same thing or not seems like a good feature.

Not really because we already have the event IDs for that. The device is still failed because otherwise an attacker could just take the device offline to get a less severe failure.

**Comment by mpeters** [comment]
> Not really because we already have the event IDs for that. 

That is true, so at least we can distinguish between them.

> The device is still failed because otherwise an attacker could just take the device offline to get a less severe failure.

Then the integrity failure would become apparent upon the next reboot, correct?

Being offline isn't necessarily an integrity problem, it's an availability problem. Keylime shouldn't really be an availability monitor but an integrity one. I still think there's an inherent difference between a known integrity failure and a known availability failure that may or may not have an integrity failure. And allowing them to be treated differently is valuable.

**Comment by maugustosilva** [comment]
Fair point, and a user can choose to treat them differently, if he so decides, thanks to the event IDs.
